/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.domains.transfer;

import EPPClient.domains.Domain;

import javax.swing.*;
import java.awt.*;

public class BulkTransferPanel extends JPanel
{

  /**
   * Creates new form AddressPanel
   */
  public BulkTransferPanel()
  {
    initComponents();
    domain = new DomainTransfer();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    lblAuthInfo = new JLabel();
    jScrollPane1 = new JScrollPane();
    bulkRequestField = new JTextArea();
    jScrollPane2 = new JScrollPane();
    bulkResultField = new JTextArea();

    //---- lblAuthInfo ----
    lblAuthInfo.setText("domain;authinfo");

    //======== jScrollPane1 ========
    {

      //---- bulkRequestField ----
      bulkRequestField.setColumns(30);
      bulkRequestField.setRows(10);
      bulkRequestField.setMinimumSize(new Dimension(484, 274));
      jScrollPane1.setViewportView(bulkRequestField);
    }

    //======== jScrollPane2 ========
    {

      //---- bulkResultField ----
      bulkResultField.setEditable(false);
      bulkResultField.setColumns(30);
      bulkResultField.setRows(10);
      bulkResultField.setMinimumSize(new Dimension(484, 274));
      jScrollPane2.setViewportView(bulkResultField);
    }

    GroupLayout layout = new GroupLayout(this);
    setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup()
                    .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lblAuthInfo)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup()
                                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup()
                    .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup()
                                    .addComponent(lblAuthInfo)
                                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  String getBulkRequest()
  {
    String bulkRequest = bulkRequestField.getText();
    return bulkRequest;
  }

  public void setAddress(Domain domain)
  {
    if (domain != null)
    {
//            setDomainName(domain.getDomainName());
//            setRegistrant(domain.getRegistrant());
//            setAuthInfo(domain.getAuthInfo());
    }
  }

  public DomainTransfer getDomainTransfer()
  {
//        getDomainName();
//        getRegistrant();
//        getAuthInfo();
//        getNewAuthInfo();
//        getIsTrade();
//        getIsCancel();
    return domain;
  }


  public void clear()
  {
//        txtDomainName.setText(null);
//        txtAuthInfo.setText(null);
//        txtIsTrade.setSelected(false);
//        txtIsCancel.setSelected(false);
//        txtRegistrant.setText(null);
//        txtNewAuthInfo.setText(null);
//        domain = new DomainTransfer();
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel lblAuthInfo;
  private JScrollPane jScrollPane1;
  private JTextArea bulkRequestField;
  private JScrollPane jScrollPane2;
  private JTextArea bulkResultField;
  // End of variables declaration//GEN-END:variables

  boolean isEditable;
  DomainTransfer domain;

}
