/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.domains.transfer;

import EPPClient.contacts.ContactSelection;
import EPPClient.domains.Domain;

import javax.swing.*;
import javax.swing.border.SoftBevelBorder;
import java.awt.*;

public class TransferPanel extends JPanel
{

  /**
   * Creates new form AddressPanel
   */
  public TransferPanel()
  {
    initComponents();
    domain = new DomainTransfer();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    lblRegistrant = new JLabel();
    txtRegistrant = new JTextField();
    lblAuthInfo = new JLabel();
    txtAuthInfo = new JTextField();
    lblDomainName = new JLabel();
    txtDomainName = new JTextField();
    setRegistrant = new JButton();
    txtIsTrade = new JCheckBox();
    txtNewAuthInfo = new JTextField();
    lblNewAuthInfo = new JLabel();
    txtIsCancel = new JCheckBox();

    setLayout(new GridBagLayout());

    //---- lblRegistrant ----
    lblRegistrant.setText("registrant");
    add(lblRegistrant, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
            GridBagConstraints.EAST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- txtRegistrant ----
    txtRegistrant.setEditable(false);
    txtRegistrant.setPreferredSize(new Dimension(200, 20));
    add(txtRegistrant, new GridBagConstraints(1, 3, 1, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- lblAuthInfo ----
    lblAuthInfo.setText("authInfo");
    add(lblAuthInfo, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
            GridBagConstraints.EAST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- txtAuthInfo ----
    txtAuthInfo.setMinimumSize(new Dimension(100, 21));
    txtAuthInfo.setPreferredSize(new Dimension(200, 20));
    add(txtAuthInfo, new GridBagConstraints(1, 1, 3, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- lblDomainName ----
    lblDomainName.setText("domainName");
    add(lblDomainName, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
            GridBagConstraints.EAST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- txtDomainName ----
    txtDomainName.setMinimumSize(new Dimension(150, 20));
    txtDomainName.setPreferredSize(new Dimension(150, 20));
    add(txtDomainName, new GridBagConstraints(1, 0, 1, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- setRegistrant ----
    setRegistrant.setText("Selezione Registrant");
    setRegistrant.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
    setRegistrant.setPreferredSize(new Dimension(120, 20));
    setRegistrant.addActionListener(e -> setRegistrantActionPerformed(e));
    add(setRegistrant, new GridBagConstraints(2, 3, 4, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- txtIsTrade ----
    txtIsTrade.setText("isTrade");
    txtIsTrade.addActionListener(e -> txtIsTradeActionPerformed(e));
    add(txtIsTrade, new GridBagConstraints(1, 2, 1, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0), 0, 0));

    //---- txtNewAuthInfo ----
    txtNewAuthInfo.setMinimumSize(new Dimension(100, 21));
    txtNewAuthInfo.setPreferredSize(new Dimension(200, 20));
    add(txtNewAuthInfo, new GridBagConstraints(1, 4, 3, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- lblNewAuthInfo ----
    lblNewAuthInfo.setText("newAuthInfo");
    add(lblNewAuthInfo, new GridBagConstraints(0, 4, 1, 1, 0.0, 0.0,
            GridBagConstraints.EAST, GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5), 0, 0));

    //---- txtIsCancel ----
    txtIsCancel.setText("cancelTransfer");
    txtIsCancel.addActionListener(e -> txtIsCancelActionPerformed(e));
    add(txtIsCancel, new GridBagConstraints(3, 2, 1, 1, 0.0, 0.0,
            GridBagConstraints.WEST, GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0), 0, 0));
  }// </editor-fold>//GEN-END:initComponents

  private void setRegistrantActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_setRegistrantActionPerformed
    JFrame frame = new JFrame();
    ContactSelection cs = new ContactSelection(frame, this, getDomainName(), 1);
    cs.setSize(400, 600);
    cs.setVisible(true);
    String newRegistrant = cs.getValidatedText();

    if (newRegistrant != null)
    {
      if (newRegistrant.length() > 0)
      {
        txtRegistrant.setText(newRegistrant);
      }
    }
  }//GEN-LAST:event_setRegistrantActionPerformed

  private void txtIsTradeActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_txtIsTradeActionPerformed
    setEditable(isEditable);
  }//GEN-LAST:event_txtIsTradeActionPerformed

  private void txtIsCancelActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_txtIsCancelActionPerformed
    setEditable(isEditable);
  }//GEN-LAST:event_txtIsCancelActionPerformed

  void setDomainName(String domainName)
  {
    domain.setAuthInfo(domainName);
    txtDomainName.setText(domainName);
  }

  String getDomainName()
  {
    String domainName = txtDomainName.getText();
    domain.setDomainName(domainName);
    return domainName;
  }

  void setAuthInfo(String authInfo)
  {
    domain.setAuthInfo(authInfo);
    txtAuthInfo.setText(authInfo);
  }

  String getAuthInfo()
  {
    String authInfo = txtAuthInfo.getText();
    domain.setAuthInfo(authInfo);
    return authInfo;
  }

  void setNewAuthInfo(String newAuthInfo)
  {
    domain.setNewAuthInfo(newAuthInfo);
    txtNewAuthInfo.setText(newAuthInfo);
  }

  String getNewAuthInfo()
  {
    String newAuthInfo = txtNewAuthInfo.getText();
    domain.setNewAuthInfo(newAuthInfo);
    return newAuthInfo;
  }

  void setRegistrant(String registrant)
  {
    domain.setRegistrant(registrant);
    txtRegistrant.setText(registrant);
  }

  String getRegistrant()
  {
    String registrant = txtRegistrant.getText();
    if (!registrant.equals(domain.getRegistrant()))
    {
      domain.setRegistrant(registrant);
    }
    return registrant;
  }

  void setIsTrade(boolean isTrade)
  {
    domain.setIsTrade(isTrade);
    txtIsTrade.setSelected(isTrade);
  }

  boolean getIsTrade()
  {
    boolean isTrade = txtIsTrade.isSelected();
    domain.setIsTrade(isTrade);
    return isTrade;
  }

  void setIsCancel(boolean isCancel)
  {
    domain.setIsCancel(isCancel);
    txtIsCancel.setSelected(isCancel);
  }

  boolean getIsCancel()
  {
    boolean isCancel = txtIsCancel.isSelected();
    domain.setIsCancel(isCancel);
    return isCancel;
  }


  public void setAddress(Domain domain)
  {
    if (domain != null)
    {
      setDomainName(domain.getDomainName());
      setRegistrant(domain.getRegistrant());
      setAuthInfo(domain.getAuthInfo());
    }
  }

  public DomainTransfer getDomainTransfer()
  {
    getDomainName();
    getRegistrant();
    getAuthInfo();
    getNewAuthInfo();
    getIsTrade();
    getIsCancel();
    return domain;
  }


  public void clear()
  {
    txtDomainName.setText(null);
    txtAuthInfo.setText(null);
    txtIsTrade.setSelected(false);
    txtIsCancel.setSelected(false);
    txtRegistrant.setText(null);
    txtNewAuthInfo.setText(null);
    domain = new DomainTransfer();
  }

  public void setEditable(boolean bEditable)
  {
    txtDomainName.setEditable(bEditable);
    txtAuthInfo.setEditable(bEditable);

    txtIsTrade.setEnabled(bEditable);
    txtIsCancel.setEnabled(bEditable);

    txtIsCancel.setVisible(bEditable && !txtIsTrade.isSelected());
    txtIsTrade.setVisible(bEditable && !txtIsCancel.isSelected());

    lblRegistrant.setVisible(bEditable && txtIsTrade.isSelected());
    txtRegistrant.setVisible(bEditable && txtIsTrade.isSelected());
    setRegistrant.setVisible(bEditable && txtIsTrade.isSelected());
    setRegistrant.setEnabled(bEditable && txtIsTrade.isSelected());

    lblNewAuthInfo.setVisible(bEditable && txtIsTrade.isSelected());
    txtNewAuthInfo.setVisible(bEditable && txtIsTrade.isSelected());
    txtNewAuthInfo.setEnabled(bEditable && txtIsTrade.isSelected());


    isEditable = bEditable;
  }

  public boolean isEditable()
  {
    return isEditable;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel lblRegistrant;
  private JTextField txtRegistrant;
  private JLabel lblAuthInfo;
  private JTextField txtAuthInfo;
  private JLabel lblDomainName;
  private JTextField txtDomainName;
  private JButton setRegistrant;
  private JCheckBox txtIsTrade;
  private JTextField txtNewAuthInfo;
  private JLabel lblNewAuthInfo;
  private JCheckBox txtIsCancel;
  // End of variables declaration//GEN-END:variables

  boolean isEditable;
  DomainTransfer domain;

}
