/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package com.codetotime.eppclient.domains.transfer;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.event.EventListenerList;

/**
 * Toolbar panel with Request Transfer and Cancel buttons for domain transfer operations. Each
 * button fires an {@link ActionEvent} to registered listeners.
 */
public class TransferActionPanel extends JPanel {

  /** Creates new form AddressActionPanel. */
  public TransferActionPanel() {
    initComponents();
    listeners = new EventListenerList();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    btnSaveAddress = new JButton();
    btnCancelAddress = new JButton();

    setLayout(new GridLayout());

    // ---- btnSaveAddress ----
    btnSaveAddress.setText("Request Transfer");
    btnSaveAddress.setActionCommand("SAVE_ADDRESS");
    btnSaveAddress.addActionListener(e -> saveAddressActionPerformed(e));
    add(btnSaveAddress);

    // ---- btnCancelAddress ----
    btnCancelAddress.setText("Cancel");
    btnCancelAddress.setActionCommand("CANCEL_ADDRESS");
    btnCancelAddress.addActionListener(e -> cancelAddressActionPerformed(e));
    add(btnCancelAddress);
  } // </editor-fold>//GEN-END:initComponents

  private void cancelAddressActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_cancelAddressActionPerformed
    fireActionEvent(evt);
  } // GEN-LAST:event_cancelAddressActionPerformed

  private void saveAddressActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_saveAddressActionPerformed
    fireActionEvent(evt);
  } // GEN-LAST:event_saveAddressActionPerformed

  private void fireActionEvent(ActionEvent evt) {
    ActionListener[] listenerList = listeners.getListeners(ActionListener.class);

    for (int i = listenerList.length - 1; i >= 0; --i) {
      listenerList[i].actionPerformed(evt);
    }
  }

  /**
   * Registers a listener to receive action events from all buttons in this panel.
   *
   * @param listener the listener to add
   */
  public void addActionListener(ActionListener listener) {
    listeners.add(ActionListener.class, listener);
  }

  /**
   * Removes a previously registered action listener.
   *
   * @param listener the listener to remove
   */
  public void removeActionListener(ActionListener listener) {
    if (listeners != null) {
      listeners.remove(ActionListener.class, listener);
    }
  }

  EventListenerList listeners;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton btnSaveAddress;
  private JButton btnCancelAddress;
  // End of variables declaration//GEN-END:variables

}
