/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package com.codetotime.eppclient.domains.transfer;

import com.codetotime.eppclient.uplink.EPPuplink;
import it.nic.epp.client.commands.transform.DomainTransfer;
import it.nic.epp.client.exceptions.EppSchemaException;
import it.nic.epp.client.responses.HttpBaseResponse;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.LayoutStyle;
import org.apache.xmlbeans.XmlException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Frame for submitting EPP domain transfer and trade requests, supporting both single and bulk
 * modes via a tabbed panel, and dispatching commands through the active EPP connection.
 */
public class TransferManagement extends JFrame implements ActionListener {
  private static final Logger log = LoggerFactory.getLogger(TransferManagement.class);

  /** Creates new form DomainTransferFrame. */
  public TransferManagement(EPPuplink EPPuplink) {
    initComponents();

    this.EPPuplink = EPPuplink;

    transferActionPanel.addActionListener(this);

    domainTransferPanel.setEditable(true);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    transferActionPanel = new TransferActionPanel();
    transferTab = new JTabbedPane();
    domainTransferPanel = new TransferPanel();
    bulkTransferPanel = new BulkTransferPanel();

    // ======== this ========
    Container contentPane = getContentPane();

    // ======== transferTab ========
    {
      transferTab.addTab("Single transfer/transferTrade", domainTransferPanel);
      transferTab.addTab("Bulk transfer", bulkTransferPanel);
    }

    GroupLayout contentPaneLayout = new GroupLayout(contentPane);
    contentPane.setLayout(contentPaneLayout);
    contentPaneLayout.setHorizontalGroup(
        contentPaneLayout
            .createParallelGroup()
            .addGroup(
                contentPaneLayout
                    .createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        transferActionPanel,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            .addGroup(
                contentPaneLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        transferTab, GroupLayout.PREFERRED_SIZE, 457, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    contentPaneLayout.setVerticalGroup(
        contentPaneLayout
            .createParallelGroup()
            .addGroup(
                contentPaneLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        transferTab, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                    .addComponent(
                        transferActionPanel,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    pack();
    setLocationRelativeTo(getOwner());
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private TransferActionPanel transferActionPanel;
  private JTabbedPane transferTab;
  private TransferPanel domainTransferPanel;
  private BulkTransferPanel bulkTransferPanel;

  // End of variables declaration//GEN-END:variables

  private void requestTransfer() {
    boolean canClose = true;

    if (transferTab.getSelectedIndex() == 0) {

      com.codetotime.eppclient.domains.transfer.DomainTransfer domain =
          domainTransferPanel.getDomainTransfer();

      try {

        DomainTransfer domainTransfer = new DomainTransfer();
        domainTransfer.setName(domain.getDomainName());
        domainTransfer.setAuthInfo(domain.getAuthInfo());

        if (domain.getIsCancel()) {
          domainTransfer.setTransferCancel();
        } else {
          domainTransfer.setTransferRequest();

          if (domain.getIsTrade()) {
            domainTransfer.setExtTransferTrade(domain.getRegistrant(), domain.getNewAuthInfo());
          }
        }

        log.info("CLIENT transfer request: {}", domainTransfer.toString());
        HttpBaseResponse response = EPPuplink.sendCommand(domainTransfer);

        if (response.isSuccessfully()) {
          if (domain.getIsCancel()) {
            JOptionPane.showMessageDialog(
                this,
                "The transfer has been successfully cancelled at the Registry.",
                "Registry transfer cancellation",
                JOptionPane.INFORMATION_MESSAGE);
          } else {
            JOptionPane.showMessageDialog(
                this,
                "The transfer has been successfully requested and is Pending.\n\nYou will receive a message after ACK/NACK",
                "Registry transfer confirmation",
                JOptionPane.INFORMATION_MESSAGE);
          }

        } else {
          if (JOptionPane.showConfirmDialog(
                  this,
                  "An error occurred while requesting transfer at the Registry.\n\nDo you want to see the Registry XML response?",
                  "Registry transfer failure",
                  JOptionPane.YES_NO_OPTION,
                  JOptionPane.WARNING_MESSAGE)
              == 0) {
            JOptionPane.showMessageDialog(this, response.toString());
          }
          canClose = false;
        }

        log.info("SERVER transfer response: {}", response.toString());

      } catch (NullPointerException v) {
      } catch (XmlException v) {
      } catch (IOException v) {
      } catch (EppSchemaException v) {
      }

      if (canClose) {
        this.dispose();
      }
    } else {
      // BULK TRANSFER

      String[] bulkRequestLines = bulkTransferPanel.getBulkRequest().split("\\r?\\n");

      for (String bulkRequestLine : bulkRequestLines) {

        String[] bulkRequestEntries = bulkRequestLine.split(":");

        try {
          DomainTransfer domainTransfer = new DomainTransfer();
          domainTransfer.setName(bulkRequestEntries[0]);
          domainTransfer.setAuthInfo(bulkRequestEntries[1]);
          domainTransfer.setTransferRequest();

          log.info("CLIENT bulk transfer request: {}", domainTransfer.toString());
          HttpBaseResponse response = EPPuplink.sendCommand(domainTransfer);

          if (response.isSuccessfully()) {
            JOptionPane.showMessageDialog(
                this,
                "The transfer has been successfully requested for "
                    + bulkRequestEntries[0]
                    + " and is Pending.\n\nYou will receive a message after ACK/NACK",
                "Registry transfer confirmation",
                JOptionPane.INFORMATION_MESSAGE);
          } else {
            if (JOptionPane.showConfirmDialog(
                    this,
                    "An error occurred while requesting transfer at the Registry.\n\nDo you want to see the Registry XML response?",
                    "Registry transfer failure",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE)
                == 0) {
              JOptionPane.showMessageDialog(this, response.toString());
            }
          }
          log.info("SERVER bulk transfer response: {}", response.toString());

        } catch (NullPointerException v) {
        } catch (XmlException v) {
        } catch (IOException v) {
        }
      }
    }
  }

  private void cancelTransfer() {
    this.dispose();
  }

  /** {@inheritDoc} */
  public void actionPerformed(ActionEvent e) {
    String actionCommand = e.getActionCommand();
    log.debug("ActionEvent: {}", actionCommand);
    if (actionCommand.equalsIgnoreCase("CANCEL_ADDRESS")) {
      cancelTransfer();
    } else if (actionCommand.equalsIgnoreCase("SAVE_ADDRESS")) {
      requestTransfer();
    }
  }

  private EPPuplink EPPuplink;
}
