/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.domains;

import java.awt.event.*;
import EPPClient.config.EPPparams;
import EPPClient.contacts.ContactSelection;

import javax.swing.*;
import javax.swing.border.SoftBevelBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.net.IDN;
import java.util.Date;
import java.util.Vector;

public class DomainPanel extends JPanel
{
    boolean dnsSecEnabled = Boolean.parseBoolean(EPPparams.getParameter("EppClient.implement.DNSSEC"));
  /**
   * Creates new form AddressPanel
   */
  private void createUIComponents() {
    // TODO: add custom component creation code here
  }

  private void dbengineActionPerformed(ActionEvent e) {
      // TODO add your code here
  }

  public DomainPanel()
  {
    initComponents();
    domain = new Domain();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

  private void initComponents() {
      lblDomainClientStatus = new JLabel();
      lblRegistrant = new JLabel();
      txtRegistrant = new JTextField();
      lblAdmin = new JLabel();
      lblTech = new JLabel();
      lblAuthInfo = new JLabel();
      txtAuthInfo = new JTextField();
      lblNameServer = new JLabel();
      txtNameServerToAdd = new JTextField();
      lblDomainName = new JLabel();
      txtDomainName = new JTextField();
      txtDomainName.getDocument().addDocumentListener(new DocumentListener() {
        public void changedUpdate(DocumentEvent e) {
          updatePunyDomainName();
        }
        public void removeUpdate(DocumentEvent e) {
          updatePunyDomainName();
        }
        public void insertUpdate(DocumentEvent e) {
          updatePunyDomainName();
        }

      });
      jScrollPane1 = new JScrollPane();
      txtStatus = new JList<>();
      jScrollPane2 = new JScrollPane();
      txtNameServer = new javax.swing.JList(nameServerModel);
      addNameServer = new JButton();
      remNameServer = new JButton();
      jScrollPane3 = new JScrollPane();
      txtTech = new javax.swing.JList(techModel);
      addTech = new JButton();
      remTech = new JButton();
      addAdmin = new JButton();
      remAdmin = new JButton();
      jScrollPane4 = new JScrollPane();
      txtAdmin = new javax.swing.JList(adminModel);
      setRegistrant = new JButton();
      lblDnsExpl = new JLabel();
      txtPunyDomainName = new JTextField();
      lblPunyDomainName = new JLabel();
      btnRndAuthinfo = new JButton();
      lblValidationCode = new JLabel();
      txtValidationCode = new JTextField();
      lblIsPendingDelete = new JLabel();
      lblDnsSec = new JLabel();
      panelDnsSec = new JPanel();
      lblKeyTag = new JLabel();
      txtAlg = new JTextField();
      lblAlg = new JLabel();
      cmbAlg = new JComboBox<>();
      lblDigestType = new JLabel();
      cmbDigestType = new JComboBox<>();
      lblDigest = new JLabel();
      scrollPane1 = new JScrollPane();
      txtDigest = new JTextArea();
      chkDNSSEC = new JCheckBox();

      //======== this ========
      setMinimumSize(new Dimension(600, 327));
      setLayout(new GridBagLayout());

      //---- lblDomainClientStatus ----
      lblDomainClientStatus.setHorizontalAlignment(SwingConstants.RIGHT);
      lblDomainClientStatus.setText("domainClientStatus");
      lblDomainClientStatus.setHorizontalTextPosition(SwingConstants.RIGHT);
      lblDomainClientStatus.setPreferredSize(new Dimension(160, 20));
      add(lblDomainClientStatus, new GridBagConstraints(4, 0, 2, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblRegistrant ----
      lblRegistrant.setText("registrant");
      add(lblRegistrant, new GridBagConstraints(0, 7, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtRegistrant ----
      txtRegistrant.setEditable(false);
      txtRegistrant.setPreferredSize(new Dimension(200, 20));
      add(txtRegistrant, new GridBagConstraints(1, 7, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblAdmin ----
      lblAdmin.setText("admin");
      add(lblAdmin, new GridBagConstraints(0, 8, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblTech ----
      lblTech.setText("tech");
      add(lblTech, new GridBagConstraints(0, 10, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblAuthInfo ----
      lblAuthInfo.setText("authInfo");
      add(lblAuthInfo, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtAuthInfo ----
      txtAuthInfo.setMinimumSize(new Dimension(150, 20));
      txtAuthInfo.setPreferredSize(new Dimension(150, 20));
      add(txtAuthInfo, new GridBagConstraints(1, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblNameServer ----
      lblNameServer.setText("nameServer");
      add(lblNameServer, new GridBagConstraints(0, 12, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtNameServerToAdd ----
      txtNameServerToAdd.setMaximumSize(new Dimension(200, 20));
      txtNameServerToAdd.setMinimumSize(new Dimension(0, 20));
      txtNameServerToAdd.setPreferredSize(new Dimension(150, 20));
      add(txtNameServerToAdd, new GridBagConstraints(3, 12, 4, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDomainName ----
      lblDomainName.setText("domainName");
      add(lblDomainName, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtDomainName ----
      txtDomainName.setMinimumSize(new Dimension(150, 20));
      txtDomainName.setPreferredSize(new Dimension(150, 20));
      add(txtDomainName, new GridBagConstraints(1, 1, 1, 1, 1.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //======== jScrollPane1 ========
      {

          //---- txtStatus ----
          txtStatus.setModel(new AbstractListModel<String>() {
              String[] values = {
                  "clientDeleteProhibited",
                  "clientTransferProhibited",
                  "clientUpdateProhibited"
              };
              @Override
              public int getSize() { return values.length; }
              @Override
              public String getElementAt(int i) { return values[i]; }
          });
          txtStatus.setMaximumSize(new Dimension(150, 80));
          txtStatus.setMinimumSize(new Dimension(150, 80));
          txtStatus.setPreferredSize(new Dimension(150, 80));
          txtStatus.setVisibleRowCount(4);
          jScrollPane1.setViewportView(txtStatus);
          jScrollPane1.setMinimumSize(new Dimension(180, 88));
          jScrollPane1.setPreferredSize(new Dimension(180, 88));
      }
      add(jScrollPane1, new GridBagConstraints(4, 1, 3, 3, 0.0, 0.0,
          GridBagConstraints.NORTH, GridBagConstraints.BOTH,
          new Insets(5, 5, 5, 5), 0, 0));

      //======== jScrollPane2 ========
      {

          //---- txtNameServer ----
          txtNameServer.setFixedCellWidth(198);
          txtNameServer.setPreferredSize(new Dimension(150, 50));
          jScrollPane2.setViewportView(txtNameServer);
      }
      add(jScrollPane2, new GridBagConstraints(1, 12, 1, 5, 1.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.BOTH,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- addNameServer ----
      addNameServer.setText("+");
      addNameServer.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      addNameServer.setPreferredSize(new Dimension(20, 20));
      addNameServer.addActionListener(e -> addNameServerActionPerformed(e));
      add(addNameServer, new GridBagConstraints(2, 12, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- remNameServer ----
      remNameServer.setText("-");
      remNameServer.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      remNameServer.setPreferredSize(new Dimension(20, 20));
      remNameServer.addActionListener(e -> remNameServerActionPerformed(e));
      add(remNameServer, new GridBagConstraints(2, 13, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //======== jScrollPane3 ========
      {

          //---- txtTech ----
          txtTech.setFixedCellWidth(198);
          txtTech.setVisibleRowCount(3);
          txtTech.setMaximumSize(new Dimension(150, 60));
          txtTech.setMinimumSize(new Dimension(150, 60));
          txtTech.setPreferredSize(new Dimension(150, 60));
          jScrollPane3.setViewportView(txtTech);
          jScrollPane3.setMinimumSize(new Dimension(180, 68));
          jScrollPane3.setPreferredSize(new Dimension(180, 68));
      }
      add(jScrollPane3, new GridBagConstraints(1, 10, 1, 2, 0.0, 0.0,
          GridBagConstraints.NORTH, GridBagConstraints.BOTH,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- addTech ----
      addTech.setText("+");
      addTech.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      addTech.setPreferredSize(new Dimension(20, 20));
      addTech.addActionListener(e -> addTechActionPerformed(e));
      add(addTech, new GridBagConstraints(2, 10, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- remTech ----
      remTech.setText("-");
      remTech.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      remTech.setPreferredSize(new Dimension(20, 20));
      remTech.addActionListener(e -> remTechActionPerformed(e));
      add(remTech, new GridBagConstraints(2, 11, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- addAdmin ----
      addAdmin.setText("+");
      addAdmin.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      addAdmin.setPreferredSize(new Dimension(20, 20));
      addAdmin.addActionListener(e -> addAdminActionPerformed(e));
      add(addAdmin, new GridBagConstraints(2, 8, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- remAdmin ----
      remAdmin.setText("-");
      remAdmin.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      remAdmin.setPreferredSize(new Dimension(20, 20));
      remAdmin.addActionListener(e -> remAdminActionPerformed(e));
      add(remAdmin, new GridBagConstraints(2, 9, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //======== jScrollPane4 ========
      {

          //---- txtAdmin ----
          txtAdmin.setFixedCellWidth(198);
          txtAdmin.setVisibleRowCount(3);
          txtAdmin.setMaximumSize(new Dimension(150, 60));
          txtAdmin.setMinimumSize(new Dimension(150, 60));
          txtAdmin.setPreferredSize(new Dimension(150, 60));
          jScrollPane4.setViewportView(txtAdmin);
          jScrollPane4.setMinimumSize(new Dimension(180, 68));
          jScrollPane4.setPreferredSize(new Dimension(180, 68));
      }
      add(jScrollPane4, new GridBagConstraints(1, 8, 1, 2, 0.0, 0.0,
          GridBagConstraints.NORTH, GridBagConstraints.BOTH,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- setRegistrant ----
      String lblChgRegistrant = "";
      if (isEditable) {
          if (getOpType()==1) {
              lblChgRegistrant = "Selezione Registrant";
          } else {
              lblChgRegistrant = "Cambio Registrant";
          }
      }
      setRegistrant.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      setRegistrant.setPreferredSize(new Dimension(120, 20));
      setRegistrant.addActionListener(e -> setRegistrantActionPerformed(e));
      add(setRegistrant, new GridBagConstraints(2, 7, 3, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDnsExpl ----
      lblDnsExpl.setFont(new Font("Tahoma", Font.PLAIN, 10));
      lblDnsExpl.setText("<HTML><P ALIGN=\"CENTER\"><B>NOTE DI COMPILAZIONE</B></P><BR/>\n<P>In caso di nameserver subordinati al dominio &egrave; necessario indicare il/gli indirizzi IP separandoli con il carattere \"@\".<BR/>\nSono supportati sia IPv4 che IPv6, es.:<BR/>\nSolo IPv4: \"dns.example.it@11.22.33.44\"<BR/>\nIPv4+IPv6: \"dns.example.it@11.22.33.44@3ff3:1:2:3:4:5:6:7\"</P></HTML>");
      lblDnsExpl.setVerticalAlignment(SwingConstants.TOP);
      lblDnsExpl.setMaximumSize(new Dimension(150, 120));
      lblDnsExpl.setMinimumSize(new Dimension(150, 120));
      lblDnsExpl.setPreferredSize(new Dimension(150, 120));
      add(lblDnsExpl, new GridBagConstraints(2, 14, 5, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtPunyDomainName ----
      txtPunyDomainName.setMinimumSize(new Dimension(150, 20));
      txtPunyDomainName.setPreferredSize(new Dimension(150, 20));
      add(txtPunyDomainName, new GridBagConstraints(1, 2, 1, 1, 1.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblPunyDomainName ----
      lblPunyDomainName.setText("IDN Punycode");
      add(lblPunyDomainName, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- btnRndAuthinfo ----
      btnRndAuthinfo.setText("genera authInfo");
      btnRndAuthinfo.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
      btnRndAuthinfo.addActionListener(e -> btnRndAuthinfoActionPerformed(e));
      add(btnRndAuthinfo, new GridBagConstraints(1, 4, 1, 1, 0.0, 0.0,
          GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
          new Insets(0, 5, 5, 5), 0, 0));

      //---- lblValidationCode ----
      lblValidationCode.setText("validationCode (.gov.it)");
      add(lblValidationCode, new GridBagConstraints(0, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtValidationCode ----
      txtValidationCode.setMinimumSize(new Dimension(150, 20));
      txtValidationCode.setPreferredSize(new Dimension(150, 20));
      add(txtValidationCode, new GridBagConstraints(1, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblIsPendingDelete ----
      lblIsPendingDelete.setIcon(new ImageIcon(getClass().getResource("/warn16_1.gif")));
      lblIsPendingDelete.setText("pendingDelete");
      lblIsPendingDelete.setEnabled(false);
      add(lblIsPendingDelete, new GridBagConstraints(6, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDnsSec ----
      lblDnsSec.setText("DNSSEC");
      add(lblDnsSec, new GridBagConstraints(0, 6, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //======== panelDnsSec ========
      {
          panelDnsSec.setLayout(new GridBagLayout());
          ((GridBagLayout)panelDnsSec.getLayout()).columnWidths = new int[] {0, 0, 0};
          ((GridBagLayout)panelDnsSec.getLayout()).rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
          ((GridBagLayout)panelDnsSec.getLayout()).columnWeights = new double[] {0.0, 0.0, 1.0E-4};
          ((GridBagLayout)panelDnsSec.getLayout()).rowWeights = new double[] {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0E-4};

          //---- lblKeyTag ----
          lblKeyTag.setText("keyTag");
          panelDnsSec.add(lblKeyTag, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.NONE,
              new Insets(5, 5, 10, 10), 0, 0));

          //---- txtAlg ----
          txtAlg.setMinimumSize(new Dimension(150, 20));
          txtAlg.setPreferredSize(new Dimension(150, 20));
          panelDnsSec.add(txtAlg, new GridBagConstraints(1, 0, 1, 1, 0.0, 0.0,
              GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
              new Insets(5, 5, 10, 5), 0, 0));

          //---- lblAlg ----
          lblAlg.setText("alg");
          panelDnsSec.add(lblAlg, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.NONE,
              new Insets(5, 5, 10, 10), 0, 0));

          //---- cmbAlg ----
          cmbAlg.setModel(new DefaultComboBoxModel<>(new String[] {
              "3 - DSA/SHA-1",
              "5 - RSA/SHA-1",
              "6 - DSA-NSEC3-SHA1",
              "7 - RSASHA1-NSEC3-SHA1",
              "8 - RSA/SHA-256",
              "10 - RSA/SHA-512",
              "12 - ECC-GOST",
              "13 - ECDSAP256SHA256",
              "14 - ECDSAP384SHA384"
          }));
          cmbAlg.setPreferredSize(new Dimension(150, 20));
          cmbAlg.addActionListener(e -> dbengineActionPerformed(e));
          panelDnsSec.add(cmbAlg, new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.NONE,
              new Insets(5, 5, 10, 5), 0, 0));

          //---- lblDigestType ----
          lblDigestType.setText("digestType");
          panelDnsSec.add(lblDigestType, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.NONE,
              new Insets(5, 5, 10, 10), 0, 0));

          //---- cmbDigestType ----
          cmbDigestType.setModel(new DefaultComboBoxModel<>(new String[] {
              "1 - SHA-1",
              "2 - SHA-256",
              "3 - GOST R 34.11-94",
              "4 - SHA-384"
          }));
          cmbDigestType.setPreferredSize(new Dimension(150, 20));
          cmbDigestType.addActionListener(e -> dbengineActionPerformed(e));
          panelDnsSec.add(cmbDigestType, new GridBagConstraints(1, 2, 1, 1, 0.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.NONE,
              new Insets(5, 5, 10, 5), 0, 0));

          //---- lblDigest ----
          lblDigest.setText("digest");
          panelDnsSec.add(lblDigest, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.NONE,
              new Insets(5, 5, 10, 10), 0, 0));

          //======== scrollPane1 ========
          {

              //---- txtDigest ----
              txtDigest.setLineWrap(true);
              txtDigest.setWrapStyleWord(true);
              txtDigest.setColumns(32);
              txtDigest.setRows(2);
              scrollPane1.setViewportView(txtDigest);
              scrollPane1.setMinimumSize(new Dimension(200, 50));
              scrollPane1.setPreferredSize(new Dimension(200, 50));
          }
          panelDnsSec.add(scrollPane1, new GridBagConstraints(1, 3, 1, 1, 1.0, 0.0,
              GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL,
              new Insets(0, 0, 5, 0), 0, 0));

          //---- chkDNSSEC ----
          chkDNSSEC.setText("Abilita DNSSEC");
          chkDNSSEC.addActionListener(e -> toggleDnsSecFields());

          chkDNSSEC.setEnabled(isEditable && dnsSecEnabled);
          chkDNSSEC.setVerticalTextPosition(SwingConstants.BOTTOM);
          panelDnsSec.add(chkDNSSEC, new GridBagConstraints(1, 4, 1, 1, 0.0, 0.0,
              GridBagConstraints.CENTER, GridBagConstraints.BOTH,
              new Insets(0, 0, 5, 0), 0, 0));
      }
      add(panelDnsSec, new GridBagConstraints(1, 6, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.BOTH,
          new Insets(0, 0, 0, 0), 0, 0));

      toggleDnsSecFields();
  }// </editor-fold>//GEN-END:initComponents

  private void addNameServerActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_addNameServerActionPerformed
    if (txtNameServerToAdd.getText().length() > 0)
    {
      try
      {
        if (txtNameServerToAdd.getText().contains("@"))
        {
          String[] dNameServer = txtNameServerToAdd.getText().split("@");
          for (int i = 1; i < dNameServer.length; i++)
          {
            ipAddressValidator.validateIpAddress(dNameServer[i]);
          }
        }
        nameServerModel.add(txtNameServer.getModel().getSize(), txtNameServerToAdd.getText());
        txtNameServerToAdd.setText("");
      }
      catch (invalidIpAddressException e)
      {
        JOptionPane.showMessageDialog(this, "The IP Address entered is not a valid IPv4 or IPv6 address.", "Invalid IP Address", JOptionPane.INFORMATION_MESSAGE);
      }
    }
  }//GEN-LAST:event_addNameServerActionPerformed

  private void remNameServerActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_remNameServerActionPerformed
    if (txtNameServer.getSelectedIndex() >= 0)
    {
      txtNameServerToAdd.setText(nameServerModel.get(txtNameServer.getSelectedIndex()));
      nameServerModel.remove(txtNameServer.getSelectedIndex());
    }
  }//GEN-LAST:event_remNameServerActionPerformed

  private void addTechActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_addTechActionPerformed
    JFrame frame = new JFrame();
    ContactSelection cs = new ContactSelection(frame, this, getDomainName(), 3);
    cs.setSize(400, 600);
    cs.setVisible(true);
    String newTech = cs.getValidatedText();

    if (newTech != null)
    {
      if (newTech.length() > 0)
      {
        techModel.add(txtTech.getModel().getSize(), newTech);
      }
    }
  }//GEN-LAST:event_addTechActionPerformed

  private void remTechActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_remTechActionPerformed
    if (txtTech.getSelectedIndex() >= 0)
    {
      techModel.remove(txtTech.getSelectedIndex());
    }
  }//GEN-LAST:event_remTechActionPerformed

  private void addAdminActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_addAdminActionPerformed
    JFrame frame = new JFrame();
    ContactSelection cs = new ContactSelection(frame, this, getDomainName(), 2);
    cs.setSize(400, 600);
    cs.setVisible(true);
    String newAdmin = cs.getValidatedText();

    if (newAdmin != null)
    {
      if (newAdmin.length() > 0)
      {
        adminModel.add(txtAdmin.getModel().getSize(), newAdmin);
      }
    }
  }//GEN-LAST:event_addAdminActionPerformed

  private void remAdminActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_remAdminActionPerformed
    if (txtAdmin.getSelectedIndex() >= 0)
    {
      adminModel.remove(txtAdmin.getSelectedIndex());
    }
  }//GEN-LAST:event_remAdminActionPerformed

  private void setRegistrantActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_setRegistrantActionPerformed
    if (getOpType() != 1 && txtAuthInfo.getText().equals(domain.getAuthInfo()))
    {
      JOptionPane.showMessageDialog(this, "The AuthInfo code needs to be changed first.", "Change AuthInfo before changing Registrant", JOptionPane.INFORMATION_MESSAGE);
    }
    else
    {
      JFrame frame = new JFrame();
      ContactSelection cs = new ContactSelection(frame, this, getDomainName(), 1);
      cs.setSize(450, 600);
      cs.setVisible(true);
      String newRegistrant = cs.getValidatedText();

      if (newRegistrant != null)
      {
        if (newRegistrant.length() > 0)
        {
          txtRegistrant.setText(newRegistrant);
        }
      }
    }
  }//GEN-LAST:event_setRegistrantActionPerformed

  private void btnRndAuthinfoActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_btnRndAuthinfoActionPerformed
    txtAuthInfo.setText(java.util.UUID.randomUUID().toString().substring(0, 32));
  }//GEN-LAST:event_btnRndAuthinfoActionPerformed

  void setDomainName(String domainName)
  {
    domain.setDomainName(domainName);
    txtDomainName.setText(domainName);
  }

  void updatePunyDomainName()
  {
    txtPunyDomainName.setText(IDN.toASCII(txtDomainName.getText()));
  }

  String getDomainName()
  {
    String domainName = txtDomainName.getText();
    domain.setDomainName(domainName);
    return domainName;
  }

    void setValidationCode(String validationCode)
    {
        domain.setValidationCode(validationCode);
        txtValidationCode.setText(validationCode);
    }

    String getValidationCode()
    {
        String validationCode = txtValidationCode.getText();
        domain.setValidationCode(validationCode);
        return validationCode;
    }
    public boolean isDnsSecEnabled() {
        boolean enabled = chkDNSSEC.isSelected();
        domain.setDNSSec(enabled);
        return enabled;
    }

    public String getDnsSecKeyTag() {
        String keyTag = chkDNSSEC.isSelected() ? txtAlg.getText().trim() : "";
        domain.setKeyTag(keyTag);
        return keyTag;
    }

    public int getDnsSecAlgorithm() {
        int alg = -1;
        if (chkDNSSEC.isSelected()) {
            String selected = (String) cmbAlg.getSelectedItem();
            if (selected != null) {
                alg = Integer.parseInt(selected.split(" - ")[0]);
            }
        }
        domain.setAlg(alg);
        return alg;
    }

    public int getDnsSecDigestType() {
        int digestType = -1;
        if (chkDNSSEC.isSelected()) {
            String selected = (String) cmbDigestType.getSelectedItem();
            if (selected != null) {
                digestType = Integer.parseInt(selected.split(" - ")[0]);
            }
        }
        domain.setDigestType(digestType);
        return digestType;
    }

    public String getDnsSecDigest() {
        String digest = chkDNSSEC.isSelected() ? txtDigest.getText().trim() : "";
        domain.setDigest(digest);
        return digest;
    }
    void setDnsSec(boolean isDnsSec) {
        domain.setDNSSec(isDnsSec);
        if(dnsSecEnabled)
            chkDNSSEC.setSelected(isDnsSec);
        else
            chkDNSSEC.setSelected(false);
        toggleDnsSecFields();
    }

    void setDnsSecKeyTag(String keyTag) {
        domain.setKeyTag(keyTag);
        txtAlg.setText(keyTag);
    }

    void setDnsSecAlg(int alg) {
        domain.setAlg(alg);
        // Set the combobox to match the algorithm number
        for (int i = 0; i < cmbAlg.getItemCount(); i++) {
            String item = cmbAlg.getItemAt(i);
            if (item.startsWith(alg + " ")) {
                cmbAlg.setSelectedIndex(i);
                break;
            }
        }
    }

    void setDnsSecDigestType(int digestType) {
        domain.setDigestType(digestType);
        // Set the combobox to match the digest type number
        for (int i = 0; i < cmbDigestType.getItemCount(); i++) {
            String item = cmbDigestType.getItemAt(i);
            if (item.startsWith(digestType + " ")) {
                cmbDigestType.setSelectedIndex(i);
                break;
            }
        }
    }

    void setDnsSecDigest(String digest) {
        domain.setDigest(digest);
        txtDigest.setText(digest);
    }
  void setAuthInfo(String authInfo)
  {
    domain.setAuthInfo(authInfo);
    txtAuthInfo.setText(authInfo);
  }

  String getAuthInfo()
  {
    String authInfo = txtAuthInfo.getText();
    domain.setAuthInfo(authInfo);
    return authInfo;
  }

  void setOldAuthInfo(String oldAuthInfo)
  {
    domain.setOldAuthInfo(oldAuthInfo);
  }

  String getOldAuthInfo()
  {
    String oldAuthInfo = domain.getOldAuthInfo();
    domain.setOldAuthInfo(oldAuthInfo);
    return oldAuthInfo;
  }

  void setRegistrant(String registrant)
  {
    domain.setRegistrant(registrant);
    txtRegistrant.setText(registrant);
  }

  String getRegistrant()
  {
    String registrant = txtRegistrant.getText();
    if (!registrant.equals(domain.getRegistrant()))
    {
      domain.setRegistrant(registrant);
      domain.setIsRegistrantChanged(true);
    }
    return registrant;
  }

  void setOldAdmin(String[] oldAdmin)
  {
    domain.setOldAdmin(oldAdmin);
  }

  String[] getOldAdmin()
  {
    String[] oldAdmin = domain.getOldAdmin();
    domain.setOldAdmin(oldAdmin);
    return oldAdmin;
  }

  void setAdmin(String[] admin)
  {
    domain.setAdmin(admin);

    adminModel.clear();
    if (admin != null)
    {
      for (int i = 0; i < admin.length; i++)
      {
        adminModel.add(txtAdmin.getModel().getSize(), admin[i]);
      }
    }
  }

  String[] getAdmin()
  {
    String[] admin = new String[txtAdmin.getModel().getSize()];
    for (int i = 0; i < admin.length; i++)
    {
      admin[i] = adminModel.get(i);
    }

    domain.setAdmin(admin);
    return admin;
  }

  void setOldTech(String[] oldTech)
  {
    domain.setOldTech(oldTech);
  }

  String[] getOldTech()
  {
    String[] oldTech = domain.getOldTech();
    domain.setOldTech(oldTech);
    return oldTech;
  }

  void setTech(String[] tech)
  {
    domain.setTech(tech);

    techModel.clear();
    if (tech != null)
    {
      for (int i = 0; i < tech.length; i++)
      {
        techModel.add(txtTech.getModel().getSize(), tech[i]);
      }
    }
  }

  String[] getTech()
  {
    String[] tech = new String[txtTech.getModel().getSize()];
    for (int i = 0; i < tech.length; i++)
    {
      tech[i] = techModel.get(i);
    }

    domain.setTech(tech);
    return tech;
  }

  void setNameServer(String[] nameServer)
  {
    domain.setNameServer(nameServer);

    nameServerModel.clear();
    if (nameServer != null)
    {
      for (int i = 0; i < nameServer.length; i++)
      {
        nameServerModel.add(txtNameServer.getModel().getSize(), nameServer[i]);
      }
    }
  }

  String[] getNameServer()
  {
    String[] nameServer = new String[txtNameServer.getModel().getSize()];
    for (int i = 0; i < nameServer.length; i++)
    {
      nameServer[i] = nameServerModel.get(i);
    }

    domain.setNameServer(nameServer);
    return nameServer;
  }

  void setOldNameServer(String[] oldNameServer)
  {
    domain.setOldNameServer(oldNameServer);
  }

  String[] getOldNameServer()
  {
    String[] nameServer = domain.getOldNameServer();
    domain.setOldNameServer(nameServer);
    return nameServer;
  }

  void setOpType(int opType)
  {
    domain.setOpType(opType);
  }

  int getOpType()
  {
    return domain.getOpType();
  }


  void setExpire(Date expire)
  {
    domain.setExpire(expire);
  }

  Date getExpire()
  {
    return domain.getExpire();
  }

/*    void setOldStatus(int[] oldStatus) {
        domain.setOldStatus(oldStatus);
    }*/

  void setOldStatus(Vector oldStatus)
  {
    domain.setOldStatus(oldStatus);
  }

/*    int[] getOldStatus() {
        int[] oldStatus = domain.getOldStatus();
        return oldStatus;
    }*/

  Vector getOldStatusV()
  {
    Vector oldStatus = domain.getOldStatusV();
    domain.setOldStatus(oldStatus);
    return oldStatus;
  }

/*    void setNewStatus(int[] newStatus) {
        domain.setNewStatus(newStatus);
        if (newStatus != null) {
            txtStatus.setSelectedIndices(newStatus);
        } else {
            txtStatus.clearSelection();
        }
        lblIsPendingDelete.setEnabled(false);
        if (newStatus != null)
            for (int i = 0; i<newStatus.length; i++) {
                if (newStatus[i] == 99) {
                    lblIsPendingDelete.setEnabled(true);
                }
            }
    }*/

  void setNewStatus(Vector newStatus)
  {
    domain.setNewStatus(newStatus);
    txtStatus.clearSelection();
    if (newStatus != null)
    {
      for (int i = 0; i < newStatus.size(); i++)
        txtStatus.addSelectionInterval((Integer) newStatus.get(i), (Integer) newStatus.get(i));
    }
    lblIsPendingDelete.setEnabled(false);
    if (newStatus != null)
      if (newStatus.contains(99))
        lblIsPendingDelete.setEnabled(true);
  }
    
/*    int[] getNewStatus() {
        int[] newStatus;
        if (lblIsPendingDelete.isEnabled())
            newStatus = new int[txtStatus.getSelectedIndices().length+1];
        else
            newStatus = new int[txtStatus.getSelectedIndices().length];

        if (lblIsPendingDelete.isEnabled())
            newStatus[newStatus.length-1] = 99;

        System.arraycopy(txtStatus.getSelectedIndices(), 0, newStatus, 0, txtStatus.getSelectedIndices().length);
        domain.setNewStatus(newStatus);
        return newStatus;
    }*/

  Vector<Integer> getNewStatusV()
  {
    Vector<Integer> newStatus = new Vector<Integer>();
    for (int selectedStatus : txtStatus.getSelectedIndices())
    {
      newStatus.add(selectedStatus);
    }

    if (lblIsPendingDelete.isEnabled())
      newStatus.add(99);

    domain.setNewStatus(newStatus);

    return newStatus;
  }

  public void setAddress(Domain domain)
  {
    if (domain != null)
    {
      setDomainName(domain.getDomainName());
      setRegistrant(domain.getRegistrant());
      setAdmin(domain.getAdmin());
      setOldAdmin(domain.getOldAdmin());
      setTech(domain.getTech());
      setOldTech(domain.getTech());
      setNameServer(domain.getNameServer());
      setOldNameServer(domain.getOldNameServer());

      setOldAuthInfo(domain.getOldAuthInfo());
      setAuthInfo(domain.getAuthInfo());
      setValidationCode(domain.getValidationCode());

      setOldStatus(domain.getOldStatusV());
      setNewStatus(domain.getNewStatusV());

      setExpire(domain.getExpire());

      // DNSSEC
      setDnsSec(domain.isDNSSec());
      setDnsSecKeyTag(domain.getKeyTag());
      setDnsSecAlg(domain.getAlg());
      setDnsSecDigestType(domain.getDigestType());
      setDnsSecDigest(domain.getDigest());
    }
  }

  public Domain getAddress()
  {
    getDomainName();
    getRegistrant();
    getAdmin();
    getOldAdmin();
    getTech();
    getOldTech();
    getNameServer();
    getOldNameServer();
    getAuthInfo();
    getOldAuthInfo();
    getNewStatusV();
    getOldStatusV();
    getValidationCode();

    //NSSEC getters
    isDnsSecEnabled();
    getDnsSecKeyTag();
    getDnsSecAlgorithm();
    getDnsSecDigestType();
    getDnsSecDigest();
    return domain;
  }


  public void clear()
  {
    txtDomainName.setText(null);
    txtPunyDomainName.setText(null);
    txtAuthInfo.setText(null);
    txtRegistrant.setText(null);
    setRegistrant.setText(null);
    txtAdmin.removeAll();
    adminModel.removeAllElements();
    txtTech.removeAll();
    techModel.removeAllElements();
    txtNameServer.removeAll();
    nameServerModel.removeAllElements();
    lblIsPendingDelete.setEnabled(false);
    domain = new Domain();
  }

  public void setEditable(boolean bEditable)
  {
    txtDomainName.setEditable(bEditable && (getOpType() == 1));
    txtPunyDomainName.setEditable(false);

    txtAuthInfo.setEditable(bEditable);
    txtValidationCode.setEditable(bEditable);

    if (getOpType() == 1)
    {
      setRegistrant.setText("Selezione Registrant");

      if (EPPparams.getParameter("EppClient.defaultTech").length() > 0)
      {
        String[] defaultTech = EPPparams.getParameter("EppClient.defaultTech").split(";");
        for (String defaultTechToAdd : defaultTech)
        {
          techModel.add(txtTech.getModel().getSize(), defaultTechToAdd.trim());
        }
      }

      if (EPPparams.getParameter("EppClient.defaultNS").length() > 0)
      {
        String[] defaultNS = EPPparams.getParameter("EppClient.defaultNS").split(";");
        for (String defaultNStoAdd : defaultNS)
        {
          nameServerModel.add(txtNameServer.getModel().getSize(), defaultNStoAdd.trim());
        }
      }
    }
    else
    {
      setRegistrant.setText("Cambio Registrant");
    }

    setRegistrant.setVisible(bEditable);
    btnRndAuthinfo.setVisible(bEditable);


    txtStatus.setEnabled(bEditable);
    txtAdmin.setEnabled(bEditable);
    addAdmin.setVisible(bEditable);
    remAdmin.setVisible(bEditable);

    txtTech.setEnabled(bEditable);
    addTech.setVisible(bEditable);
    remTech.setVisible(bEditable);

    lblDnsExpl.setVisible(bEditable);
    txtNameServerToAdd.setVisible(bEditable);
    txtNameServer.setEnabled(bEditable);
    addNameServer.setVisible(bEditable);
    remNameServer.setVisible(bEditable);
    chkDNSSEC.setEnabled(bEditable && dnsSecEnabled);
    isEditable = bEditable;
    toggleDnsSecFields();

  }
    private void toggleDnsSecFields() {
        boolean enabled = chkDNSSEC.isSelected() && isEditable;

        txtAlg.setEnabled(enabled);
        cmbAlg.setEnabled(enabled);
        cmbDigestType.setEnabled(enabled);
        txtDigest.setEnabled(enabled);

        if (!enabled || !dnsSecEnabled) {
            txtAlg.setText("");
            txtDigest.setText("");
            cmbAlg.setSelectedIndex(0);
            cmbDigestType.setSelectedIndex(0);
        }
    }

  public boolean isEditable()
  {
    return isEditable;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables

  private JLabel lblDomainClientStatus;
  private JLabel lblRegistrant;
  private JTextField txtRegistrant;
  private JLabel lblAdmin;
  private JLabel lblTech;
  private JLabel lblAuthInfo;
  private JTextField txtAuthInfo;
  private JLabel lblNameServer;
  private JTextField txtNameServerToAdd;
  private JLabel lblDomainName;
  private JTextField txtDomainName;
  private JScrollPane jScrollPane1;
  private JList<String> txtStatus;
  private JScrollPane jScrollPane2;
  private JList txtNameServer;
  private JButton addNameServer;
  private JButton remNameServer;
  private JScrollPane jScrollPane3;
  private JList txtTech;
  private JButton addTech;
  private JButton remTech;
  private JButton addAdmin;
  private JButton remAdmin;
  private JScrollPane jScrollPane4;
  private JList txtAdmin;
  private JButton setRegistrant;
  private JLabel lblDnsExpl;
  private JTextField txtPunyDomainName;
  private JLabel lblPunyDomainName;
  private JButton btnRndAuthinfo;
  private JLabel lblValidationCode;
  private JTextField txtValidationCode;
  private JLabel lblIsPendingDelete;
  private JLabel lblDnsSec;
  private JPanel panelDnsSec;
  private JLabel lblKeyTag;
  private JTextField txtAlg;
  private JLabel lblAlg;
  private JComboBox<String> cmbAlg;
  private JLabel lblDigestType;
  private JComboBox<String> cmbDigestType;
  private JLabel lblDigest;
  private JScrollPane scrollPane1;
  private JTextArea txtDigest;
  private JCheckBox chkDNSSEC;
  // End of variables declaration//GEN-END:variables

  DefaultListModel<String> adminModel = new DefaultListModel<String>();
  DefaultListModel<String> techModel = new DefaultListModel<String>();
  DefaultListModel<String> nameServerModel = new DefaultListModel<>();

  boolean isEditable;
  Domain domain;
}
