/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.domains;

import javax.swing.*;
import javax.swing.event.EventListenerList;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DomainActionPanel extends JPanel
{

  /**
   * Creates new form AddressActionPanel
   */
  public DomainActionPanel()
  {
    initComponents();
    listeners = new EventListenerList();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

  private void initComponents() {
      btnNewAddress = new JButton();
      btnTransferAddress = new JButton();
      btnCheckDomain = new JButton();
      btnEditAddress = new JButton();
      btnDeleteAddress = new JButton();
      btnCancelAddress = new JButton();
      btnSaveAddress = new JButton();
      btnSyncInfo = new JButton();
      btnRestoreDomain = new JButton();
      btnInfo = new JButton();

      //======== this ========
      setLayout(new GridLayout());

      //---- btnNewAddress ----
      btnNewAddress.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnNewAddress.setText("New");
      btnNewAddress.setActionCommand("NEW_ADDRESS");
      btnNewAddress.setMargin(new Insets(2, 2, 2, 2));
      btnNewAddress.addActionListener(e -> newAddressActionPerformed(e));
      add(btnNewAddress);

      //---- btnTransferAddress ----
      btnTransferAddress.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnTransferAddress.setText("Transfer\nTrade");
      btnTransferAddress.setActionCommand("TRANSFER_ADDRESS");
      btnTransferAddress.setMargin(new Insets(2, 2, 2, 2));
      btnTransferAddress.addActionListener(e -> transferAddressActionPerformed(e));
      add(btnTransferAddress);

      //---- btnCheckDomain ----
      btnCheckDomain.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnCheckDomain.setText("Check");
      btnCheckDomain.setActionCommand("CHECK_DOMAIN");
      btnCheckDomain.setMargin(new Insets(2, 2, 2, 2));
      btnCheckDomain.addActionListener(e -> btnCheckDomainActionPerformed(e));
      add(btnCheckDomain);

      //---- btnEditAddress ----
      btnEditAddress.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnEditAddress.setText("Edit");
      btnEditAddress.setActionCommand("EDIT_ADDRESS");
      btnEditAddress.setMargin(new Insets(2, 2, 2, 2));
      btnEditAddress.addActionListener(e -> editAddressActionPerformed(e));
      add(btnEditAddress);

      //---- btnDeleteAddress ----
      btnDeleteAddress.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnDeleteAddress.setText("Delete");
      btnDeleteAddress.setActionCommand("DELETE_ADDRESS");
      btnDeleteAddress.setMargin(new Insets(2, 2, 2, 2));
      btnDeleteAddress.addActionListener(e -> deleteAddressActionPerformed(e));
      add(btnDeleteAddress);

      //---- btnCancelAddress ----
      btnCancelAddress.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnCancelAddress.setText("Cancel");
      btnCancelAddress.setActionCommand("CANCEL_ADDRESS");
      btnCancelAddress.setMargin(new Insets(2, 2, 2, 2));
      btnCancelAddress.addActionListener(e -> cancelAddressActionPerformed(e));
      add(btnCancelAddress);

      //---- btnSaveAddress ----
      btnSaveAddress.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnSaveAddress.setText("Save");
      btnSaveAddress.setActionCommand("SAVE_ADDRESS");
      btnSaveAddress.setMargin(new Insets(2, 2, 2, 2));
      btnSaveAddress.addActionListener(e -> saveAddressActionPerformed(e));
      add(btnSaveAddress);

      //---- btnSyncInfo ----
      btnSyncInfo.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnSyncInfo.setText("Sync");
      btnSyncInfo.setActionCommand("SYNC_DOMAIN");
      btnSyncInfo.setMargin(new Insets(2, 2, 2, 2));
      btnSyncInfo.addActionListener(e -> btnSyncDomainActionPerformed(e));
      add(btnSyncInfo);

      //---- btnRestoreDomain ----
      btnRestoreDomain.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnRestoreDomain.setText("Restore");
      btnRestoreDomain.setActionCommand("RESTORE_DOMAIN");
      btnRestoreDomain.setMargin(new Insets(2, 2, 2, 2));
      btnRestoreDomain.addActionListener(e -> btnRestoreDomainActionPerformed(e));
      add(btnRestoreDomain);

      //---- btnInfo ----
      btnInfo.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnInfo.setText("Info");
      btnInfo.setActionCommand("INFO_DOMAIN");
      btnInfo.setMargin(new Insets(2, 2, 2, 2));
      btnInfo.addActionListener(e -> btnInfoActionPerformed(e));
      add(btnInfo);
  }// </editor-fold>//GEN-END:initComponents

  private void cancelAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_cancelAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_cancelAddressActionPerformed

  private void saveAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_saveAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_saveAddressActionPerformed

  private void editAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_editAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_editAddressActionPerformed

  private void deleteAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_deleteAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_deleteAddressActionPerformed

  private void newAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_newAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_newAddressActionPerformed

  private void transferAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_transferAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_transferAddressActionPerformed

  private void btnCheckDomainActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnCheckDomainActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnCheckDomainActionPerformed

  private void btnSyncDomainActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnSyncDomainActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnSyncDomainActionPerformed

  private void btnRestoreDomainActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnRestoreDomainActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnRestoreDomainActionPerformed

  private void btnInfoActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnInfoActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnInfoActionPerformed

  private void fireActionEvent(ActionEvent evt)
  {
    ActionListener[] listenerList = listeners.getListeners(ActionListener.class);

    for (int i = listenerList.length - 1; i >= 0; --i)
    {
      listenerList[i].actionPerformed(evt);
    }

  }

  public void addActionListener(ActionListener listener)
  {
    listeners.add(ActionListener.class, listener);
  }

  public void removeActionListener(ActionListener listener)
  {
    if (listeners != null)
    {
      listeners.remove(ActionListener.class, listener);
    }
  }

  EventListenerList listeners;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton btnNewAddress;
  private JButton btnTransferAddress;
  private JButton btnCheckDomain;
  private JButton btnEditAddress;
  private JButton btnDeleteAddress;
  private JButton btnCancelAddress;
  private JButton btnSaveAddress;
  private JButton btnSyncInfo;
  private JButton btnRestoreDomain;
  private JButton btnInfo;
  // End of variables declaration//GEN-END:variables

}
