/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.domains;

import EPPClient.db.domainsDao;

import EPPClient.Debug;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.util.List;

public class DomainFrame
        extends JFrame
        implements ActionListener, ListSelectionListener
{

  /**
   * Creates new form AddressFrame
   */
  public DomainFrame()
  {
    initComponents();
    loadFrameIcon();
    windowAdapter = new WindowCloser();
    this.addWindowListener(windowAdapter);
    db = new domainsDao();
    db.connect();
    addressActionPanel.addActionListener(this);
    domainPanel.setEditable(false);
    List<ListEntry> entries = db.getListEntries();
    domainListPanel.addListEntries(entries);
    domainListPanel.addListSelectionListener(this);
  }


  /**
   * Load our own "address book" icon into our frame window.
   */
  private void loadFrameIcon()
  {
    URL imgUrl = null;
    ImageIcon imgIcon = null;

    imgUrl = DomainFrame.class.getResource("../resources/addressbook32.gif");
    imgIcon = new ImageIcon(imgUrl);
    Image img = imgIcon.getImage();
    this.setIconImage(img);

  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    addressActionPanel = new DomainActionPanel();
    domainPanel = new DomainPanel();
    domainListPanel = new DomainListPanel();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setTitle("Address Book Demo");
    getContentPane().add(addressActionPanel, BorderLayout.SOUTH);

    getContentPane().add(domainPanel, BorderLayout.CENTER);

    getContentPane().add(domainListPanel, BorderLayout.WEST);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  private void cancelAddress()
  {
    domainPanel.clear();
    domainPanel.setEditable(false);
    ListEntry entry = domainListPanel.getSelectedListEntry();
    if (entry != null)
    {
      String contactId = entry.getDomainName();
      Domain address = db.getDomain(contactId);
      domainPanel.setAddress(address);
    }


  }

  private void newAddress()
  {
    domainPanel.clear();
    domainPanel.setEditable(true);

  }

  private void deleteAddress()
  {
    String domainName = domainPanel.getDomainName();
    if (domainName.equals(""))
    {
      db.deleteRecord(domainName);
      int selectedIndex = domainListPanel.deleteSelectedEntry();
      if (selectedIndex >= 0)
      {
        selectedIndex = domainListPanel.setSelectedIndex(selectedIndex);
        ListEntry entry = domainListPanel.getSelectedListEntry();
        if (entry != null)
        {
          domainName = entry.getDomainName();
          Domain address = db.getDomain(domainName);
          domainPanel.setAddress(address);
        }
        else
        {
          domainPanel.clear();
        }
      }
    }
    else
    {
      domainPanel.clear();
    }
    domainPanel.setEditable(false);


  }

  private void editAddress()
  {
    int selected = domainListPanel.getSelectedIndex();
    if (selected >= 0)
    {
      domainPanel.setEditable(true);
    }

  }

  private void saveAddress()
  {
    if (domainPanel.isEditable())
    {
      Domain domain = domainPanel.getAddress();
      String domainName = domain.getDomainName();

      if (domainName.equals(""))
      {
        domainName = db.saveRecord(domain);
        domain.setDomainName(domainName);

        ListEntry entry = new ListEntry(domainName);
        domainListPanel.addListEntry(entry);

      }
      else
      {
        db.editRecord(domain);
        ListEntry entry = domainListPanel.getSelectedListEntry();
        entry.setDomainName(domainName);
        domainListPanel.repaint();
      }
      domainPanel.setEditable(false);
    }
  }


  public void actionPerformed(ActionEvent e)
  {
    String actionCommand = e.getActionCommand();
    Debug.log("DomainFrame", "ActionEvent: " + actionCommand);
    if (actionCommand.equalsIgnoreCase("CANCEL_ADDRESS"))
    {
      cancelAddress();
    }
    else if (actionCommand.equalsIgnoreCase("NEW_ADDRESS"))
    {
      newAddress();
    }
    else if (actionCommand.equalsIgnoreCase("DELETE_ADDRESS"))
    {
      deleteAddress();
    }
    else if (actionCommand.equalsIgnoreCase("EDIT_ADDRESS"))
    {
      editAddress();
    }
    else if (actionCommand.equalsIgnoreCase("SAVE_ADDRESS"))
    {
      saveAddress();
    }
  }


  public void valueChanged(ListSelectionEvent e)
  {
    if (e.getValueIsAdjusting())
    {
      return;
    }
    JList entryList = (JList) e.getSource();
    selectedEntry = entryList.getSelectedIndex();
    ListEntry entry = (ListEntry) entryList.getSelectedValue();
    if (entry != null)
    {
      String contactId = entry.getDomainName();
      Domain address = db.getDomain(contactId);
      domainPanel.setAddress(address);
    }
    else
    {
      domainPanel.clear();
    }
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private DomainActionPanel addressActionPanel;
  private DomainListPanel domainListPanel;
  private DomainPanel domainPanel;
  // End of variables declaration//GEN-END:variables

  private int selectedEntry = -1;
  private domainsDao db;
  private WindowAdapter windowAdapter;

  class WindowCloser extends WindowAdapter
  {
    public void windowClosing(WindowEvent e)
    {
      db.disconnect();
    }

  }
}
