/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package com.codetotime.eppclient.domains;

import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;
import javax.swing.event.ListSelectionListener;

/** Scrollable list panel showing domain entries loaded from the local database. */
public class DomainListPanel extends JPanel {

  /** Creates new form AddressListPanel. */
  public DomainListPanel() {
    renderer = new ListEntryRenderer();
    model = new DefaultListModel();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    scrollPane = new JScrollPane();
    addressList = new JList();

    // ======== this ========
    setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

    // ======== scrollPane ========
    {
      scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

      // ---- addressList ----
      addressList.setModel(model);
      addressList.setCellRenderer(renderer);
      addressList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      scrollPane.setViewportView(addressList);
    }
    add(scrollPane);
  } // </editor-fold>//GEN-END:initComponents

  /**
   * Appends a single entry to the list.
   *
   * @param entry the domain list entry to add
   */
  public void addListEntry(ListEntry entry) {
    model.addElement(entry);
  }

  /**
   * Appends all entries from the given list.
   *
   * @param list the domain list entries to add
   */
  public void addListEntries(List<ListEntry> list) {
    for (ListEntry entry : list) {
      addListEntry(entry);
    }
  }

  public int getSelectedIndex() {
    return addressList.getSelectedIndex();
  }

  /**
   * Selects the entry at the given index, clamping to the last entry if out of range.
   *
   * @param index the desired selection index
   * @return the actual index that was selected
   */
  public int setSelectedIndex(int index) {
    assert (index >= -1);
    DefaultListModel model = (DefaultListModel) addressList.getModel();
    int size = model.getSize();
    if (index < size) {
      addressList.setSelectedIndex(index);
    } else {
      addressList.setSelectedIndex(size - 1);
      index = size - 1;
    }
    return index;
  }

  /**
   * Returns the currently selected list entry, or {@code null} if nothing is selected.
   *
   * @return the selected {@link ListEntry}
   */
  public ListEntry getSelectedListEntry() {
    ListEntry entry = (ListEntry) addressList.getSelectedValue();
    return entry;
  }

  /**
   * Removes the currently selected entry from the list.
   *
   * @return the index of the removed entry, or {@code -1} if nothing was selected
   */
  public int deleteSelectedEntry() {
    int selectedIndex = addressList.getSelectedIndex();
    if (selectedIndex >= 0) {
      DefaultListModel model = (DefaultListModel) addressList.getModel();
      model.remove(selectedIndex);
    }
    return selectedIndex;
  }

  /** Removes all entries from the list. */
  public void deleteAllEntries() {
    DefaultListModel model = (DefaultListModel) addressList.getModel();
    model.removeAllElements();
  }

  /**
   * Registers a selection listener on the underlying list.
   *
   * @param listener the listener to add
   */
  public void addListSelectionListener(ListSelectionListener listener) {
    addressList.addListSelectionListener(listener);
  }

  /**
   * Removes a previously registered selection listener.
   *
   * @param listener the listener to remove
   */
  public void removeListSelectionListener(ListSelectionListener listener) {
    addressList.removeListSelectionListener(listener);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JScrollPane scrollPane;
  private JList addressList;
  // End of variables declaration//GEN-END:variables

  private ListEntryRenderer renderer;
  private DefaultListModel model;
}
