/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package com.codetotime.eppclient.messages;

import com.codetotime.eppclient.config.EppParams;
import com.codetotime.eppclient.db.messagesDao;
import com.codetotime.eppclient.importer.ImportDomain;
import com.codetotime.eppclient.main;
import com.codetotime.eppclient.uplink.EppUplink;
import it.nic.epp.client.commands.query.Poll;
import it.nic.epp.client.commands.transform.DomainTransfer;
import it.nic.epp.client.exceptions.EppSchemaException;
import it.nic.epp.client.responses.HttpBaseResponse;
import it.nic.epp.client.responses.ext.PollingResponseExt;
import it.nic.epp.client.responses.resData.PollingResponseResData;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import org.apache.xmlbeans.XmlException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Frame showing the full detail and raw XML of a selected EPP poll message, with an option to
 * acknowledge it.
 */
public class MessageDetail extends JFrame {

  private EppUplink eppUplink;
  private Logger log;
  private Message message;
  private messagesDao db;
  private MessageManagement parentFrame;
  private main mainFrame;

  it.nic.epp.client.responses.CommandResponse response = null;
  PollingResponseResData resData;
  PollingResponseExt extData;

  /** Creates new form MessageDetail. */
  public MessageDetail(main mainFrame, MessageManagement parentFrame, Message messageIn) {
    initComponents();

    this.mainFrame = mainFrame;
    this.eppUplink = mainFrame.eppUplink;
    this.parentFrame = parentFrame;
    this.db = mainFrame.messagesDao;

    log = LoggerFactory.getLogger(MessageDetail.class);
    java.text.SimpleDateFormat dateFormatter =
        new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    this.message = messageIn;

    this.msgIdTxt.setText(message.getMsgId());
    this.datetimeTxt.setText(dateFormatter.format(message.getDateTime()));
    this.messageTxt.setText(message.getTitle());
    this.rawMessageTxt.setText(message.getXml());

    try {
      response = new it.nic.epp.client.responses.CommandResponse(message.getXml());
    } catch (XmlException e) {
      log.error("XmlException in constructor for message ID {}", message.getMsgId(), e);
    }

    resData = (PollingResponseResData) response.getResponseResData();
    extData = (PollingResponseExt) response.getResponseExtension();

    switchAck();

    if (!message.getRead()) {
      message.setRead(true);
      db.editRecord(message);
      parentFrame.updateTableContent();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    lblMsgId = new JLabel();
    msgIdTxt = new JTextField();
    lblMessage = new JLabel();
    lblRawMessage = new JLabel();
    rawMessageScroll = new JScrollPane();
    rawMessageTxt = new JTextArea();
    lblDateTime = new JLabel();
    datetimeTxt = new JTextField();
    btnAck = new JButton();
    actionTab = new JTabbedPane();
    genericPanel = new JPanel();
    genericScroll = new JScrollPane();
    txtGeneric = new JTextArea();
    transferPanel = new JPanel();
    btnTransfer = new JButton();
    transferScroll = new JScrollPane();
    txtTransfer = new JTextArea();
    otherPanel = new JPanel();
    otherScroll = new JScrollPane();
    txtOther = new JTextArea();
    btnOther = new JButton();
    messageScroll = new JScrollPane();
    messageTxt = new JTextArea();
    unusedPanel = new JPanel();

    // ======== this ========
    setTitle("Dettaglio MESSAGGIO");

    // ---- lblMsgId ----
    lblMsgId.setText("Message ID:");

    // ---- msgIdTxt ----
    msgIdTxt.setEditable(false);
    msgIdTxt.setText("jTextField1");

    // ---- lblMessage ----
    lblMessage.setText("Message:");

    // ---- lblRawMessage ----
    lblRawMessage.setText("Raw Message:");

    // ======== rawMessageScroll ========
    {

      // ---- rawMessageTxt ----
      rawMessageTxt.setColumns(20);
      rawMessageTxt.setEditable(false);
      rawMessageTxt.setRows(5);
      rawMessageScroll.setViewportView(rawMessageTxt);
    }

    // ---- lblDateTime ----
    lblDateTime.setText("Date/Time:");

    // ---- datetimeTxt ----
    datetimeTxt.setEditable(false);
    datetimeTxt.setText("jTextField2");

    // ---- btnAck ----
    btnAck.addActionListener(e -> btnAckActionPerformed(e));

    // ======== actionTab ========
    {

      // ======== genericPanel ========
      {
        // ======== genericScroll ========
        {

          // ---- txtGeneric ----
          txtGeneric.setColumns(20);
          txtGeneric.setEditable(false);
          txtGeneric.setLineWrap(true);
          txtGeneric.setRows(7);
          txtGeneric.setText(
              "This is a generic message, therefore no specific action panel has been enabled.");
          txtGeneric.setWrapStyleWord(true);
          genericScroll.setViewportView(txtGeneric);
        }

        GroupLayout genericPanelLayout = new GroupLayout(genericPanel);
        genericPanel.setLayout(genericPanelLayout);
        genericPanelLayout.setHorizontalGroup(
            genericPanelLayout
                .createParallelGroup()
                .addGroup(
                    genericPanelLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(genericScroll, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addContainerGap()));
        genericPanelLayout.setVerticalGroup(
            genericPanelLayout
                .createParallelGroup()
                .addGroup(
                    genericPanelLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            genericScroll,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE)));
      }
      actionTab.addTab("Generic", genericPanel);

      // ======== transferPanel ========
      {

        // ---- btnTransfer ----
        btnTransfer.addMouseListener(
            new MouseAdapter() {
              @Override
              public void mouseReleased(MouseEvent e) {
                btnTransferMouseReleased(e);
              }
            });

        // ======== transferScroll ========
        {

          // ---- txtTransfer ----
          txtTransfer.setColumns(20);
          txtTransfer.setEditable(false);
          txtTransfer.setLineWrap(true);
          txtTransfer.setRows(7);
          txtTransfer.setWrapStyleWord(true);
          transferScroll.setViewportView(txtTransfer);
        }

        GroupLayout transferPanelLayout = new GroupLayout(transferPanel);
        transferPanel.setLayout(transferPanelLayout);
        transferPanelLayout.setHorizontalGroup(
            transferPanelLayout
                .createParallelGroup()
                .addGroup(
                    transferPanelLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            transferPanelLayout
                                .createParallelGroup()
                                .addComponent(
                                    transferScroll, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                .addComponent(btnTransfer, GroupLayout.Alignment.TRAILING))
                        .addContainerGap()));
        transferPanelLayout.setVerticalGroup(
            transferPanelLayout
                .createParallelGroup()
                .addGroup(
                    transferPanelLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            transferScroll,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTransfer)
                        .addContainerGap(41, Short.MAX_VALUE)));
      }
      actionTab.addTab("Transfer", transferPanel);

      // ======== otherPanel ========
      {

        // ======== otherScroll ========
        {

          // ---- txtOther ----
          txtOther.setColumns(20);
          txtOther.setEditable(false);
          txtOther.setLineWrap(true);
          txtOther.setRows(7);
          txtOther.setWrapStyleWord(true);
          otherScroll.setViewportView(txtOther);
        }

        // ---- btnOther ----
        btnOther.addMouseListener(
            new MouseAdapter() {
              @Override
              public void mouseReleased(MouseEvent e) {
                btnOtherMouseReleased(e);
              }
            });

        GroupLayout otherPanelLayout = new GroupLayout(otherPanel);
        otherPanel.setLayout(otherPanelLayout);
        otherPanelLayout.setHorizontalGroup(
            otherPanelLayout
                .createParallelGroup()
                .addGroup(
                    otherPanelLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            otherPanelLayout
                                .createParallelGroup()
                                .addComponent(
                                    otherScroll, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                .addComponent(btnOther, GroupLayout.Alignment.TRAILING))
                        .addContainerGap()));
        otherPanelLayout.setVerticalGroup(
            otherPanelLayout
                .createParallelGroup()
                .addGroup(
                    otherPanelLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            otherScroll,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOther)
                        .addContainerGap(41, Short.MAX_VALUE)));
      }
      actionTab.addTab("other...", otherPanel);
    }

    // ======== messageScroll ========
    {

      // ---- messageTxt ----
      messageTxt.setColumns(20);
      messageTxt.setEditable(false);
      messageTxt.setLineWrap(true);
      messageTxt.setRows(2);
      messageTxt.setWrapStyleWord(true);
      messageScroll.setViewportView(messageTxt);
    }

    Container contentPane = getContentPane();
    GroupLayout contentPaneLayout = new GroupLayout(contentPane);
    contentPane.setLayout(contentPaneLayout);
    contentPaneLayout.setHorizontalGroup(
        contentPaneLayout
            .createParallelGroup()
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                contentPaneLayout
                    .createSequentialGroup()
                    .addGroup(
                        contentPaneLayout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                GroupLayout.Alignment.LEADING,
                                contentPaneLayout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(
                                        actionTab, GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                            .addGroup(
                                GroupLayout.Alignment.LEADING,
                                contentPaneLayout
                                    .createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(
                                        contentPaneLayout
                                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMsgId)
                                            .addComponent(lblMessage))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        msgIdTxt,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblDateTime)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        datetimeTxt,
                                        GroupLayout.PREFERRED_SIZE,
                                        188,
                                        GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                GroupLayout.Alignment.LEADING,
                                contentPaneLayout
                                    .createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(lblRawMessage)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        contentPaneLayout
                                            .createParallelGroup()
                                            .addComponent(
                                                messageScroll,
                                                GroupLayout.DEFAULT_SIZE,
                                                390,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                rawMessageScroll,
                                                GroupLayout.DEFAULT_SIZE,
                                                390,
                                                Short.MAX_VALUE)))
                            .addGroup(
                                contentPaneLayout
                                    .createSequentialGroup()
                                    .addContainerGap(478, Short.MAX_VALUE)
                                    .addComponent(btnAck)))
                    .addContainerGap()));
    contentPaneLayout.setVerticalGroup(
        contentPaneLayout
            .createParallelGroup()
            .addGroup(
                contentPaneLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        contentPaneLayout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMsgId)
                            .addComponent(
                                msgIdTxt,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateTime)
                            .addComponent(
                                datetimeTxt,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        contentPaneLayout
                            .createParallelGroup()
                            .addComponent(lblMessage)
                            .addComponent(
                                messageScroll,
                                GroupLayout.PREFERRED_SIZE,
                                50,
                                GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        contentPaneLayout
                            .createParallelGroup()
                            .addComponent(lblRawMessage)
                            .addComponent(
                                rawMessageScroll, GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnAck)
                    .addGap(11, 11, 11)
                    .addComponent(
                        actionTab, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    pack();
    setLocationRelativeTo(getOwner());

    // ======== unusedPanel ========
    {
      GroupLayout unusedPanelLayout = new GroupLayout(unusedPanel);
      unusedPanel.setLayout(unusedPanelLayout);
      unusedPanelLayout.setHorizontalGroup(
          unusedPanelLayout.createParallelGroup().addGap(0, 100, Short.MAX_VALUE));
      unusedPanelLayout.setVerticalGroup(
          unusedPanelLayout.createParallelGroup().addGap(0, 100, Short.MAX_VALUE));
    }
  } // </editor-fold>//GEN-END:initComponents

  private void btnAckActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnAckActionPerformed
    ackMessage(message.getMsgId());
  } // GEN-LAST:event_btnAckActionPerformed

  private void btnTransferMouseReleased(
      MouseEvent evt) { // GEN-FIRST:event_btnTransferMouseReleased
    boolean doOp = false;

    if (message.getActioned()) {
      doOp =
          JOptionPane.showConfirmDialog(
                  this,
                  "The operation has been already executed. Do you want to execute-it again?",
                  "Confirm to re-execute an action",
                  JOptionPane.YES_NO_OPTION,
                  JOptionPane.QUESTION_MESSAGE)
              == 0;
    } else {
      doOp = true;
    }

    if (doOp) {
      if (resData.getTranferMsgReID().equals(EppParams.getParameter("EppClient.defaultUser"))) {
        // We requested this transfer
        txtTransfer.setText(
            "The transfer of the domain name "
                + resData.getTranferMsgName()
                + " to Registrar "
                + EppParams.getParameter("EppClient.defaultUser")
                + " has been ");
        if (resData.getTranferMsgTrStatus().equals("clientApproved")) {
          ImportDomain transferredDomain = new ImportDomain(mainFrame, true);
          if (transferredDomain.execute(resData.getTranferMsgName())) {
            txtTransfer.setText(
                txtTransfer.getText()
                    + "\nThe domain name has been successfully added to the client local"
                    + " database.");
            message.setActioned(true);
            db.editRecord(message);
            if (!message.getAck()) {
              if (ackMessage(message.getMsgId())) {
                txtTransfer.setText(
                    txtTransfer.getText() + ", this message has been automatically Acked.");
              } else {
                txtTransfer.setText(
                    txtTransfer.getText() + ", an error occurred while Ack'ing the message.");
              }
            }
          } else {
            txtTransfer.setText(
                txtTransfer.getText()
                    + "\nAn error occurred while importing the domain name to the client"
                    + " local database.");
          }
        }

      } else {
        // Someone else requested this transfer
        if (resData.getTranferMsgTrStatus().equals("pending")) {
          DomainTransfer domainTransfer = null;
          switch (JOptionPane.showConfirmDialog(
              this,
              "There is a new request to transfer the domain "
                  + resData.getTranferMsgName()
                  + " to registrar "
                  + resData.getTranferMsgReID()
                  + ".\n\nDo you want to aknowledge the transfer?",
              "New Outbound transfer request",
              JOptionPane.YES_NO_CANCEL_OPTION,
              JOptionPane.QUESTION_MESSAGE)) {
            case 0:
              domainTransfer = new DomainTransfer(resData.getTranferMsgName());
              domainTransfer.setTransferApprove();
              log.debug("Transfer approve: {}", domainTransfer);
              try {
                response = eppUplink.sendCommand(domainTransfer);
              } catch (XmlException e) {
                log.error("XmlException in btnTransferMouseReleased", e);
              } catch (IOException e) {
                log.error("IOException in btnTransferMouseReleased", e);
              }
              log.debug("Transfer response: {}", response);
              if (response.isSuccessfully()) {
                txtTransfer.setText(
                    txtTransfer.getText()
                        + "\n============\nThe transfer has been successfully Acknowledged!");
                message.setActioned(true);
                db.editRecord(message);
                if (!message.getAck()) {
                  if (ackMessage(message.getMsgId())) {
                    txtTransfer.setText(
                        txtTransfer.getText() + ", this message has been automatically Acked.");
                  } else {
                    txtTransfer.setText(
                        txtTransfer.getText() + ", an error occurred while Ack'ing the message.");
                  }
                }
              } else {
                txtTransfer.setText(
                    txtTransfer.getText()
                        + "\n============\nAn error occurred while Acknowledging the transfer."
                        + " This messages has NOT been Acked.");
              }
              break;
            case 1:
              domainTransfer = new DomainTransfer(resData.getTranferMsgName());
              domainTransfer.setTransferReject();
              log.debug("Transfer reject: {}", domainTransfer);
              try {
                response = eppUplink.sendCommand(domainTransfer);
              } catch (XmlException e) {
                log.error("XmlException in btnTransferMouseReleased reject", e);
              } catch (IOException e) {
                log.error("IOException in btnTransferMouseReleased reject", e);
              }
              log.debug("Transfer reject response: {}", response);
              if (response.isSuccessfully()) {
                txtTransfer.setText(
                    txtTransfer.getText()
                        + "\n============\nThe transfer has been successfully Rejected!");
                message.setActioned(true);
                db.editRecord(message);
                if (!message.getAck()) {
                  if (ackMessage(message.getMsgId())) {
                    txtTransfer.setText(
                        txtTransfer.getText() + " This message has been automatically Acked.");
                  } else {
                    txtTransfer.setText(
                        txtTransfer.getText() + " An error occurred while Ack'ing the message.");
                  }
                }
              } else {
                txtTransfer.setText(
                    txtTransfer.getText()
                        + "\n============\nAn error occurred while Rejecting the transfer."
                        + " This messages has NOT been Acked.");
              }
              break;
            case 2:
              JOptionPane.showMessageDialog(this, "Doing nothing!");
              break;
            default:
              break;
          }
        } else if (resData.getTranferMsgTrStatus().equals("clientApproved")
            || resData.getTranferMsgTrStatus().equals("serverApproved")) {
          mainFrame.domainsDao.deleteRecord(resData.getTranferMsgName());
          txtTransfer.setText(
              txtTransfer.getText()
                  + "\n============\nThe domain name has been successfully deleted from"
                  + " the client local database.");
          message.setActioned(true);
          db.editRecord(message);
          if (!message.getAck()) {
            if (ackMessage(message.getMsgId())) {
              txtTransfer.setText(
                  txtTransfer.getText() + " This message has been automatically Acked.");
            } else {
              txtTransfer.setText(
                  txtTransfer.getText() + " An error occurred while Ack'ing the message.");
            }
          }
        }
      }
    }
  } // GEN-LAST:event_btnTransferMouseReleased

  private void btnOtherMouseReleased(MouseEvent evt) { // GEN-FIRST:event_btnOtherMouseReleased
    boolean doOp = false;

    if (message.getActioned()) {
      doOp =
          JOptionPane.showConfirmDialog(
                  this,
                  "The operation has been already executed. Do you want to execute-it again?",
                  "Confirm to re-execute an action",
                  JOptionPane.YES_NO_OPTION,
                  JOptionPane.QUESTION_MESSAGE)
              == 0;
    } else {
      doOp = true;
    }

    if (doOp) {

      if (response.getMsgQText().equalsIgnoreCase("Domain has been deleted")) {
        mainFrame.domainsDao.deleteRecord(extData.getSimpleMsgDomains()[0]);
        txtOther.setText(
            txtOther.getText()
                + "\n============\nThe domain name has been successfully deleted from"
                + " the client local database.");
        message.setActioned(true);
        db.editRecord(message);
        if (!message.getAck()) {
          if (ackMessage(message.getMsgId())) {
            txtOther.setText(txtOther.getText() + " This message has been automatically Acked.");
          } else {
            txtOther.setText(txtOther.getText() + " An error occurred while Ack'ing the message.");
          }
        }
      } else if (response.getMsgQText().equalsIgnoreCase("autoRenewPeriod is expired")) {

        ImportDomain syncDomain = new ImportDomain(mainFrame, true);
        if (syncDomain.execute(extData.getChgStatusMsgName())) {
          txtOther.setText(
              txtOther.getText()
                  + "\nThe domain name has been successfully updated on the client local"
                  + " database.");
          message.setActioned(true);
          db.editRecord(message);
          if (!message.getAck()) {
            if (ackMessage(message.getMsgId())) {
              txtOther.setText(txtOther.getText() + ", this message has been automatically Acked.");
            } else {
              txtOther.setText(
                  txtOther.getText() + ", an error occurred while Ack'ing the message.");
            }
          }
        }
      }
    }
  } // GEN-LAST:event_btnOtherMouseReleased

  protected String getMsgId() {
    return message.getMsgId();
  }

  /**
   * Shows or hides the acknowledge button based on whether the EPP connection is active.
   *
   * @param eppStatus {@code true} if the EPP connection is active
   */
  public void setEppEnablement(boolean eppStatus) {
    btnAck.setVisible(eppStatus);
    btnTransfer.setVisible(eppStatus);
  }

  private void switchAck() {
    if (!message.getAck()) {
      btnAck.setEnabled(true);
      btnAck.setText("click to ACK");
    } else {
      btnAck.setEnabled(false);
      btnAck.setText("msg Already ACKED");
    }

    actionTab.setEnabledAt(0, true);
    actionTab.setEnabledAt(1, false);
    actionTab.setEnabledAt(2, false);

    if (resData != null) {
      if (resData.isTransferMsg()) {
        actionTab.setEnabledAt(0, false);
        actionTab.setEnabledAt(1, true);
        actionTab.setSelectedIndex(1);

        if (resData.getTranferMsgReID().equals(EppParams.getParameter("EppClient.defaultUser"))) {
          // We requested this transfer
          txtTransfer.setText(
              "The transfer of the domain name "
                  + resData.getTranferMsgName()
                  + " to Registrar "
                  + EppParams.getParameter("EppClient.defaultUser")
                  + " has been ");
          if (resData.getTranferMsgTrStatus().equals("clientRejected")) {
            txtTransfer.setText(txtTransfer.getText() + "REJECTED by the Losing Registrar.");
            btnTransfer.setText("---");
            btnTransfer.setEnabled(false);
          } else if (resData.getTranferMsgTrStatus().equals("clientApproved")) {
            txtTransfer.setText(
                txtTransfer.getText()
                    + "APPROVED by the Losing Registrar, the Domain Name has been added to your"
                    + " account on the Registry. Please click the button below to save it"
                    + " on the client local database.");
            btnTransfer.setText("Save to local db");
            btnTransfer.setEnabled(true);
          } else {
            btnTransfer.setText(resData.getTranferMsgTrStatus());
            txtTransfer.setText("There is no specific action to do.");
            // btnTransfer.setText("---");
            btnTransfer.setEnabled(false);
          }

        } else {
          // Someone else requested this transfer
          if (resData.getTranferMsgTrStatus().equals("pending")) {
            txtTransfer.setText(
                "There is a new request to transfer the domain name "
                    + resData.getTranferMsgName()
                    + " to Registrar "
                    + EppParams.getParameter("EppClient.defaultUser")
                    + " to Registrar "
                    + resData.getTranferMsgReID()
                    + ". Please click the button below to ACK o REJ the Transfer (will also ACK"
                    + " the message).");
            btnTransfer.setText("Acknowledge/Reject Transfer");
            btnTransfer.setEnabled(true);
          } else if (resData.getTranferMsgTrStatus().equals("clientApproved")
              || resData.getTranferMsgTrStatus().equals("serverApproved")) {
            txtTransfer.setText(
                "The domain name "
                    + resData.getTranferMsgName()
                    + " has been successfully transferred to Registrar "
                    + resData.getTranferMsgReID()
                    + ". Please click the button below to delete-it from the client local"
                    + " database.");
            btnTransfer.setText("Delete from local db");
            btnTransfer.setEnabled(true);
          } else {
            txtTransfer.setText("There is no specific action to do.");
            btnTransfer.setText("---");
            btnTransfer.setEnabled(false);
          }
        }
      }

    } else if (response.getMsgQText().equalsIgnoreCase("Domain has been deleted")) {
      actionTab.setEnabledAt(0, false);
      actionTab.setEnabledAt(1, false);
      actionTab.setEnabledAt(2, true);
      actionTab.setSelectedIndex(2);
      txtOther.setText(
          "The domain name "
              + extData.getSimpleMsgDomains()[0]
              + " has been deleted. Please click the button below to delete-it from the"
              + " client local database.");
      btnOther.setText("Delete from local db");
      btnOther.setEnabled(true);

    } else if (response.getMsgQText().equalsIgnoreCase("autoRenewPeriod is expired")) {
      actionTab.setEnabledAt(0, false);
      actionTab.setEnabledAt(1, false);
      actionTab.setEnabledAt(2, true);
      actionTab.setSelectedIndex(2);
      txtOther.setText(
          "The domain name "
              + extData.getChgStatusMsgName()
              + " autoRenewPeriod is expired. Please click the button below to update the"
              + " expiration date stored in the local database.");
      btnOther.setText("Update expiration date on local db");
      btnOther.setEnabled(true);
    }
  }

  /**
   * Sends an EPP poll acknowledgement for the given message ID.
   *
   * @param msgQid the message queue ID to acknowledge
   * @return {@code true} if the acknowledgement was accepted by the registry
   */
  protected boolean ackMessage(String msgQid) {
    boolean ackStatus = false;
    HttpBaseResponse response = null;
    try {
      Poll pollCmd = new Poll();
      pollCmd.setAck(msgQid);
      log.debug("ACK: {}", pollCmd);
      response = eppUplink.sendCommand(pollCmd);
      if (response.isSuccessfully()) {
        ackStatus = true;
        message.setAck(true);
        db.editRecord(message);
        parentFrame.updateTableContent();
        switchAck();
        eppUplink.doPoll();
      } else {
        if (JOptionPane.showConfirmDialog(
                this,
                "An error occurred while aknowledging a message.\n\n"
                    + "Do you want to see the Registry XML response?",
                "Registry adknowledgment failure",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE)
            == 0) {
          JOptionPane.showMessageDialog(this, response.toString());
        }
      }
    } catch (EppSchemaException v) {
      log.error("EppSchemaException in ackMessage", v);
    } catch (XmlException v) {
      log.error("XmlException in ackMessage", v);
    } catch (IOException v) {
      log.error("IOException in ackMessage", v);
    }

    return ackStatus;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel lblMsgId;
  private JTextField msgIdTxt;
  private JLabel lblMessage;
  private JLabel lblRawMessage;
  private JScrollPane rawMessageScroll;
  private JTextArea rawMessageTxt;
  private JLabel lblDateTime;
  private JTextField datetimeTxt;
  private JButton btnAck;
  private JTabbedPane actionTab;
  private JPanel genericPanel;
  private JScrollPane genericScroll;
  private JTextArea txtGeneric;
  private JPanel transferPanel;
  private JButton btnTransfer;
  private JScrollPane transferScroll;
  private JTextArea txtTransfer;
  private JPanel otherPanel;
  private JScrollPane otherScroll;
  private JTextArea txtOther;
  private JButton btnOther;
  private JScrollPane messageScroll;
  private JTextArea messageTxt;
  private JPanel unusedPanel;
  // End of variables declaration//GEN-END:variables

}
