/*
 * SPDX-FileCopyrightText: 2008-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package com.codetotime.eppclient.config;

import static net.logstash.logback.argument.StructuredArguments.kv;

import com.codetotime.eppclient.CustomLogin;
import com.codetotime.eppclient.ErrorHandler;
import com.codetotime.eppclient.Main;
import it.nic.epp.client.commands.session.Logout;
import it.nic.epp.client.httpClient.Client;
import it.nic.epp.client.responses.HttpBaseResponse;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.border.EtchedBorder;
import org.apache.xmlbeans.XmlException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Swing form for viewing and editing all application configuration parameters. */
public class ManageParameters extends JFrame implements WindowListener {
  private static final Logger log = LoggerFactory.getLogger(ManageParameters.class);

  Main mainFrame;
  private boolean isKillRequired;
  private boolean killOnClose;

  /** Creates new form manageParameters2. */
  public ManageParameters(Main mainFrame) {
    initComponents();
    this.mainFrame = mainFrame;
    isKillRequired = false;
    killOnClose = false;
    this.addWindowListener(this);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

  private void initComponents() {
    lblEppUserName = new JLabel();
    defaultUser = new JTextField();
    defaultPassword = new JTextField();
    lblEppPassword = new JLabel();
    serverUri = new JTextField();
    lblProxyHost = new JLabel();
    saveButton = new JButton();
    cancelButton = new JButton();
    btnChangePwd = new JButton();
    saveCloseButton = new JButton();
    dbhost = new JTextField();
    lblDbHostname = new JLabel();
    lblDbEngine = new JLabel();
    dbengine = new JComboBox<>();
    dbname = new JTextField();
    lblDbName = new JLabel();
    dbuid = new JTextField();
    dbpwd = new JTextField();
    lblDbUid = new JLabel();
    lblDbPwd = new JLabel();
    refreshInterval = new JTextField();
    lblRefreshInterval = new JLabel();
    emptyDb = new JButton();
    lblEppServerUri = new JLabel();
    lblProxyPort = new JLabel();
    proxyHost = new JTextField();
    proxyPort = new JTextField();
    contactPrefix = new JTextField();
    lblContactPrefix = new JLabel();
    defaultTech = new JTextField();
    defaultNs = new JTextField();
    lblDefaultTech = new JLabel();
    lblDefaultNs = new JLabel();
    lblTechExample = new JLabel();
    lblNsExample = new JLabel();
    lblDnssec = new JLabel();
    chkDnsSec = new JCheckBox();

    // ======== this ========
    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Gestione CONFIGURAZIONE");
    setLocationByPlatform(true);
    setMinimumSize(new Dimension(480, 400));
    Container contentPane = getContentPane();
    contentPane.setLayout(new GridBagLayout());

    // ---- lblEppUserName ----
    lblEppUserName.setText("eppUserName");
    contentPane.add(
        lblEppUserName,
        new GridBagConstraints(
            0,
            0,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- defaultUser ----
    defaultUser.setMinimumSize(new Dimension(150, 20));
    defaultUser.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        defaultUser,
        new GridBagConstraints(
            1,
            0,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- defaultPassword ----
    defaultPassword.setMinimumSize(new Dimension(150, 20));
    defaultPassword.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        defaultPassword,
        new GridBagConstraints(
            1,
            1,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblEppPassword ----
    lblEppPassword.setText("eppPassword");
    contentPane.add(
        lblEppPassword,
        new GridBagConstraints(
            0,
            1,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- serverUri ----
    serverUri.setMinimumSize(new Dimension(250, 20));
    serverUri.setPreferredSize(new Dimension(250, 20));
    contentPane.add(
        serverUri,
        new GridBagConstraints(
            1,
            2,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.CENTER,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblProxyHost ----
    lblProxyHost.setText("proxyHost");
    contentPane.add(
        lblProxyHost,
        new GridBagConstraints(
            0,
            3,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- saveButton ----
    saveButton.setText("Save");
    saveButton.addActionListener(e -> saveButtonActionPerformed(e));
    contentPane.add(
        saveButton,
        new GridBagConstraints(
            1,
            14,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0),
            0,
            0));

    // ---- cancelButton ----
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(e -> cancelButtonActionPerformed(e));
    contentPane.add(
        cancelButton,
        new GridBagConstraints(
            3,
            14,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0),
            0,
            0));

    // ---- btnChangePwd ----
    btnChangePwd.setFont(new Font("Tahoma", Font.PLAIN, 10));
    btnChangePwd.setText("Cambio Password");
    btnChangePwd.setBorder(new EtchedBorder());
    btnChangePwd.setMaximumSize(new Dimension(100, 19));
    btnChangePwd.setMinimumSize(new Dimension(100, 19));
    btnChangePwd.setPreferredSize(new Dimension(100, 19));
    btnChangePwd.addActionListener(e -> btnChangePwdActionPerformed(e));
    contentPane.add(
        btnChangePwd,
        new GridBagConstraints(
            2,
            1,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.CENTER,
            GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0),
            0,
            0));

    // ---- saveCloseButton ----
    saveCloseButton.setText("Save & Close");
    saveCloseButton.addActionListener(e -> saveCloseButtonActionPerformed(e));
    contentPane.add(
        saveCloseButton,
        new GridBagConstraints(
            2,
            14,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.CENTER,
            GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0),
            0,
            0));

    // ---- dbhost ----
    dbhost.setMinimumSize(new Dimension(150, 20));
    dbhost.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        dbhost,
        new GridBagConstraints(
            1,
            10,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDbHostname ----
    lblDbHostname.setText("dbHostname");
    contentPane.add(
        lblDbHostname,
        new GridBagConstraints(
            0,
            10,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDbEngine ----
    lblDbEngine.setText("dbEngine");
    contentPane.add(
        lblDbEngine,
        new GridBagConstraints(
            0,
            8,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- dbengine ----
    dbengine.setModel(
        new DefaultComboBoxModel<>(new String[] {"Internal DB", "MySQL/MariaDB", "PostgreSQL"}));
    dbengine.setPreferredSize(new Dimension(150, 20));
    dbengine.addActionListener(e -> dbengineActionPerformed(e));
    contentPane.add(
        dbengine,
        new GridBagConstraints(
            1,
            8,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- dbname ----
    dbname.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        dbname,
        new GridBagConstraints(
            1,
            9,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDbName ----
    lblDbName.setText("dbName");
    contentPane.add(
        lblDbName,
        new GridBagConstraints(
            0,
            9,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- dbuid ----
    dbuid.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        dbuid,
        new GridBagConstraints(
            1,
            11,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- dbpwd ----
    dbpwd.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        dbpwd,
        new GridBagConstraints(
            1,
            12,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDbUid ----
    lblDbUid.setText("dbUID");
    contentPane.add(
        lblDbUid,
        new GridBagConstraints(
            0,
            11,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDbPwd ----
    lblDbPwd.setText("dbPWD");
    contentPane.add(
        lblDbPwd,
        new GridBagConstraints(
            0,
            12,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- refreshInterval ----
    refreshInterval.setPreferredSize(new Dimension(50, 20));
    contentPane.add(
        refreshInterval,
        new GridBagConstraints(
            1,
            4,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblRefreshInterval ----
    lblRefreshInterval.setText("refreshInterval (s)");
    contentPane.add(
        lblRefreshInterval,
        new GridBagConstraints(
            0,
            4,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- emptyDb ----
    emptyDb.setText("Azzera DB");
    emptyDb.addActionListener(e -> emptyDbActionPerformed(e));
    contentPane.add(
        emptyDb,
        new GridBagConstraints(
            2,
            8,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.CENTER,
            GridBagConstraints.NONE,
            new Insets(0, 0, 0, 0),
            0,
            0));

    // ---- lblEppServerUri ----
    lblEppServerUri.setText("eppServerURI");
    contentPane.add(
        lblEppServerUri,
        new GridBagConstraints(
            0,
            2,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblProxyPort ----
    lblProxyPort.setText("proxyPort");
    contentPane.add(
        lblProxyPort,
        new GridBagConstraints(
            2,
            3,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.CENTER,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- proxyHost ----
    proxyHost.setMinimumSize(new Dimension(250, 20));
    proxyHost.setPreferredSize(new Dimension(250, 20));
    contentPane.add(
        proxyHost,
        new GridBagConstraints(
            1,
            3,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- proxyPort ----
    proxyPort.setPreferredSize(new Dimension(50, 20));
    contentPane.add(
        proxyPort,
        new GridBagConstraints(
            3,
            3,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- contactPrefix ----
    contactPrefix.setPreferredSize(new Dimension(150, 20));
    contentPane.add(
        contactPrefix,
        new GridBagConstraints(
            1,
            5,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblContactPrefix ----
    lblContactPrefix.setText("contactPrefix");
    contentPane.add(
        lblContactPrefix,
        new GridBagConstraints(
            0,
            5,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- defaultTech ----
    defaultTech.setMinimumSize(new Dimension(250, 20));
    defaultTech.setPreferredSize(new Dimension(250, 20));
    contentPane.add(
        defaultTech,
        new GridBagConstraints(
            1,
            6,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- defaultNs ----
    defaultNs.setMinimumSize(new Dimension(250, 20));
    defaultNs.setPreferredSize(new Dimension(250, 20));
    contentPane.add(
        defaultNs,
        new GridBagConstraints(
            1,
            7,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDefaultTech ----
    lblDefaultTech.setText("defaultTech");
    contentPane.add(
        lblDefaultTech,
        new GridBagConstraints(
            0,
            6,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDefaultNs ----
    lblDefaultNs.setText("defaultNS");
    contentPane.add(
        lblDefaultNs,
        new GridBagConstraints(
            0,
            7,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblTechExample ----
    lblTechExample.setFont(new Font(Font.DIALOG, Font.PLAIN, 10));
    lblTechExample.setText("(es.: TECH1;TECH2;TECH3)");
    contentPane.add(
        lblTechExample,
        new GridBagConstraints(
            2,
            6,
            2,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblNsExample ----
    lblNsExample.setFont(new Font(Font.DIALOG, Font.PLAIN, 10));
    lblNsExample.setText("(es.: dns1.example.it;dns2.example.it)");
    contentPane.add(
        lblNsExample,
        new GridBagConstraints(
            2,
            7,
            2,
            1,
            0.0,
            0.0,
            GridBagConstraints.WEST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- lblDnssec ----
    lblDnssec.setText("DNSSEC");
    contentPane.add(
        lblDnssec,
        new GridBagConstraints(
            0,
            13,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.EAST,
            GridBagConstraints.NONE,
            new Insets(5, 5, 5, 5),
            0,
            0));

    // ---- chkDnsSec ----
    chkDnsSec.setText("Abilita supporto a DNSSEC");
    contentPane.add(
        chkDnsSec,
        new GridBagConstraints(
            1,
            13,
            1,
            1,
            0.0,
            0.0,
            GridBagConstraints.CENTER,
            GridBagConstraints.BOTH,
            new Insets(0, 0, 0, 0),
            0,
            0));
    pack();
    setLocationRelativeTo(getOwner());
  } // </editor-fold>//GEN-END:initComponents

  private void saveButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_saveButtonActionPerformed
    saveParameters();
  } // GEN-LAST:event_saveButtonActionPerformed

  private void cancelButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_cancelButtonActionPerformed
    this.setVisible(false);
  } // GEN-LAST:event_cancelButtonActionPerformed

  private void btnChangePwdActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnChangePwdActionPerformed
    boolean passwordOk = false;
    while (!passwordOk) {
      String newPassword =
          JOptionPane.showInputDialog(
              null, "Enter new Password: ", "Change password at Registry", 1);

      if (newPassword == null) {
        break;
      } else if (newPassword.length() == 0) {
        JOptionPane.showMessageDialog(
            this,
            "The New Password cannot be an empty string.",
            "Password cannot be empty",
            JOptionPane.ERROR_MESSAGE);
      } else if (EppParams.getParameter("EppClient.defaultPassword").equals(newPassword)) {
        JOptionPane.showMessageDialog(
            this,
            "The New Password cannot be the same as the Old Password.",
            "New Password = Old Password",
            JOptionPane.ERROR_MESSAGE);
      } else {
        try {
          // sets the serverUri
          URI serverUri = new URI(EppParams.getParameter("EppClient.Epp.serverUri"));

          // creates a login command with a valid account
          CustomLogin login =
              new CustomLogin(
                  EppParams.getParameter("EppClient.defaultUser"),
                  EppParams.getParameter("EppClient.defaultPassword"));

          login.setNewPW(newPassword);

          // creates a new client
          Client client = new Client(serverUri.toString());

          // send the login command
          log.info("Changing EPP password");
          log.debug("EPP > login (password change request omitted for security)");
          HttpBaseResponse response = client.sendCommand(login);
          log.trace("EPP < login", kv("raw_xml", response.toString()));

          // send the logout command with verbose interaction
          Logout logout = new Logout();
          log.trace("EPP > logout", kv("raw_xml", logout.xmlText()));
          response = client.sendCommand(logout);
          log.trace("EPP < logout", kv("raw_xml", response.toString()));

          defaultPassword.setText(newPassword);
          EppParams.setParameter("EppClient.defaultPassword", defaultPassword.getText());

          JOptionPane.showMessageDialog(
              this,
              "Password successfully changed at the Registry.",
              "Password changed",
              JOptionPane.INFORMATION_MESSAGE);
          passwordOk = true;
        } catch (NullPointerException v) {
          ErrorHandler.error(log, v, "Error changing password", this);
        } catch (URISyntaxException v) {
          ErrorHandler.error(log, v, "Error changing password", this);
        } catch (XmlException v) {
          ErrorHandler.error(log, v, "Error changing password", this);
        } catch (IOException v) {
          ErrorHandler.error(log, v, "Error changing password", this);
        }
      }
    }
  } // GEN-LAST:event_btnChangePwdActionPerformed

  private void saveCloseButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_saveCloseButtonActionPerformed
    saveParameters();
    this.setVisible(false);
  } // GEN-LAST:event_saveCloseButtonActionPerformed

  private void dbengineActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_dbengineActionPerformed
    setVisibleOnDbEngine();
    // isKillRequired = true;
  } // GEN-LAST:event_dbengineActionPerformed

  private void emptyDbActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_emptyDbActionPerformed
    dropTables();
  } // GEN-LAST:event_emptyDbActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables

  private JLabel lblEppUserName;
  private JTextField defaultUser;
  private JTextField defaultPassword;
  private JLabel lblEppPassword;
  private JTextField serverUri;
  private JLabel lblProxyHost;
  private JButton saveButton;
  private JButton cancelButton;
  private JButton btnChangePwd;
  private JButton saveCloseButton;
  private JTextField dbhost;
  private JLabel lblDbHostname;
  private JLabel lblDbEngine;
  private JComboBox<String> dbengine;
  private JTextField dbname;
  private JLabel lblDbName;
  private JTextField dbuid;
  private JTextField dbpwd;
  private JLabel lblDbUid;
  private JLabel lblDbPwd;
  private JTextField refreshInterval;
  private JLabel lblRefreshInterval;
  private JButton emptyDb;
  private JLabel lblEppServerUri;
  private JLabel lblProxyPort;
  private JTextField proxyHost;
  private JTextField proxyPort;
  private JTextField contactPrefix;
  private JLabel lblContactPrefix;
  private JTextField defaultTech;
  private JTextField defaultNs;
  private JLabel lblDefaultTech;
  private JLabel lblDefaultNs;
  private JLabel lblTechExample;
  private JLabel lblNsExample;
  private JLabel lblDnssec;
  private JCheckBox chkDnsSec;

  // End of variables declaration//GEN-END:variables

  /**
   * Enables or disables EPP-related controls based on connection status.
   *
   * @param eppStatus {@code true} if the EPP connection is active
   */
  public void setEppEnablement(boolean eppStatus) {
    // btnChangePwd.setVisible(eppStatus);
  }

  private void saveParameters() {
    EppParams.setParameter("EppClient.defaultUser", defaultUser.getText());
    EppParams.setParameter("EppClient.defaultPassword", defaultPassword.getText());

    if (serverUri.getText().contains("https://epp-acc1.nic.it")
        || serverUri.getText().contains("https://epp-acc2.nic.it")) {
      JOptionPane.showMessageDialog(
          this,
          "Please DONT'T enter accreditation test server here!\n\n"
              + "To proceed with the .it Registry Accreditation test go to the TEST section.\n\n"
              + "As the accreditation procedure requires several operations to be executed in"
              + " sequence\n"
              + "entering here an accreditation server hostname will cause the test to fail.",
          "ACCREDITATION SERVER FOUND",
          JOptionPane.INFORMATION_MESSAGE);
      serverUri.setText(EppParams.getParameter("EppClient.serverUri"));
    } else {
      EppParams.setParameter("EppClient.serverUri", serverUri.getText());
    }

    EppParams.setParameter("EppClient.proxyHost", proxyHost.getText());

    // Handle proxyPort - save as string, validate if numeric
    String proxyPortValue = proxyPort.getText().trim();
    try {
      Integer.parseInt(proxyPortValue);
    } catch (NumberFormatException ex) {
      log.debug("Invalid proxy port value: {}", proxyPortValue);
      proxyPortValue = ""; // Treat invalid numeric values as empty string
    }
    EppParams.setParameter("EppClient.proxyPort", proxyPortValue);

    EppParams.setParameter("EppClient.contactPrefix", contactPrefix.getText());
    EppParams.setParameter("EppClient.defaultTech", defaultTech.getText());
    EppParams.setParameter("EppClient.defaultNS", defaultNs.getText());

    // Handle refreshInterval - save as string, validate if numeric
    String refreshValue = refreshInterval.getText().trim();
    try {
      Integer.parseInt(refreshValue);
    } catch (NumberFormatException ex) {
      log.debug("Invalid refresh interval value: {}", refreshValue);
      refreshValue = ""; // Treat invalid numeric values as empty string
    }
    EppParams.setParameter("EppClient.refreshInterval", refreshValue);

    EppParams.setParameter("EppClient.dbengine", Integer.toString(dbengine.getSelectedIndex()));
    EppParams.setParameter("EppClient.dbname", dbname.getText());
    EppParams.setParameter("EppClient.dbhost", dbhost.getText());
    EppParams.setParameter("EppClient.dbuid", dbuid.getText());
    EppParams.setParameter("EppClient.dbpwd", dbpwd.getText());
    EppParams.setParameter("EppClient.implement.DNSSEC", Boolean.toString(chkDnsSec.isSelected()));

    switch (dbengine.getSelectedIndex()) { // 0: derby, 1: mysql/mariadb, 2: postgresql
      case 0:
        EppParams.setParameter("EppClient.dburl", "jdbc:derby:");
        EppParams.setParameter("EppClient.dbname", "eppclient");
        EppParams.setParameter("EppClient.dbuid", "eppclient");
        EppParams.setParameter("EppClient.dbpwd", "clientepp");
        break;
      case 1:
        EppParams.setParameter(
            "EppClient.dburl", "jdbc:mariadb://" + dbhost.getText() + "/" + dbname.getText());
        break;
      case 2:
        EppParams.setParameter(
            "EppClient.dburl", "jdbc:postgresql://" + dbhost.getText() + "/" + dbname.getText());
        break;
      default:
        break;
    }

    if (isKillRequired) {
      killOnClose = true;
    }
  }

  private void dropTables() {
    killOnClose = true;
    mainFrame.messagesDao.disconnect();
    mainFrame.messagesDao.connect();
    mainFrame.messagesDao.dropTables();
    mainFrame.messagesDao.disconnect();

    mainFrame.contactsDao.disconnect();
    mainFrame.contactsDao.connect();
    mainFrame.contactsDao.dropTables();
    mainFrame.contactsDao.disconnect();

    mainFrame.domainsDao.disconnect();
    mainFrame.domainsDao.connect();
    mainFrame.domainsDao.dropTables();
    mainFrame.domainsDao.disconnect();
  }

  private void setVisibleOnDbEngine() {
    switch (dbengine.getSelectedIndex()) { // 0: derby, 1: mysql/mariadb, 2: postgresql
      case 0:
        dbhost.setEditable(false);
        dbname.setEditable(false);
        dbuid.setEditable(false);
        dbpwd.setEditable(false);
        break;
      case 1:
      case 2:
        dbhost.setEditable(true);
        dbname.setEditable(true);
        dbuid.setEditable(true);
        dbpwd.setEditable(true);
        break;
      default:
        break;
    }
  }

  @Override
  public void setVisible(boolean b) {
    super.setVisible(b);
    if (b) {
      defaultUser.setText(EppParams.getParameter("EppClient.defaultUser"));
      defaultPassword.setText(EppParams.getParameter("EppClient.defaultPassword"));
      serverUri.setText(EppParams.getParameter("EppClient.serverUri"));
      proxyHost.setText(EppParams.getParameter("EppClient.proxyHost"));
      proxyPort.setText(EppParams.getParameter("EppClient.proxyPort"));
      contactPrefix.setText(EppParams.getParameter("EppClient.contactPrefix"));
      defaultTech.setText(EppParams.getParameter("EppClient.defaultTech"));
      defaultNs.setText(EppParams.getParameter("EppClient.defaultNS"));
      refreshInterval.setText(EppParams.getParameter("EppClient.refreshInterval"));
      dbengine.setSelectedIndex(Integer.parseInt(EppParams.getParameter("EppClient.dbengine")));
      dbname.setText(EppParams.getParameter("EppClient.dbname"));
      dbhost.setText(EppParams.getParameter("EppClient.dbhost"));
      dbuid.setText(EppParams.getParameter("EppClient.dbuid"));
      dbpwd.setText(EppParams.getParameter("EppClient.dbpwd"));
      chkDnsSec.setSelected(
          Boolean.parseBoolean(EppParams.getParameter("EppClient.implement.DNSSEC")));
      setVisibleOnDbEngine();
    } else {
      if (killOnClose) {
        mainFrame.windowClosing(new WindowEvent(this, 0));
      }
    }
  }

  /** {@inheritDoc} */
  public void windowActivated(WindowEvent e) {}

  /** {@inheritDoc} */
  public void windowOpened(WindowEvent e) {}

  /** {@inheritDoc} */
  public void windowClosed(WindowEvent e) {}

  /** {@inheritDoc} */
  public void windowDeactivated(WindowEvent e) {}

  /** {@inheritDoc} */
  public void windowDeiconified(WindowEvent e) {}

  /** {@inheritDoc} */
  public void windowIconified(WindowEvent e) {}

  /** {@inheritDoc} */
  public void windowClosing(WindowEvent e) {
    if (killOnClose) {
      mainFrame.windowClosing(e);
    }
  }
}
