/*
 * SPDX-FileCopyrightText: 2008-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.config;

import EPPClient.CustomLogin;
import EPPClient.main;
import it.nic.epp.client.commands.session.Login;
import it.nic.epp.client.commands.session.Logout;
import it.nic.epp.client.httpClient.Client;
import it.nic.epp.client.responses.HttpBaseResponse;
import java.net.URI;
import java.net.URISyntaxException;
import org.apache.xmlbeans.XmlException;

import javax.swing.*;
import javax.swing.border.EtchedBorder;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;

public class manageParameters extends JFrame implements WindowListener
{

  main mainFrame;
  private boolean isKillRequired;
  private boolean killOnClose;

  /**
   * Creates new form manageParameters2
   */
  public manageParameters(main mainFrame)
  {
    initComponents();
    this.mainFrame = mainFrame;
    isKillRequired = false;
    killOnClose = false;
    this.addWindowListener(this);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

  private void initComponents() {
      jLabel1 = new JLabel();
      defaultUser = new JTextField();
      defaultPassword = new JTextField();
      jLabel2 = new JLabel();
      serverURI = new JTextField();
      jLabel3 = new JLabel();
      saveButton = new JButton();
      cancelButton = new JButton();
      btnChangePwd = new JButton();
      saveCloseButton = new JButton();
      dbhost = new JTextField();
      lblDbHostname = new JLabel();
      jLabel5 = new JLabel();
      dbengine = new JComboBox<>();
      dbname = new JTextField();
      lblDbName = new JLabel();
      dbuid = new JTextField();
      dbpwd = new JTextField();
      lblDbUid = new JLabel();
      lblDbPwd = new JLabel();
      refreshInterval = new JTextField();
      jLabel4 = new JLabel();
      emptyDb = new JButton();
      jLabel6 = new JLabel();
      jLabel7 = new JLabel();
      proxyHost = new JTextField();
      proxyPort = new JTextField();
      contactPrefix = new JTextField();
      jLabel8 = new JLabel();
      defaultTech = new JTextField();
      defaultNS = new JTextField();
      jLabel9 = new JLabel();
      jLabel10 = new JLabel();
      jLabel11 = new JLabel();
      jLabel12 = new JLabel();
      lblDNSSEC = new JLabel();
      chkDNSSEC = new JCheckBox();

      //======== this ========
      setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Gestione CONFIGURAZIONE");
      setLocationByPlatform(true);
      setMinimumSize(new Dimension(480, 400));
      Container contentPane = getContentPane();
      contentPane.setLayout(new GridBagLayout());

      //---- jLabel1 ----
      jLabel1.setText("eppUserName");
      contentPane.add(jLabel1, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- defaultUser ----
      defaultUser.setMinimumSize(new Dimension(150, 20));
      defaultUser.setPreferredSize(new Dimension(150, 20));
      contentPane.add(defaultUser, new GridBagConstraints(1, 0, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- defaultPassword ----
      defaultPassword.setMinimumSize(new Dimension(150, 20));
      defaultPassword.setPreferredSize(new Dimension(150, 20));
      contentPane.add(defaultPassword, new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel2 ----
      jLabel2.setText("eppPassword");
      contentPane.add(jLabel2, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- serverURI ----
      serverURI.setMinimumSize(new Dimension(250, 20));
      serverURI.setPreferredSize(new Dimension(250, 20));
      contentPane.add(serverURI, new GridBagConstraints(1, 2, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel3 ----
      jLabel3.setText("proxyHost");
      contentPane.add(jLabel3, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- saveButton ----
      saveButton.setText("Save");
      saveButton.addActionListener(e -> saveButtonActionPerformed(e));
      contentPane.add(saveButton, new GridBagConstraints(1, 14, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- cancelButton ----
      cancelButton.setText("Cancel");
      cancelButton.addActionListener(e -> cancelButtonActionPerformed(e));
      contentPane.add(cancelButton, new GridBagConstraints(3, 14, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- btnChangePwd ----
      btnChangePwd.setFont(new Font("Tahoma", Font.PLAIN, 10));
      btnChangePwd.setText("Cambio Password");
      btnChangePwd.setBorder(new EtchedBorder());
      btnChangePwd.setMaximumSize(new Dimension(100, 19));
      btnChangePwd.setMinimumSize(new Dimension(100, 19));
      btnChangePwd.setPreferredSize(new Dimension(100, 19));
      btnChangePwd.addActionListener(e -> btnChangePwdActionPerformed(e));
      contentPane.add(btnChangePwd, new GridBagConstraints(2, 1, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- saveCloseButton ----
      saveCloseButton.setText("Save & Close");
      saveCloseButton.addActionListener(e -> saveCloseButtonActionPerformed(e));
      contentPane.add(saveCloseButton, new GridBagConstraints(2, 14, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- dbhost ----
      dbhost.setMinimumSize(new Dimension(150, 20));
      dbhost.setPreferredSize(new Dimension(150, 20));
      contentPane.add(dbhost, new GridBagConstraints(1, 10, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDbHostname ----
      lblDbHostname.setText("dbHostname");
      contentPane.add(lblDbHostname, new GridBagConstraints(0, 10, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel5 ----
      jLabel5.setText("dbEngine");
      contentPane.add(jLabel5, new GridBagConstraints(0, 8, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- dbengine ----
      dbengine.setModel(new DefaultComboBoxModel<>(new String[] {
          "Internal DB",
          "MySQL/MariaDB",
          "PostgreSQL"
      }));
      dbengine.setPreferredSize(new Dimension(150, 20));
      dbengine.addActionListener(e -> dbengineActionPerformed(e));
      contentPane.add(dbengine, new GridBagConstraints(1, 8, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- dbname ----
      dbname.setPreferredSize(new Dimension(150, 20));
      contentPane.add(dbname, new GridBagConstraints(1, 9, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDbName ----
      lblDbName.setText("dbName");
      contentPane.add(lblDbName, new GridBagConstraints(0, 9, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- dbuid ----
      dbuid.setPreferredSize(new Dimension(150, 20));
      contentPane.add(dbuid, new GridBagConstraints(1, 11, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- dbpwd ----
      dbpwd.setPreferredSize(new Dimension(150, 20));
      contentPane.add(dbpwd, new GridBagConstraints(1, 12, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDbUid ----
      lblDbUid.setText("dbUID");
      contentPane.add(lblDbUid, new GridBagConstraints(0, 11, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDbPwd ----
      lblDbPwd.setText("dbPWD");
      contentPane.add(lblDbPwd, new GridBagConstraints(0, 12, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- refreshInterval ----
      refreshInterval.setPreferredSize(new Dimension(50, 20));
      contentPane.add(refreshInterval, new GridBagConstraints(1, 4, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel4 ----
      jLabel4.setText("refreshInterval (s)");
      contentPane.add(jLabel4, new GridBagConstraints(0, 4, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- emptyDb ----
      emptyDb.setText("Azzera DB");
      emptyDb.addActionListener(e -> emptyDbActionPerformed(e));
      contentPane.add(emptyDb, new GridBagConstraints(2, 8, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- jLabel6 ----
      jLabel6.setText("eppServerURI");
      contentPane.add(jLabel6, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel7 ----
      jLabel7.setText("proxyPort");
      contentPane.add(jLabel7, new GridBagConstraints(2, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- proxyHost ----
      proxyHost.setMinimumSize(new Dimension(250, 20));
      proxyHost.setPreferredSize(new Dimension(250, 20));
      contentPane.add(proxyHost, new GridBagConstraints(1, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- proxyPort ----
      proxyPort.setPreferredSize(new Dimension(50, 20));
      contentPane.add(proxyPort, new GridBagConstraints(3, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- contactPrefix ----
      contactPrefix.setPreferredSize(new Dimension(150, 20));
      contentPane.add(contactPrefix, new GridBagConstraints(1, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel8 ----
      jLabel8.setText("contactPrefix");
      contentPane.add(jLabel8, new GridBagConstraints(0, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- defaultTech ----
      defaultTech.setMinimumSize(new Dimension(250, 20));
      defaultTech.setPreferredSize(new Dimension(250, 20));
      contentPane.add(defaultTech, new GridBagConstraints(1, 6, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- defaultNS ----
      defaultNS.setMinimumSize(new Dimension(250, 20));
      defaultNS.setPreferredSize(new Dimension(250, 20));
      contentPane.add(defaultNS, new GridBagConstraints(1, 7, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel9 ----
      jLabel9.setText("defaultTech");
      contentPane.add(jLabel9, new GridBagConstraints(0, 6, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel10 ----
      jLabel10.setText("defaultNS");
      contentPane.add(jLabel10, new GridBagConstraints(0, 7, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel11 ----
      jLabel11.setFont(new Font(Font.DIALOG, Font.PLAIN, 10));
      jLabel11.setText("(es.: TECH1;TECH2;TECH3)");
      contentPane.add(jLabel11, new GridBagConstraints(2, 6, 2, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- jLabel12 ----
      jLabel12.setFont(new Font(Font.DIALOG, Font.PLAIN, 10));
      jLabel12.setText("(es.: dns1.example.it;dns2.example.it)");
      contentPane.add(jLabel12, new GridBagConstraints(2, 7, 2, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblDNSSEC ----
      lblDNSSEC.setText("DNSSEC");
      contentPane.add(lblDNSSEC, new GridBagConstraints(0, 13, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- chkDNSSEC ----
      chkDNSSEC.setText("Abilita supporto a DNSSEC");
      contentPane.add(chkDNSSEC, new GridBagConstraints(1, 13, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.BOTH,
          new Insets(0, 0, 0, 0), 0, 0));
      pack();
      setLocationRelativeTo(getOwner());
  }// </editor-fold>//GEN-END:initComponents

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_saveButtonActionPerformed
    saveParameters();
  }//GEN-LAST:event_saveButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_cancelButtonActionPerformed
    this.setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void btnChangePwdActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_btnChangePwdActionPerformed
    boolean passwordOk = false;
    while (!passwordOk)
    {
      String newPassword = JOptionPane.showInputDialog(null, "Enter new Password: ", "Change password at Registry", 1);

      if (newPassword == null)
      {
        break;
      }
      else if (newPassword.length() == 0)
      {
        JOptionPane.showMessageDialog(this, "The New Password cannot be an empty string.", "Password cannot be empty", JOptionPane.ERROR_MESSAGE);
      }
      else if (EPPparams.getParameter("EppClient.defaultPassword").equals(newPassword))
      {
        JOptionPane.showMessageDialog(this, "The New Password cannot be the same as the Old Password.", "New Password = Old Password", JOptionPane.ERROR_MESSAGE);
      }
      else
      {
        try
        {
          // sets the serverURI
          URI serverURI = new URI(EPPparams.getParameter("EppClient.serverURI"));
          // creates a new client
          Client client = new Client(serverURI.toString());

          // creates a login command with a valid account
          CustomLogin login = new CustomLogin(EPPparams.getParameter("EppClient.defaultUser"),
                  EPPparams.getParameter("EppClient.defaultPassword"));

          login.setNewPW(newPassword);

          // send the login command
          //System.out.println("CLIENT: "+ login.toString() + "\n");
          System.out.println("CLIENT: *LOGIN w/CHANGE PWD COMMAND OMITTED*\n");
          HttpBaseResponse response = client.sendCommand(login);
          System.out.println("SERVER: " + response.toString());

          // send the logout command with verbose interaction
          Logout logout = new Logout();
          System.out.println("CLIENT: " + logout.toString() + "\n");
          response = client.sendCommand(logout);
          System.out.println("SERVER: " + response.toString());

          defaultPassword.setText(newPassword);
          EPPparams.setParameter("EppClient.defaultPassword", defaultPassword.getText());

          JOptionPane.showMessageDialog(this, "Password successfully changed at the Registry.", "Password changed", JOptionPane.INFORMATION_MESSAGE);
          passwordOk = true;
        }
        catch (NullPointerException v)
        {
        }
        catch (URISyntaxException v)
        {
        }
        catch (XmlException v)
        {
        }
        catch (IOException v)
        {
        }
      }
    }

  }//GEN-LAST:event_btnChangePwdActionPerformed

  private void saveCloseButtonActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_saveCloseButtonActionPerformed
    saveParameters();
    this.setVisible(false);
  }//GEN-LAST:event_saveCloseButtonActionPerformed

  private void dbengineActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_dbengineActionPerformed
    setVisibleOnDbEngine();
    //isKillRequired = true;
  }//GEN-LAST:event_dbengineActionPerformed

  private void emptyDbActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_emptyDbActionPerformed
    dropTables();
  }//GEN-LAST:event_emptyDbActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables

  private JLabel jLabel1;
  private JTextField defaultUser;
  private JTextField defaultPassword;
  private JLabel jLabel2;
  private JTextField serverURI;
  private JLabel jLabel3;
  private JButton saveButton;
  private JButton cancelButton;
  private JButton btnChangePwd;
  private JButton saveCloseButton;
  private JTextField dbhost;
  private JLabel lblDbHostname;
  private JLabel jLabel5;
  private JComboBox<String> dbengine;
  private JTextField dbname;
  private JLabel lblDbName;
  private JTextField dbuid;
  private JTextField dbpwd;
  private JLabel lblDbUid;
  private JLabel lblDbPwd;
  private JTextField refreshInterval;
  private JLabel jLabel4;
  private JButton emptyDb;
  private JLabel jLabel6;
  private JLabel jLabel7;
  private JTextField proxyHost;
  private JTextField proxyPort;
  private JTextField contactPrefix;
  private JLabel jLabel8;
  private JTextField defaultTech;
  private JTextField defaultNS;
  private JLabel jLabel9;
  private JLabel jLabel10;
  private JLabel jLabel11;
  private JLabel jLabel12;
  private JLabel lblDNSSEC;
  private JCheckBox chkDNSSEC;
  // End of variables declaration//GEN-END:variables


  public void setEPPEnablement(boolean EPPstatus)
  {
    //btnChangePwd.setVisible(EPPstatus);
  }

  private void saveParameters()
  {
    EPPparams.setParameter("EppClient.defaultUser", defaultUser.getText());
    EPPparams.setParameter("EppClient.defaultPassword", defaultPassword.getText());

    if (serverURI.getText().contains("https://epp-acc1.nic.it") || serverURI.getText().contains("https://epp-acc2.nic.it"))
    {
      JOptionPane.showMessageDialog(this, "Please DONT'T enter accreditation test server here!\n\nTo proceed with the .it Registry Accreditation test go to the TEST section.\n\nAs the accreditation procedure requires several operations to be executed in sequence\nentering here an accreditation server hostname will cause the test to fail.", "ACCREDITATION SERVER FOUND", JOptionPane.INFORMATION_MESSAGE);
      serverURI.setText(EPPparams.getParameter("EppClient.serverURI"));
    }
    else
    {
      EPPparams.setParameter("EppClient.serverURI", serverURI.getText());
    }

    EPPparams.setParameter("EppClient.proxyHost", proxyHost.getText());

    try
    {
      EPPparams.setParameter("EppClient.proxyPort", Integer.toString(Integer.parseInt(proxyPort.getText())));
    }
    catch (Exception ex)
    {
      //do nothing... don't save this parameter!
      proxyPort.setText(EPPparams.getParameter("EppClient.proxyPort"));
    }

    EPPparams.setParameter("EppClient.contactPrefix", contactPrefix.getText());
    EPPparams.setParameter("EppClient.defaultTech", defaultTech.getText());
    EPPparams.setParameter("EppClient.defaultNS", defaultNS.getText());

    try
    {
      EPPparams.setParameter("EppClient.refreshInterval", Integer.toString(Integer.parseInt(refreshInterval.getText())));
    }
    catch (Exception ex)
    {
      //do nothing... don't save this parameter!
      refreshInterval.setText(EPPparams.getParameter("EppClient.refreshInterval"));
    }

    EPPparams.setParameter("EppClient.dbengine", Integer.toString(dbengine.getSelectedIndex()));
    EPPparams.setParameter("EppClient.dbname", dbname.getText());
    EPPparams.setParameter("EppClient.dbhost", dbhost.getText());
    EPPparams.setParameter("EppClient.dbuid", dbuid.getText());
    EPPparams.setParameter("EppClient.dbpwd", dbpwd.getText());
    EPPparams.setParameter("EppClient.implement.DNSSEC", Boolean.toString(chkDNSSEC.isSelected()));

    switch (dbengine.getSelectedIndex())
    { //0: derby, 1: mysql/mariadb, 2: postgresql
      case 0:
        EPPparams.setParameter("EppClient.dburl", "jdbc:derby:");
        EPPparams.setParameter("EppClient.dbuid", "eppclient");
        EPPparams.setParameter("EppClient.dbpwd", "clientepp");
        break;
      case 1:
        EPPparams.setParameter("EppClient.dburl", "jdbc:mariadb://" + dbhost.getText() + "/" + dbname.getText());
        break;
      case 2:
        EPPparams.setParameter("EppClient.dburl", "jdbc:postgresql://" + dbhost.getText() + "/" + dbname.getText());
      default:
        break;
    }

    if (isKillRequired)
      killOnClose = true;

  }

  private void dropTables()
  {
    killOnClose = true;
    mainFrame.messagesDao.disconnect();
    mainFrame.messagesDao.connect();
    mainFrame.messagesDao.dropTables();
    mainFrame.messagesDao.disconnect();

    mainFrame.contactsDao.disconnect();
    mainFrame.contactsDao.connect();
    mainFrame.contactsDao.dropTables();
    mainFrame.contactsDao.disconnect();

    mainFrame.domainsDao.disconnect();
    mainFrame.domainsDao.connect();
    mainFrame.domainsDao.dropTables();
    mainFrame.domainsDao.disconnect();
  }

  private void setVisibleOnDbEngine()
  {
    switch (dbengine.getSelectedIndex())
    { //0: derby, 1: mysql/mariadb, 2: postgresql
      case 0:
        dbhost.setEditable(false);
        dbname.setEditable(false);
        dbuid.setEditable(false);
        dbpwd.setEditable(false);
        break;
      case 1:
      case 2:
        dbhost.setEditable(true);
        dbname.setEditable(true);
        dbuid.setEditable(true);
        dbpwd.setEditable(true);
        break;
      default:
        break;
    }
  }

  @Override
  public void setVisible(boolean b)
  {
    super.setVisible(b);
    if (b)
    {
      defaultUser.setText(EPPparams.getParameter("EppClient.defaultUser"));
      defaultPassword.setText(EPPparams.getParameter("EppClient.defaultPassword"));
      serverURI.setText(EPPparams.getParameter("EppClient.serverURI"));
      proxyHost.setText(EPPparams.getParameter("EppClient.proxyHost"));
      proxyPort.setText(EPPparams.getParameter("EppClient.proxyPort"));
      contactPrefix.setText(EPPparams.getParameter("EppClient.contactPrefix"));
      defaultTech.setText(EPPparams.getParameter("EppClient.defaultTech"));
      defaultNS.setText(EPPparams.getParameter("EppClient.defaultNS"));
      refreshInterval.setText(EPPparams.getParameter("EppClient.refreshInterval"));
      dbengine.setSelectedIndex(Integer.parseInt(EPPparams.getParameter("EppClient.dbengine")));
      dbname.setText(EPPparams.getParameter("EppClient.dbname"));
      dbhost.setText(EPPparams.getParameter("EppClient.dbhost"));
      dbuid.setText(EPPparams.getParameter("EppClient.dbuid"));
      dbpwd.setText(EPPparams.getParameter("EppClient.dbpwd"));
      chkDNSSEC.setSelected(Boolean.parseBoolean(EPPparams.getParameter("EppClient.implement.DNSSEC")));
      setVisibleOnDbEngine();
    }
    else
    {
      if (killOnClose)
      {
        mainFrame.windowClosing(new WindowEvent(this, 0));
      }
    }
  }

  public void windowActivated(WindowEvent e)
  {
  }

  public void windowOpened(WindowEvent e)
  {
  }

  public void windowClosed(WindowEvent e)
  {
  }

  public void windowDeactivated(WindowEvent e)
  {
  }

  public void windowDeiconified(WindowEvent e)
  {
  }

  public void windowIconified(WindowEvent e)
  {
  }

  public void windowClosing(WindowEvent e)
  {
    if (killOnClose)
    {
      mainFrame.windowClosing(e);
    }
  }
}
