/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.contacts;

import javax.swing.*;
import java.awt.*;

public class AddressPanel2 extends JPanel
{

  /**
   * Creates new form AddressPanel
   */
  public AddressPanel2()
  {
    initComponents();
    address = new Address();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

  private void initComponents() {
      lblAddress1 = new JLabel();
      txtStreet = new JTextField();
      lblCity = new JLabel();
      txtCity = new JTextField();
      txtStateOrProvince = new JTextField();
      txtPostalCode = new JTextField();
      lblState = new JLabel();
      lblPostalCode = new JLabel();
      lblLastName = new JLabel();
      txtName = new JTextField();
      lblFirstName = new JLabel();
      txtOrg = new JTextField();
      lblPhone = new JLabel();
      txtVoice = new JTextField();
      lblEmail = new JLabel();
      txtEmail = new JTextField();
      lblCountry = new JLabel();
      txtCountryCode = new JTextField();
      txtRegCode = new JTextField();
      lblCountry1 = new JLabel();
      txtNationalityCode = new JTextField();
      lblCountry2 = new JLabel();
      lblCountry3 = new JLabel();
      txtIsRegistrant = new JCheckBox();
      lblPhone1 = new JLabel();
      txtFax = new JTextField();
      lblLastName1 = new JLabel();
      txtContactId = new JTextField();
      txtAutoContactId = new JCheckBox();
      txtEntityType = new JComboBox<>();
      txtConsentForPublishing = new JCheckBox();
      jScrollPane1 = new JScrollPane();
      txtStatus = new JList<>();

      //======== this ========
      setLayout(new GridBagLayout());

      //---- lblAddress1 ----
      lblAddress1.setText("street");
      add(lblAddress1, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtStreet ----
      txtStreet.setPreferredSize(new Dimension(200, 20));
      add(txtStreet, new GridBagConstraints(1, 3, 3, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblCity ----
      lblCity.setText("city");
      add(lblCity, new GridBagConstraints(0, 4, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtCity ----
      txtCity.setMinimumSize(new Dimension(150, 20));
      txtCity.setPreferredSize(new Dimension(150, 20));
      add(txtCity, new GridBagConstraints(1, 4, 3, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtStateOrProvince ----
      txtStateOrProvince.setMinimumSize(new Dimension(30, 21));
      txtStateOrProvince.setPreferredSize(new Dimension(30, 20));
      add(txtStateOrProvince, new GridBagConstraints(1, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtPostalCode ----
      txtPostalCode.setMinimumSize(new Dimension(80, 21));
      txtPostalCode.setPreferredSize(new Dimension(50, 20));
      add(txtPostalCode, new GridBagConstraints(5, 4, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblState ----
      lblState.setText("stateOrProvince");
      add(lblState, new GridBagConstraints(0, 5, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblPostalCode ----
      lblPostalCode.setText("postalCode");
      add(lblPostalCode, new GridBagConstraints(4, 4, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblLastName ----
      lblLastName.setText("name");
      add(lblLastName, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtName ----
      txtName.setMinimumSize(new Dimension(100, 21));
      txtName.setPreferredSize(new Dimension(200, 20));
      add(txtName, new GridBagConstraints(1, 1, 3, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblFirstName ----
      lblFirstName.setText("org");
      add(lblFirstName, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtOrg ----
      txtOrg.setMinimumSize(new Dimension(80, 21));
      txtOrg.setPreferredSize(new Dimension(200, 20));
      add(txtOrg, new GridBagConstraints(1, 2, 3, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblPhone ----
      lblPhone.setText("voice");
      add(lblPhone, new GridBagConstraints(0, 8, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtVoice ----
      txtVoice.setMinimumSize(new Dimension(100, 20));
      txtVoice.setPreferredSize(new Dimension(150, 20));
      add(txtVoice, new GridBagConstraints(1, 8, 2, 1, 0.0, 0.0,
          GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblEmail ----
      lblEmail.setText("email");
      add(lblEmail, new GridBagConstraints(0, 10, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtEmail ----
      txtEmail.setMinimumSize(new Dimension(80, 20));
      txtEmail.setPreferredSize(new Dimension(150, 20));
      add(txtEmail, new GridBagConstraints(1, 10, 2, 1, 0.0, 0.0,
          GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblCountry ----
      lblCountry.setText("countryCode");
      add(lblCountry, new GridBagConstraints(0, 6, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtCountryCode ----
      txtCountryCode.setPreferredSize(new Dimension(30, 20));
      add(txtCountryCode, new GridBagConstraints(1, 6, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtRegCode ----
      txtRegCode.setPreferredSize(new Dimension(150, 20));
      add(txtRegCode, new GridBagConstraints(1, 14, 2, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblCountry1 ----
      lblCountry1.setText("regCode");
      add(lblCountry1, new GridBagConstraints(0, 14, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtNationalityCode ----
      txtNationalityCode.setPreferredSize(new Dimension(30, 20));
      add(txtNationalityCode, new GridBagConstraints(1, 12, 2, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblCountry2 ----
      lblCountry2.setText("nationalityCode");
      add(lblCountry2, new GridBagConstraints(0, 12, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblCountry3 ----
      lblCountry3.setText("entityType");
      add(lblCountry3, new GridBagConstraints(0, 13, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtIsRegistrant ----
      txtIsRegistrant.setText("isRegistrant");
      txtIsRegistrant.addActionListener(e -> txtIsRegistrantActionPerformed(e));
      add(txtIsRegistrant, new GridBagConstraints(0, 11, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- lblPhone1 ----
      lblPhone1.setFont(new Font("Tahoma", Font.ITALIC, 11));
      lblPhone1.setText("fax");
      add(lblPhone1, new GridBagConstraints(0, 9, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtFax ----
      txtFax.setMinimumSize(new Dimension(80, 20));
      txtFax.setPreferredSize(new Dimension(150, 20));
      add(txtFax, new GridBagConstraints(1, 9, 2, 1, 0.0, 0.0,
          GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- lblLastName1 ----
      lblLastName1.setText("contactID");
      add(lblLastName1, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtContactId ----
      txtContactId.setMinimumSize(new Dimension(150, 20));
      txtContactId.setPreferredSize(new Dimension(150, 20));
      add(txtContactId, new GridBagConstraints(1, 0, 2, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtAutoContactId ----
      txtAutoContactId.setText("Assegnazione Automatica");
      txtAutoContactId.addActionListener(e -> txtAutoContactIdActionPerformed(e));
      add(txtAutoContactId, new GridBagConstraints(3, 0, 2, 1, 0.0, 0.0,
          GridBagConstraints.EAST, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //---- txtEntityType ----
      txtEntityType.setModel(new DefaultComboBoxModel<>(new String[] {
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7"
      }));
      add(txtEntityType, new GridBagConstraints(1, 13, 1, 1, 0.0, 0.0,
          GridBagConstraints.WEST, GridBagConstraints.NONE,
          new Insets(5, 5, 5, 5), 0, 0));

      //---- txtConsentForPublishing ----
      txtConsentForPublishing.setText("consentForPublishing");
      add(txtConsentForPublishing, new GridBagConstraints(5, 11, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));

      //======== jScrollPane1 ========
      {

          //---- txtStatus ----
          txtStatus.setModel(new AbstractListModel<String>() {
              String[] values = {
                  "clientDeleteProhibited",
                  "clientTransferProhibited",
                  "clientUpdateProhibited"
              };
              @Override
              public int getSize() { return values.length; }
              @Override
              public String getElementAt(int i) { return values[i]; }
          });
          txtStatus.setMaximumSize(new Dimension(150, 25));
          txtStatus.setMinimumSize(new Dimension(150, 25));
          txtStatus.setPreferredSize(new Dimension(150, 25));
          txtStatus.setVisibleRowCount(4);
          jScrollPane1.setViewportView(txtStatus);
      }
      add(jScrollPane1, new GridBagConstraints(5, 0, 1, 3, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.NONE,
          new Insets(0, 0, 0, 0), 0, 0));
  }// </editor-fold>//GEN-END:initComponents

  private void txtIsRegistrantActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_txtIsRegistrantActionPerformed
    // TODO add your handling code here:
    if (address.getIsRegistrant())
    {
      if (!txtIsRegistrant.isSelected())
      {
        JOptionPane.showMessageDialog(this, "Registrant status cannot be reverted once applied to the Registry", "Switch to non-Registrant contact failed", JOptionPane.INFORMATION_MESSAGE);
        txtIsRegistrant.setSelected(true);
      }
      else
      {
        setEditable(isEditable);
      }
    }
    else
    {
      address.isIsRegistrantChanged(true);
      setEditable(isEditable);
    }

  }//GEN-LAST:event_txtIsRegistrantActionPerformed

  private void txtAutoContactIdActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_txtAutoContactIdActionPerformed
    // TODO add your handling code here:
    setEditable(isEditable);
  }//GEN-LAST:event_txtAutoContactIdActionPerformed

  void setContactName(String name)
  {
    address.setContactName(name);
    txtName.setText(name);
  }

  String getContactName()
  {
    String name = txtName.getText();
    address.setContactName(name);
    return name;
  }

  void setOrg(String org)
  {
    address.setOrg(org);
    txtOrg.setText(org);

  }

  String getOrg()
  {
    String org = txtOrg.getText();
    address.setOrg(org);
    return org;
  }

  void setStreet(String street)
  {
    address.setStreet(street);
    txtStreet.setText(street);
  }

  String getStreet()
  {
    String street = txtStreet.getText();
    address.setStreet(street);
    return street;
  }

  void setCity(String city)
  {
    address.setCity(city);
    txtCity.setText(city);
  }

  String getCity()
  {
    String city = txtCity.getText();
    address.setCity(city);
    return city;
  }

  void setStateOrProvince(String stateOrProvince)
  {
    address.setStateOrProvince(stateOrProvince);
    txtStateOrProvince.setText(stateOrProvince);
  }

  String getStateOrProvince()
  {
    String stateOrProvince = txtStateOrProvince.getText();
    address.setStateOrProvince(stateOrProvince);
    return stateOrProvince;
  }

  void setPostalCode(String postalCode)
  {
    address.setPostalCode(postalCode);
    txtPostalCode.setText(postalCode);
  }

  String getPostalCode()
  {
    String postalCode = txtPostalCode.getText();
    address.setPostalCode(postalCode);
    return postalCode;
  }

  void setCountryCode(String countryCode)
  {
    address.setCountryCode(countryCode);
    txtCountryCode.setText(countryCode);
  }

  String getCountryCode()
  {
    String countryCode = txtCountryCode.getText();
    address.setCountryCode(countryCode);
    return countryCode;
  }

  void setVoice(String voice)
  {
    address.setVoice(voice);
    txtVoice.setText(voice);
  }

  String getVoice()
  {
    String voice = txtVoice.getText();
    address.setVoice(voice);
    return voice;
  }

  void setFax(String fax)
  {
    address.setFax(fax);
    txtFax.setText(fax);
  }

  String getFax()
  {
    String fax = txtFax.getText();
    address.setFax(fax);
    return fax;
  }

  void setEmail(String email)
  {
    address.setEmail(email);
    txtEmail.setText(email);
  }

  String getEmail()
  {
    String email = txtEmail.getText();
    address.setEmail(email);
    return email;
  }

  void setConsentForPublishing(Boolean consentForPublishing)
  {
    address.setConsentForPublishing(consentForPublishing);
    txtConsentForPublishing.setSelected(consentForPublishing);
  }

  Boolean getConsentForPublishing()
  {
    Boolean consentForPublishing = txtConsentForPublishing.isSelected();
    address.setConsentForPublishing(consentForPublishing);
    return consentForPublishing;
  }

  void setIsRegistrant(Boolean isRegistrant)
  {
    address.setIsRegistrant(isRegistrant);
    txtIsRegistrant.setSelected(isRegistrant);
  }

  Boolean getIsRegistrant()
  {
    Boolean isRegistrant = txtIsRegistrant.isSelected();
    address.setIsRegistrant(isRegistrant);
    return isRegistrant;
  }

  void setNationalityCode(String nationalityCode)
  {
    address.setNationalityCode(nationalityCode);
    txtNationalityCode.setText(nationalityCode);
  }

  String getNationalityCode()
  {
    String nationalityCode = txtNationalityCode.getText();
    address.setNationalityCode(nationalityCode);
    return nationalityCode;
  }

  void setEntityType(int entityType)
  {
    address.setEntityType(entityType);
    txtEntityType.setSelectedIndex(entityType - 1);
  }

  int getEntityType()
  {
    int entityType = txtEntityType.getSelectedIndex() + 1;
    address.setEntityType(entityType);
    return entityType;
  }

  void setRegCode(String regCode)
  {
    address.setRegCode(regCode);
    txtRegCode.setText(regCode);
  }

  String getRegCode()
  {
    String regCode = txtRegCode.getText();
    address.setRegCode(regCode);
    return regCode;
  }

  void setContactId(String contactId)
  {
    address.setContactId(contactId);
    txtContactId.setText(contactId);
  }

  String getContactId()
  {
    String contactId = txtContactId.getText();
    address.setContactId(contactId);
    return contactId;
  }

  void setAutoContactId(Boolean autoContactId)
  {
    address.setAutoContactId(autoContactId);
    txtAutoContactId.setSelected(autoContactId);
  }

  Boolean getAutoContactId()
  {
    Boolean autoContactId = txtAutoContactId.isSelected();
    address.setAutoContactId(autoContactId);
    return autoContactId;
  }

  void setIsNewContact(Boolean isNewContact)
  {
    address.setIsNewContact(isNewContact);
  }

  Boolean getIsNewContact()
  {
    return address.getIsNewContact();
  }

  void setOldStatus(int[] oldStatus)
  {
    address.setOldStatus(oldStatus);
  }

  int[] getOldStatus()
  {
    int[] oldStatus = address.getOldStatus();
    return oldStatus;
  }

  void setNewStatus(int[] newStatus)
  {
    address.setNewStatus(newStatus);
    if (newStatus != null)
    {
      txtStatus.setSelectedIndices(newStatus);
    }
    else
    {
      txtStatus.clearSelection();
    }
  }

  int[] getNewStatus()
  {
    int[] newStatus = txtStatus.getSelectedIndices();
    address.setNewStatus(newStatus);
    return newStatus;
  }

  public void setAddress(Address address)
  {
    if (address != null)
    {
      setContactName(address.getContactName());
      setOrg(address.getOrg());
      setStreet(address.getStreet());
      setCity(address.getCity());
      setStateOrProvince(address.getStateOrProvince());
      setPostalCode(address.getPostalCode());
      setCountryCode(address.getCountryCode());

      setVoice(address.getVoice());
      setFax(address.getFax());
      setEmail(address.getEmail());

      setConsentForPublishing(address.getConsentForPublishing());
      setIsRegistrant(address.getIsRegistrant());
      setNationalityCode(address.getNationalityCode());
      setEntityType(address.getEntityType());
      setRegCode(address.getRegCode());

      setContactId(address.getContactId());
      setAutoContactId(address.getAutoContactId());

      setOldStatus(address.getOldStatus());
      setNewStatus(address.getNewStatus());
    }
  }

  public Address getAddress()
  {
    getContactName();
    getOrg();
    getStreet();
    getCity();
    getStateOrProvince();
    getPostalCode();
    getCountryCode();
    getVoice();
    getFax();
    getEmail();
    getConsentForPublishing();
    getIsRegistrant();
    getNationalityCode();
    getEntityType();
    getRegCode();
    getContactId();
    getAutoContactId();
    getNewStatus();
    getOldStatus();
    return address;
  }


  public void clear()
  {
    txtContactId.setText(null);
    txtAutoContactId.setSelected(true);
    txtName.setText(null);
    txtOrg.setText(null);
    txtVoice.setText(null);
    txtFax.setText(null);
    txtEmail.setText(null);
    txtStreet.setText(null);
    txtCity.setText(null);
    txtStateOrProvince.setText(null);
    txtPostalCode.setText(null);
    txtCountryCode.setText(null);
    address = new Address();

    txtConsentForPublishing.setSelected(false);

    txtIsRegistrant.setSelected(false);
    txtNationalityCode.setText(null);
    txtEntityType.setSelectedIndex(0);
    txtRegCode.setText(null);
    txtStatus.clearSelection();
  }

  public void setEditable(boolean bEditable)
  {
    txtAutoContactId.setVisible(bEditable && (contactId.equals("")) && getIsNewContact());
    txtAutoContactId.setEnabled(bEditable && (contactId.equals("")) && getIsNewContact());
    txtContactId.setEditable(bEditable && !txtAutoContactId.isSelected() && (contactId.equals("")) && getIsNewContact());

    txtStatus.setEnabled(bEditable);

    txtName.setEditable(bEditable && !address.getIsRegistrant());
    txtOrg.setEditable(bEditable && !address.getIsRegistrant());
    txtStreet.setEditable(bEditable);

    txtCity.setEditable(bEditable);
    txtStateOrProvince.setEditable(bEditable);
    txtPostalCode.setEditable(bEditable);
    txtCountryCode.setEditable(bEditable);
    txtVoice.setEditable(bEditable);
    txtFax.setEditable(bEditable);
    txtEmail.setEditable(bEditable);

    txtConsentForPublishing.setEnabled(bEditable);

    txtIsRegistrant.setEnabled(bEditable && !address.getIsRegistrant());

    txtNationalityCode.setEditable(bEditable && txtIsRegistrant.isSelected() && !address.getIsRegistrant());
    txtEntityType.setEnabled(bEditable && txtIsRegistrant.isSelected() && !address.getIsRegistrant());
    txtRegCode.setEditable(bEditable && txtIsRegistrant.isSelected() && !address.getIsRegistrant());

    isEditable = bEditable;
  }

  public boolean isEditable()
  {
    return isEditable;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables

  private JLabel lblAddress1;
  private JTextField txtStreet;
  private JLabel lblCity;
  private JTextField txtCity;
  private JTextField txtStateOrProvince;
  private JTextField txtPostalCode;
  private JLabel lblState;
  private JLabel lblPostalCode;
  private JLabel lblLastName;
  private JTextField txtName;
  private JLabel lblFirstName;
  private JTextField txtOrg;
  private JLabel lblPhone;
  private JTextField txtVoice;
  private JLabel lblEmail;
  private JTextField txtEmail;
  private JLabel lblCountry;
  private JTextField txtCountryCode;
  private JTextField txtRegCode;
  private JLabel lblCountry1;
  private JTextField txtNationalityCode;
  private JLabel lblCountry2;
  private JLabel lblCountry3;
  private JCheckBox txtIsRegistrant;
  private JLabel lblPhone1;
  private JTextField txtFax;
  private JLabel lblLastName1;
  private JTextField txtContactId;
  private JCheckBox txtAutoContactId;
  private JComboBox<String> txtEntityType;
  private JCheckBox txtConsentForPublishing;
  private JScrollPane jScrollPane1;
  private JList<String> txtStatus;
  // End of variables declaration//GEN-END:variables
  String contactId = "";
  boolean isEditable;
  Address address;

}
