/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.contacts;

import EPPClient.db.contactsDao;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.util.List;

public class AddressFrame
        extends JFrame
        implements ActionListener, ListSelectionListener
{

  /**
   * Creates new form AddressFrame
   */
  public AddressFrame()
  {
    initComponents();
    loadFrameIcon();
    windowAdapter = new WindowCloser();
    this.addWindowListener(windowAdapter);
    db = new contactsDao();
    db.connect();
    addressActionPanel.addActionListener(this);
    addressPanel.setEditable(false);
    List<ListEntry> entries = db.getListEntries();
    addressListPanel.addListEntries(entries);
    addressListPanel.addListSelectionListener(this);
  }


  /**
   * Load our own "address book" icon into our frame window.
   */
  private void loadFrameIcon()
  {
    URL imgUrl = null;
    ImageIcon imgIcon = null;

    imgUrl = AddressFrame.class.getResource("../resources/addressbook32.gif");
    imgIcon = new ImageIcon(imgUrl);
    Image img = imgIcon.getImage();
    this.setIconImage(img);

  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    addressActionPanel = new AddressActionPanel();
    addressPanel = new AddressPanel();
    addressListPanel = new AddressListPanel();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setTitle("Address Book Demo");
    getContentPane().add(addressActionPanel, BorderLayout.SOUTH);

    getContentPane().add(addressPanel, BorderLayout.CENTER);

    getContentPane().add(addressListPanel, BorderLayout.WEST);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  private void cancelAddress()
  {
    addressPanel.clear();
    addressPanel.setEditable(false);
    ListEntry entry = addressListPanel.getSelectedListEntry();
    if (entry != null)
    {
      String contactId = entry.getContactId();
      Address address = db.getAddress(contactId);
      addressPanel.setAddress(address);
    }


  }

  private void newAddress()
  {
    addressPanel.clear();
    addressPanel.setEditable(true);

  }

  private void deleteAddress()
  {
    String contactId = addressPanel.getContactId();
    if (contactId.equals(""))
    {
      db.deleteRecord(contactId);
      int selectedIndex = addressListPanel.deleteSelectedEntry();
      if (selectedIndex >= 0)
      {
        selectedIndex = addressListPanel.setSelectedIndex(selectedIndex);
        ListEntry entry = addressListPanel.getSelectedListEntry();
        if (entry != null)
        {
          contactId = entry.getContactId();
          Address address = db.getAddress(contactId);
          addressPanel.setAddress(address);
        }
        else
        {
          addressPanel.clear();
        }
      }
    }
    else
    {
      addressPanel.clear();
    }
    addressPanel.setEditable(false);


  }

  private void editAddress()
  {
    int selected = addressListPanel.getSelectedIndex();
    if (selected >= 0)
    {
      addressPanel.setEditable(true);
    }

  }

  private void saveAddress()
  {
    if (addressPanel.isEditable())
    {
      Address address = addressPanel.getAddress();
      String contactId = address.getContactId();
      String name = address.getContactName();
      if (contactId.equals(""))
      {
        contactId = db.saveRecord(address);
        address.setContactId(contactId);

        ListEntry entry = new ListEntry(name, contactId);
        addressListPanel.addListEntry(entry);

      }
      else
      {
        db.editRecord(address);
        ListEntry entry = addressListPanel.getSelectedListEntry();
        entry.setContactName(name);
        addressListPanel.repaint();
      }
      addressPanel.setEditable(false);
    }
  }


  public void actionPerformed(ActionEvent e)
  {
    String actionCommand = e.getActionCommand();
    if (actionCommand.equalsIgnoreCase("CANCEL_ADDRESS"))
    {
      cancelAddress();
    }
    else if (actionCommand.equalsIgnoreCase("NEW_ADDRESS"))
    {
      newAddress();
    }
    else if (actionCommand.equalsIgnoreCase("DELETE_ADDRESS"))
    {
      deleteAddress();
    }
    else if (actionCommand.equalsIgnoreCase("EDIT_ADDRESS"))
    {
      editAddress();
    }
    else if (actionCommand.equalsIgnoreCase("SAVE_ADDRESS"))
    {
      saveAddress();
    }
  }


  public void valueChanged(ListSelectionEvent e)
  {
    if (e.getValueIsAdjusting())
    {
      return;
    }
    JList entryList = (JList) e.getSource();
    selectedEntry = entryList.getSelectedIndex();
    ListEntry entry = (ListEntry) entryList.getSelectedValue();
    if (entry != null)
    {
      String contactId = entry.getContactId();
      Address address = db.getAddress(contactId);
      addressPanel.setAddress(address);
    }
    else
    {
      addressPanel.clear();
    }
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private AddressActionPanel addressActionPanel;
  private AddressListPanel addressListPanel;
  private AddressPanel addressPanel;
  // End of variables declaration//GEN-END:variables

  private int selectedEntry = -1;
  private contactsDao db;
  private WindowAdapter windowAdapter;

  class WindowCloser extends WindowAdapter
  {
    public void windowClosing(WindowEvent e)
    {
      db.disconnect();
    }

  }
}
