/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.contacts;

import javax.swing.*;
import javax.swing.event.EventListenerList;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddressActionPanel extends JPanel
{

  /**
   * Creates new form AddressActionPanel
   */
  public AddressActionPanel()
  {
    initComponents();
    listeners = new EventListenerList();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    btnNewAddress = new JButton();
    btnCloneAddress = new JButton();
    btnDeleteAddress = new JButton();
    btnEditAddress = new JButton();
    btnSaveAddress = new JButton();
    btnSyncInfo = new JButton();
    btnCancelAddress = new JButton();
    btnCheckContact = new JButton();
    btnInfoContact = new JButton();

    //======== this ========
    setLayout(new GridLayout());

    //---- btnNewAddress ----
    btnNewAddress.setText("New");
    btnNewAddress.setActionCommand("NEW_ADDRESS");
    btnNewAddress.addActionListener(e -> newAddressActionPerformed(e));
    add(btnNewAddress);

    //---- btnCloneAddress ----
    btnCloneAddress.setText("Clone");
    btnCloneAddress.setActionCommand("CLONE_ADDRESS");
    btnCloneAddress.addActionListener(e -> btnCloneAddressActionPerformed(e));
    add(btnCloneAddress);

    //---- btnDeleteAddress ----
    btnDeleteAddress.setText("Delete");
    btnDeleteAddress.setActionCommand("DELETE_ADDRESS");
    btnDeleteAddress.addActionListener(e -> deleteAddressActionPerformed(e));
    add(btnDeleteAddress);

    //---- btnEditAddress ----
    btnEditAddress.setText("Edit");
    btnEditAddress.setActionCommand("EDIT_ADDRESS");
    btnEditAddress.addActionListener(e -> editAddressActionPerformed(e));
    add(btnEditAddress);

    //---- btnSaveAddress ----
    btnSaveAddress.setText("Save");
    btnSaveAddress.setActionCommand("SAVE_ADDRESS");
    btnSaveAddress.addActionListener(e -> saveAddressActionPerformed(e));
    add(btnSaveAddress);

    //---- btnSyncInfo ----
    btnSyncInfo.setText("Sync");
    btnSyncInfo.setActionCommand("SYNC_CONTACT");
    btnSyncInfo.setMargin(new Insets(2, 2, 2, 2));
    btnSyncInfo.addActionListener(e -> btnSyncInfobtnSyncDomainActionPerformed(e));
    add(btnSyncInfo);

    //---- btnCancelAddress ----
    btnCancelAddress.setText("Cancel");
    btnCancelAddress.setActionCommand("CANCEL_ADDRESS");
    btnCancelAddress.addActionListener(e -> cancelAddressActionPerformed(e));
    add(btnCancelAddress);

    //---- btnCheckContact ----
    btnCheckContact.setText("Check");
    btnCheckContact.setActionCommand("CHECK_CONTACT");
    btnCheckContact.addActionListener(e -> btnCheckContactActionPerformed(e));
    add(btnCheckContact);

    //---- btnInfoContact ----
    btnInfoContact.setText("Info");
    btnInfoContact.setActionCommand("INFO_CONTACT");
    btnInfoContact.addActionListener(e -> btnInfoContactActionPerformed(e));
    add(btnInfoContact);
  }// </editor-fold>//GEN-END:initComponents

  private void cancelAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_cancelAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_cancelAddressActionPerformed

  private void saveAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_saveAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_saveAddressActionPerformed

  private void editAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_editAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_editAddressActionPerformed

  private void deleteAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_deleteAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_deleteAddressActionPerformed

  private void newAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_newAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_newAddressActionPerformed

  private void btnCheckContactActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnCheckContactActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnCheckContactActionPerformed

  private void btnInfoContactActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnInfoContactActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnInfoContactActionPerformed

  private void btnSyncInfobtnSyncDomainActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnSyncInfobtnSyncDomainActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnSyncInfobtnSyncDomainActionPerformed

  private void btnCloneAddressActionPerformed(ActionEvent evt)
  {//GEN-FIRST:event_btnCloneAddressActionPerformed
    fireActionEvent(evt);
  }//GEN-LAST:event_btnCloneAddressActionPerformed

  private void fireActionEvent(ActionEvent evt)
  {
    ActionListener[] listenerList = listeners.getListeners(ActionListener.class);

    for (int i = listenerList.length - 1; i >= 0; --i)
    {
      listenerList[i].actionPerformed(evt);
    }

  }

  public void addActionListener(ActionListener listener)
  {
    listeners.add(ActionListener.class, listener);
  }

  public void removeActionListener(ActionListener listener)
  {
    if (listeners != null)
    {
      listeners.remove(ActionListener.class, listener);
    }
  }

  EventListenerList listeners;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton btnNewAddress;
  private JButton btnCloneAddress;
  private JButton btnDeleteAddress;
  private JButton btnEditAddress;
  private JButton btnSaveAddress;
  private JButton btnSyncInfo;
  private JButton btnCancelAddress;
  private JButton btnCheckContact;
  private JButton btnInfoContact;
  // End of variables declaration//GEN-END:variables

}
