/*
 * SPDX-FileCopyrightText: 2008-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.contacts;

import EPPClient.db.contactsDao;
import EPPClient.importer.ImportContact;
import EPPClient.logger;
import EPPClient.main;
import EPPClient.uplink.EPPuplink;
import it.nic.epp.client.commands.query.ContactCheck;
import it.nic.epp.client.commands.query.ContactInfo;
import it.nic.epp.client.commands.transform.ContactCreate;
import it.nic.epp.client.commands.transform.ContactDelete;
import it.nic.epp.client.commands.transform.ContactUpdate;
import it.nic.epp.client.responses.HttpBaseResponse;
import it.nic.epp.client.responses.ext.ContactInfoResponseExt;
import it.nic.epp.client.responses.resData.ContactCheckResponseResData;
import it.nic.epp.client.responses.resData.ContactInfoResponseResData;
import org.apache.xmlbeans.XmlException;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.List;

public class ContactsManagement extends JFrame implements ActionListener, ListSelectionListener
{

  private main mainFrame;

  /**
   * Creates new form ContactsManagement
   */
  public ContactsManagement(main mainFrame)
  {
    initComponents();

    windowAdapter = new WindowCloser();
    this.addWindowListener(windowAdapter);
    addressActionPanel.addActionListener(this);
    addressPanel.setEditable(false);
    addressListPanel.addListSelectionListener(this);

    this.mainFrame = mainFrame;
    this.EPPuplink = mainFrame.EPPuplink;
    this.db = mainFrame.contactsDao;

    refreshContactList();


    logger = new logger("CONTACT");
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    addressActionPanel = new AddressActionPanel();
    addressPanel = new AddressPanel();
    addressListPanel = new AddressListPanel();

    //======== this ========
    setTitle("Gestione CONTATTI");
    Container contentPane = getContentPane();

    GroupLayout contentPaneLayout = new GroupLayout(contentPane);
    contentPane.setLayout(contentPaneLayout);
    contentPaneLayout.setHorizontalGroup(
      contentPaneLayout.createParallelGroup()
        .addGroup(contentPaneLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(addressListPanel, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
          .addGroup(contentPaneLayout.createParallelGroup()
            .addGroup(contentPaneLayout.createSequentialGroup()
              .addGap(34, 34, 34)
              .addComponent(addressPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(contentPaneLayout.createSequentialGroup()
              .addGap(57, 57, 57)
              .addComponent(addressActionPanel, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
              .addGap(226, 226, 226)))
          .addContainerGap())
    );
    contentPaneLayout.setVerticalGroup(
      contentPaneLayout.createParallelGroup()
        .addGroup(contentPaneLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(contentPaneLayout.createParallelGroup()
            .addGroup(contentPaneLayout.createSequentialGroup()
              .addComponent(addressPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(addressActionPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(addressListPanel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addContainerGap())
    );
    pack();
    setLocationRelativeTo(getOwner());
  }// </editor-fold>//GEN-END:initComponents

  private void refreshContactList()
  {
    addressListPanel.deleteAllEntries();
//        db = new contactsDao();
//        db.connect();
    List<ListEntry> entries = db.getListEntries();
//        db.disconnect();
    addressListPanel.addListEntries(entries);
  }

  public void setEPPEnablement(boolean EPPstatus)
  {
    addressActionPanel.setVisible(EPPstatus);
  }

  private void cancelAddress()
  {
    addressPanel.clear();
    addressPanel.setEditable(false);
    ListEntry entry = addressListPanel.getSelectedListEntry();
    if (entry != null)
    {
      String contactId = entry.getContactId();
//            db = new contactsDao();
//            db.connect();
      Address address = db.getAddress(contactId);
//            db.disconnect();
      addressPanel.setAddress(address);
    }
  }

  private void selectAddress()
  {
    selectedContactId = addressPanel.getContactId();
  }

  private void newAddress()
  {
    addressPanel.clear();
    addressPanel.setIsNewContact(true);
    addressPanel.setEditable(true);
  }

  private void cloneAddress()
  {
    addressPanel.setIsNewContact(true);
    addressPanel.setAutoContactId(false);
    addressPanel.setEditable(true);
  }

  private void deleteAddress()
  {
    String contactId = addressPanel.getContactId();
    if (!contactId.equals(""))
    {

      try
      {
        /**
         * Delete the contact
         * The contact MUSTN'T BE LINKED with any domain name
         */
        ContactDelete contactDelete = new ContactDelete();
        contactDelete.setId(contactId);
        logger.logmessage("CLIENT: " + contactDelete.toString() + "\n");
        HttpBaseResponse response = EPPuplink.sendCommand(contactDelete);
        logger.logmessage("SERVER: " + response.toString() + "\n");

        if (response.isSuccessfully())
        {
//                    db = new contactsDao();
//                    db.connect();
          db.deleteRecord(contactId);
//                    db.disconnect();
          int selectedIndex = addressListPanel.deleteSelectedEntry();
          if (selectedIndex >= 0)
          {
            selectedIndex = addressListPanel.setSelectedIndex(selectedIndex);
            ListEntry entry = addressListPanel.getSelectedListEntry();
            if (entry != null)
            {
              contactId = entry.getContactId();
//                            db = new contactsDao();
//                            db.connect();
              Address address = db.getAddress(contactId);
//                            db.disconnect();
              addressPanel.setAddress(address);
            }
            else
            {
              addressPanel.clear();
            }
          }

        }
        else
        {
          if (JOptionPane.showConfirmDialog(this, "An error occurred while deleting contact on the Registry.\n\nDo you want to see the Registry XML response?", "Registry delete failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
          {
            JOptionPane.showMessageDialog(this, response.toString());
          }
          parseContactResult(response);
        }


      }
      catch (NullPointerException v)
      {
      }
      catch (XmlException v)
      {
      }
      catch (IOException v)
      {
      }

    }
    else
    {
      addressPanel.clear();
    }
    addressPanel.setEditable(false);


  }

  private void editAddress()
  {
    int selected = addressListPanel.getSelectedIndex();
    if (selected >= 0)
    {
      addressPanel.setEditable(true);
    }
  }

  private void saveAddress()
  {
    if (addressPanel.isEditable())
    {
      Address address = addressPanel.getAddress();
      String contactId = address.getContactId();

      if (address.getIsNewContact())
      {
        if (address.getAutoContactId())
        {
          while (true)
          {
            addressPanel.setContactId(address.getRandomContactId());
            ContactCheck contactCheck = new ContactCheck();
            contactCheck.addId(address.getContactId());
            try
            {
              HttpBaseResponse response = EPPuplink.sendCommand(contactCheck);
              logger.logmessage("SERVER: " + response.toString() + "\n");
              if (response.isSuccessfully())
              {
                ContactCheckResponseResData resData = (ContactCheckResponseResData) response.getResponseResData();
                if (resData.getChkAvail(0))
                  break;
              }
            }
            catch (NullPointerException v)
            {
            }
            catch (XmlException v)
            {
            }
            catch (IOException v)
            {
            }

          }
        }

        try
        {

          // prepare and send a Create contact command
          ContactCreate contactCreate = new ContactCreate(address.getContactId(), address.getContactName(), address.getStreet(), address.getStateOrProvince(), address.getPostalCode(), address.getCity(), address.getCountryCode(), address.getVoice(), address.getEmail(), address.getConsentForPublishing());

          contactCreate.setFax(address.getFax());
          contactCreate.setOrg(address.getOrg());
          if(!address.getSchoolCode().isEmpty())
            contactCreate.setExtSchoolCode(address.getSchoolCode());

          if(!address.getIpaCode().isEmpty() && address.getUoCode().isEmpty())
            contactCreate.setExtGovRegistrant(address.getIpaCode());

          if(!address.getIpaCode().isEmpty() && !address.getUoCode().isEmpty())
            contactCreate.setExtGovRegistrant(address.getIpaCode(), address.getUoCode());

          if (address.getIsRegistrant())
          {
            contactCreate.setExtRegistrant(address.getNationalityCode(), address.getEntityType(), address.getRegCode());
          }

          logger.logmessage("CLIENT: " + contactCreate.toString() + "\n");
          HttpBaseResponse response = EPPuplink.sendCommand(contactCreate);
          logger.logmessage("SERVER: " + response.toString() + "\n");

          if (response.isSuccessfully())
          {
//                        db = new contactsDao();
//                        db.connect();
            contactId = db.saveRecord(address);
//                        db.disconnect();
            address.setContactId(contactId);
            address.setIsNewContact(false);
            address.isIsRegistrantChanged(false);

            ListEntry entry = new ListEntry(address.getContactName(), contactId);
            addressListPanel.addListEntry(entry);
            addressListPanel.setSelectedIndex(Integer.MAX_VALUE);
            addressListPanel.repaint();
            addressPanel.setEditable(false);

          }
          else
          {
            if (JOptionPane.showConfirmDialog(this, "An error occurred while applying changes to the Registry.\n\nDo you want to see the Registry XML response?", "Registry update failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
            {
              JOptionPane.showMessageDialog(this, response.toString());
            }
          }

        }
        catch (NullPointerException v)
        {
        }
        catch (XmlException v)
        {
        }
        catch (IOException v)
        {
        }

      }
      else
      {

        try
        {
          ContactInfo contactInfo = new ContactInfo();
          contactInfo.setId(address.getContactId());
          HttpBaseResponse response = EPPuplink.sendCommand(contactInfo);
          logger.logmessage("ContactInfo PRIMA: " + response.toString() + "\n");
          ContactInfoResponseResData contactInfoResData = (ContactInfoResponseResData) response.getResponseResData();
          ContactInfoResponseExt contactInfoExt = (ContactInfoResponseExt) response.getResponseExtension();


          ContactUpdate contactUpdate = new ContactUpdate(address.getContactId());

          Boolean migratedUpdateOK = true;

          if (!contactInfoExt.isRegistrant())
          {
            if (address.isIsRegistrantChanged())
            {
              if (address.getIsRegistrant())
              {
                contactUpdate.setExtRegistrant(address.getNationalityCode(), address.getEntityType(), address.getRegCode());

              }
            }
          }
          else
          {
            Boolean updateMigrated = false;
            try
            {
              if (contactInfoExt.getEntityType() == 0)
              {
                contactUpdate.setExtEntityType(address.getEntityType());
                updateMigrated = true;
              }
            }
            catch (Exception e)
            {
              contactUpdate.setExtEntityType(address.getEntityType());
              updateMigrated = true;
            }

            try
            {
              if (contactInfoExt.getNationalityCode().length() == 0)
              {
                contactUpdate.setExtNationalityCode(address.getNationalityCode());
                updateMigrated = true;
              }
            }
            catch (Exception e)
            {
              contactUpdate.setExtNationalityCode(address.getNationalityCode());
              updateMigrated = true;
            }

            try
            {
              if (contactInfoExt.getRegCode().length() == 0)
              {
                contactUpdate.setExtRegCode(address.getRegCode());
                updateMigrated = true;
              }
            }
            catch (Exception e)
            {
              contactUpdate.setExtRegCode(address.getRegCode());
              updateMigrated = true;
            }


            if (updateMigrated)
            {
              logger.logmessage("CLIENT: " + contactUpdate.toString() + "\n");
              response = EPPuplink.sendCommand(contactUpdate);
              logger.logmessage("SERVER: " + response.toString() + "\n");

              if (!response.isSuccessfully())
              {
                migratedUpdateOK = false;
                if (JOptionPane.showConfirmDialog(this, "An error occurred while applying changes to the Registry.\n\nDo you want to see the Registry XML response?", "Registry (M) update failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
                {
                  JOptionPane.showMessageDialog(this, response.toString());
                }
              }
              contactUpdate = new ContactUpdate(address.getContactId());
            }
          }

          if (migratedUpdateOK)
          {

            contactUpdate.setFax(address.getFax());
            contactUpdate.setVoice(address.getVoice());
            contactUpdate.setEmail(address.getEmail());

            if (!address.getIsRegistrant() || address.isIsRegistrantChanged())
            {
              contactUpdate.setName(address.getContactName());
              contactUpdate.setOrg(address.getOrg());
            }
            else if (address.getEntityType() != 1)
            {
              contactUpdate.setName(address.getContactName());
            }
            contactUpdate.setCity(address.getCity());
            contactUpdate.addStreet(address.getStreet());
            contactUpdate.setSp(address.getStateOrProvince());
            contactUpdate.setPc(address.getPostalCode());
            contactUpdate.setCc(address.getCountryCode());
            if(!address.getSchoolCode().isEmpty())
              contactUpdate.setExtSchoolCode(address.getSchoolCode());

            contactUpdate.setExtConsForPub(address.getConsentForPublishing());

            logger.logmessage("CLIENT: " + contactUpdate.toString() + "\n");
            response = EPPuplink.sendCommand(contactUpdate);
            logger.logmessage("SERVER: " + response.toString() + "\n");


            if (response.isSuccessfully())
            {
              db.editRecord(address);
              address.isIsRegistrantChanged(false);
              ListEntry entry = addressListPanel.getSelectedListEntry();
              entry.setContactName(address.getContactName());
              addressListPanel.repaint();
              addressPanel.setEditable(false);
            }
            else
            {
              if (JOptionPane.showConfirmDialog(this, "An error occurred while applying changes to the Registry.\n\nDo you want to see the Registry XML response?", "Registry update failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
              {
                JOptionPane.showMessageDialog(this, response.toString());
              }
            }

          }

        }
        catch (NullPointerException v)
        {
          v.printStackTrace();
        }
        catch (XmlException v)
        {
          v.printStackTrace();
        }
        catch (IOException v)
        {
          JOptionPane.showMessageDialog(this, v.getCause().toString());
          v.printStackTrace();
        }
      }
    }
  }

  private void checkContact()
  {
    String contactIds = (String) JOptionPane.showInputDialog(this, "Please digit contact IDs you want to Check for Availability", "Contact Availability Check", JOptionPane.INFORMATION_MESSAGE, null, null, "");
    try
    {
      ContactCheck contactCheck = new ContactCheck();
      for (String contactId : contactIds.split(";"))
      {
        contactCheck.addId(contactId);
      }

      logger.logmessage("CLIENT: " + contactCheck.toString() + "\n");
      HttpBaseResponse response = EPPuplink.sendCommand(contactCheck);
      logger.logmessage("SERVER: " + response.toString() + "\n");

      if (response.isSuccessfully())
      {
        String msgAvailabilityResult = "";
        ContactCheckResponseResData resData = (ContactCheckResponseResData) response.getResponseResData();
        for (int i = 0; i < resData.getChkSize(); i++)
        {
          msgAvailabilityResult += "" + resData.getChkId(i) + " : ";
          if (resData.getChkAvail(i))
          {
            msgAvailabilityResult += "Available";
          }
          else
          {
            msgAvailabilityResult += "NOT Available";
            if (resData.getChkReasonText(i) != null)
              msgAvailabilityResult += " (" + resData.getChkReasonText(i) + ")";
          }
          msgAvailabilityResult += "\n";
        }
        JOptionPane.showMessageDialog(this, msgAvailabilityResult, "Contact Check Result", JOptionPane.INFORMATION_MESSAGE);
      }
      else
      {
        if (JOptionPane.showConfirmDialog(this, "An error occurred while checking contact availability on the Registry.\n\nDo you want to see the Registry XML response?", "Registry contact check failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
        {
          JOptionPane.showMessageDialog(this, response.toString());
        }
      }


    }
    catch (NullPointerException v)
    {
    }
    catch (XmlException v)
    {
    }
    catch (IOException v)
    {
    }
  }

  private void infoContact()
  {
    String contactId = addressPanel.getContactId();
    if (!contactId.equals(""))
    {

      try
      {
        ContactInfo contactInfo = new ContactInfo(contactId);
        logger.logmessage("CLIENT: " + contactInfo.toString() + "\n");
        HttpBaseResponse response = EPPuplink.sendCommand(contactInfo);
        logger.logmessage("SERVER: " + response.toString() + "\n");

        if (response.isSuccessfully())
        {
          ContactRawInfo contactRawInfo = new ContactRawInfo(contactId, response.toString());
          contactRawInfo.setVisible(true);
        }
        else
        {
          if (JOptionPane.showConfirmDialog(this, "An error occurred while asking for Contact Info on the Registry.\n\nDo you want to see the Registry XML response?", "Registry delete failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
          {
            JOptionPane.showMessageDialog(this, response.toString());
          }
          parseContactResult(response);
        }


      }
      catch (NullPointerException v)
      {
      }
      catch (XmlException v)
      {
      }
      catch (IOException v)
      {
      }

    }
  }

  public void syncContactInfo()
  {
    String contactId = (String) JOptionPane.showInputDialog(this, "Please digit the contact ID you want to sync", "Contact Sync", JOptionPane.INFORMATION_MESSAGE, null, null, addressPanel.getContactId());

    if (contactId != null)
    {
      ImportContact syncContact = new ImportContact(mainFrame, contactId);
      if (syncContact.execute())
      {
        addressListPanel.deleteAllEntries();
        List<ListEntry> entries = db.getListEntries();
        addressListPanel.addListEntries(entries);
      }
      else
      {
        JOptionPane.showMessageDialog(this, "Si è verificato un errore durante la sincronizzazione dei dati del contatto " + contactId + "!", "Errore sincronizzazione contatto", JOptionPane.WARNING_MESSAGE);
      }

      syncContact = null;
    }
  }

  private void parseContactResult(HttpBaseResponse response)
  {
    try
    {

      switch (response.getResultCode())
      {
        case 2303:
          if (response.getReasonCode() == 9003)
          {
            //Cancello il contatto dal db locale
//                        db = new contactsDao();
//                        db.connect();


            /*2012.06.15: Modifica libreria ITNIC*/
            //db.deleteRecord(response.getErrValue());
            db.deleteRecord(response.getErrValueTagValue(0));


//                        db.disconnect();
            int selectedIndex = addressListPanel.deleteSelectedEntry();
            if (selectedIndex >= 0)
            {
              selectedIndex = addressListPanel.setSelectedIndex(selectedIndex);
              ListEntry entry = addressListPanel.getSelectedListEntry();
              if (entry != null)
              {
//                                db = new contactsDao();
//                                db.connect();
                Address address = db.getAddress(entry.getContactId());
//                                db.disconnect();
                addressPanel.setAddress(address);
              }
              else
              {
                addressPanel.clear();
              }
            }
          }
          break;
        default:
          break;
      }
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }
  }

  public void actionPerformed(ActionEvent e)
  {
    String actionCommand = e.getActionCommand();
    if (actionCommand.equalsIgnoreCase("CANCEL_ADDRESS"))
    {
      cancelAddress();
    }
    else if (actionCommand.equalsIgnoreCase("NEW_ADDRESS"))
    {
      newAddress();
    }
    else if (actionCommand.equalsIgnoreCase("CLONE_ADDRESS"))
    {
      cloneAddress();
    }
    else if (actionCommand.equalsIgnoreCase("DELETE_ADDRESS"))
    {
      deleteAddress();
    }
    else if (actionCommand.equalsIgnoreCase("EDIT_ADDRESS"))
    {
      editAddress();
    }
    else if (actionCommand.equalsIgnoreCase("SAVE_ADDRESS"))
    {
      saveAddress();
    }
    else if (actionCommand.equalsIgnoreCase("SAVE_ADDRESS"))
    {
      selectAddress();
    }
    else if (actionCommand.equalsIgnoreCase("CHECK_CONTACT"))
    {
      checkContact();
    }
    else if (actionCommand.equalsIgnoreCase("SYNC_CONTACT"))
    {
      syncContactInfo();
    }
    else if (actionCommand.equalsIgnoreCase("INFO_CONTACT"))
    {
      infoContact();
    }
  }

  public void valueChanged(ListSelectionEvent e)
  {
    cancelAddress();
    if (e.getValueIsAdjusting())
    {
      return;
    }
    JList entryList = (JList) e.getSource();
    selectedEntry = entryList.getSelectedIndex();
    ListEntry entry = (ListEntry) entryList.getSelectedValue();
    if (entry != null)
    {
      String contactId = entry.getContactId();
//            db = new contactsDao();
//            db.connect();
      Address address = db.getAddress(contactId);
//            db.disconnect();
      addressPanel.setAddress(address);
    }
    else
    {
      addressPanel.clear();
    }
  }


  private static String selectedContactId;

  private int selectedEntry = -1;
  private contactsDao db;
  private WindowAdapter windowAdapter;

  public void setVisible(boolean b)
  {
    super.setVisible(b);
    if (b)
    {
      cancelAddress();
      refreshContactList();
    }

  }

  class WindowCloser extends WindowAdapter
  {
    @Override
    public void windowClosing(WindowEvent e)
    {
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private AddressActionPanel addressActionPanel;
  private AddressPanel addressPanel;
  private AddressListPanel addressListPanel;
  // End of variables declaration//GEN-END:variables
  private logger logger;
  private EPPuplink EPPuplink;
}
