/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.contacts;

import javax.swing.*;
import java.awt.*;

public class ContactRawInfo extends JFrame
{

  /**
   * Creates new form DomainRawInfo
   */
  public ContactRawInfo(String domainName, String domainRawInfo)
  {
    initComponents();

    contactIDTxt.setText(domainName);
    contactRawInfoTxt.setText(domainRawInfo);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new JLabel();
    contactIDTxt = new JTextField();
    jLabel2 = new JLabel();
    jScrollPane1 = new JScrollPane();
    contactRawInfoTxt = new JTextArea();

    //======== this ========
    setTitle("Contact INFO Output");
    Container contentPane = getContentPane();

    //---- jLabel1 ----
    jLabel1.setText("Contact ID");

    //---- contactIDTxt ----
    contactIDTxt.setEditable(false);
    contactIDTxt.setText("jTextField1");

    //---- jLabel2 ----
    jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
    jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
    jLabel2.setText("CONTACT INFO OUTPUT");

    //======== jScrollPane1 ========
    {

      //---- contactRawInfoTxt ----
      contactRawInfoTxt.setColumns(20);
      contactRawInfoTxt.setRows(5);
      jScrollPane1.setViewportView(contactRawInfoTxt);
    }

    GroupLayout contentPaneLayout = new GroupLayout(contentPane);
    contentPane.setLayout(contentPaneLayout);
    contentPaneLayout.setHorizontalGroup(
      contentPaneLayout.createParallelGroup()
        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jLabel1)
          .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(contactIDTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addContainerGap(352, Short.MAX_VALUE))
        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        .addGroup(contentPaneLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
          .addContainerGap())
    );
    contentPaneLayout.setVerticalGroup(
      contentPaneLayout.createParallelGroup()
        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
          .addComponent(jLabel2)
          .addGap(8, 8, 8)
          .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1)
            .addComponent(contactIDTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
          .addContainerGap())
    );
    pack();
    setLocationRelativeTo(getOwner());
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel jLabel1;
  private JTextField contactIDTxt;
  private JLabel jLabel2;
  private JScrollPane jScrollPane1;
  private JTextArea contactRawInfoTxt;
  // End of variables declaration//GEN-END:variables

}
