/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient. If not, see <https://www.gnu.org/licenses/>.
 */

package EPPClient.messages;

import EPPClient.config.EPPparams;
import EPPClient.db.messagesDao;
import EPPClient.logger;
import EPPClient.main;
import EPPClient.uplink.EPPuplink;
import EPPClient.importer.ImportDomain;
import it.nic.epp.client.commands.query.Poll;
import it.nic.epp.client.commands.transform.DomainTransfer;
import it.nic.epp.client.exceptions.EppSchemaException;
import it.nic.epp.client.responses.HttpBaseResponse;
import it.nic.epp.client.responses.ext.PollingResponseExt;
import it.nic.epp.client.responses.resData.PollingResponseResData;
import org.apache.xmlbeans.XmlException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

public class MessageDetail extends JFrame
{

  private EPPuplink EPPuplink;
  private logger logger;
  private Message message;
  private messagesDao db;
  private MessageManagement parentFrame;
  private main mainFrame;

  it.nic.epp.client.responses.CommandResponse response = null;
  PollingResponseResData resData;
  PollingResponseExt extData;

  /**
   * Creates new form MessageDetail
   */
  public MessageDetail(main mainFrame, MessageManagement parentFrame, Message messageIn)
  {
    initComponents();

    this.mainFrame = mainFrame;
    this.EPPuplink = mainFrame.EPPuplink;
    this.parentFrame = parentFrame;
    this.db = mainFrame.messagesDao;


    logger = new logger("MESSAGE");
    java.text.SimpleDateFormat dateFormatter = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    this.message = messageIn;

    this.msgIdTxt.setText(message.getMsgId());
    this.datetimeTxt.setText(dateFormatter.format(message.getDateTime()));
    this.messageTxt.setText(message.getTitle());
    this.rawMessageTxt.setText(message.getXml());

    try
    {
      response = new it.nic.epp.client.responses.CommandResponse(message.getXml());
    }
    catch (XmlException e)
    {
      e.printStackTrace();
    }

    resData = (PollingResponseResData) response.getResponseResData();
    extData = (PollingResponseExt) response.getResponseExtension();

    switchAck();

    if (!message.getRead())
    {
      message.setRead(true);
      db.editRecord(message);
      parentFrame.updateTableContent();
    }


  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jLabel1 = new JLabel();
    msgIdTxt = new JTextField();
    jLabel2 = new JLabel();
    jLabel3 = new JLabel();
    jScrollPane1 = new JScrollPane();
    rawMessageTxt = new JTextArea();
    jLabel4 = new JLabel();
    datetimeTxt = new JTextField();
    btnAck = new JButton();
    actionTab = new JTabbedPane();
    jPanel4 = new JPanel();
    jScrollPane3 = new JScrollPane();
    txtGeneric = new JTextArea();
    jPanel1 = new JPanel();
    btnTransfer = new JButton();
    jScrollPane2 = new JScrollPane();
    txtTransfer = new JTextArea();
    jPanel3 = new JPanel();
    jScrollPane5 = new JScrollPane();
    txtOther = new JTextArea();
    btnOther = new JButton();
    jScrollPane4 = new JScrollPane();
    messageTxt = new JTextArea();
    jPanel2 = new JPanel();

    //======== this ========
    setTitle("Dettaglio MESSAGGIO");
    Container contentPane = getContentPane();

    //---- jLabel1 ----
    jLabel1.setText("Message ID:");

    //---- msgIdTxt ----
    msgIdTxt.setEditable(false);
    msgIdTxt.setText("jTextField1");

    //---- jLabel2 ----
    jLabel2.setText("Message:");

    //---- jLabel3 ----
    jLabel3.setText("Raw Message:");

    //======== jScrollPane1 ========
    {

      //---- rawMessageTxt ----
      rawMessageTxt.setColumns(20);
      rawMessageTxt.setEditable(false);
      rawMessageTxt.setRows(5);
      jScrollPane1.setViewportView(rawMessageTxt);
    }

    //---- jLabel4 ----
    jLabel4.setText("Date/Time:");

    //---- datetimeTxt ----
    datetimeTxt.setEditable(false);
    datetimeTxt.setText("jTextField2");

    //---- btnAck ----
    btnAck.addActionListener(e -> btnAckActionPerformed(e));

    //======== actionTab ========
    {

      //======== jPanel4 ========
      {
        jPanel4.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
          @Override
          public void propertyChange(java.beans.PropertyChangeEvent e
          )
          {
            if ("borde\u0072".equals(e.getPropertyName())) throw new RuntimeException();
          }
        });

        //======== jScrollPane3 ========
        {

          //---- txtGeneric ----
          txtGeneric.setColumns(20);
          txtGeneric.setEditable(false);
          txtGeneric.setLineWrap(true);
          txtGeneric.setRows(7);
          txtGeneric.setText("This is a generic message, therefore no specific action panel has been enabled.");
          txtGeneric.setWrapStyleWord(true);
          jScrollPane3.setViewportView(txtGeneric);
        }

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup()
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup()
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(57, Short.MAX_VALUE))
        );
      }
      actionTab.addTab("Generic", jPanel4);

      //======== jPanel1 ========
      {

        //---- btnTransfer ----
        btnTransfer.addMouseListener(new MouseAdapter()
        {
          @Override
          public void mouseReleased(MouseEvent e)
          {
            btnTransferMouseReleased(e);
          }
        });

        //======== jScrollPane2 ========
        {

          //---- txtTransfer ----
          txtTransfer.setColumns(20);
          txtTransfer.setEditable(false);
          txtTransfer.setLineWrap(true);
          txtTransfer.setRows(7);
          txtTransfer.setWrapStyleWord(true);
          jScrollPane2.setViewportView(txtTransfer);
        }

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup()
                                        .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                        .addComponent(btnTransfer, GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTransfer)
                                .addContainerGap(41, Short.MAX_VALUE))
        );
      }
      actionTab.addTab("Transfer", jPanel1);

      //======== jPanel3 ========
      {

        //======== jScrollPane5 ========
        {

          //---- txtOther ----
          txtOther.setColumns(20);
          txtOther.setEditable(false);
          txtOther.setLineWrap(true);
          txtOther.setRows(7);
          txtOther.setWrapStyleWord(true);
          jScrollPane5.setViewportView(txtOther);
        }

        //---- btnOther ----
        btnOther.addMouseListener(new MouseAdapter()
        {
          @Override
          public void mouseReleased(MouseEvent e)
          {
            btnOtherMouseReleased(e);
          }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup()
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup()
                                        .addComponent(jScrollPane5, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                        .addComponent(btnOther, GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup()
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOther)
                                .addContainerGap(41, Short.MAX_VALUE))
        );
      }
      actionTab.addTab("other...", jPanel3);
    }

    //======== jScrollPane4 ========
    {

      //---- messageTxt ----
      messageTxt.setColumns(20);
      messageTxt.setEditable(false);
      messageTxt.setLineWrap(true);
      messageTxt.setRows(2);
      messageTxt.setWrapStyleWord(true);
      jScrollPane4.setViewportView(messageTxt);
    }

    GroupLayout contentPaneLayout = new GroupLayout(contentPane);
    contentPane.setLayout(contentPaneLayout);
    contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(actionTab, GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                                    .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(msgIdTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(datetimeTxt, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(contentPaneLayout.createParallelGroup()
                                                    .addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)))
                                    .addGroup(contentPaneLayout.createSequentialGroup()
                                            .addContainerGap(478, Short.MAX_VALUE)
                                            .addComponent(btnAck)))
                            .addContainerGap())
    );
    contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                    .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(msgIdTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(datetimeTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAck)
                            .addGap(11, 11, 11)
                            .addComponent(actionTab, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
    );
    pack();
    setLocationRelativeTo(getOwner());

    //======== jPanel2 ========
    {
      jPanel2.addPropertyChangeListener(new java.beans.PropertyChangeListener()
      {
        @Override
        public void propertyChange(java
                                           .beans.PropertyChangeEvent e)
        {
          if ("bord\u0065r".equals(e.getPropertyName())) throw new RuntimeException
                  ();
        }
      });

      GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
              jPanel2Layout.createParallelGroup()
                      .addGap(0, 100, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
              jPanel2Layout.createParallelGroup()
                      .addGap(0, 100, Short.MAX_VALUE)
      );
    }
  }// </editor-fold>//GEN-END:initComponents

  private void btnAckActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_btnAckActionPerformed
    ackMessage(message.getMsgId());
  }//GEN-LAST:event_btnAckActionPerformed

  private void btnTransferMouseReleased(MouseEvent evt)
  {//GEN-FIRST:event_btnTransferMouseReleased
    boolean doOp = false;

    if (message.getActioned())
    {
      doOp = JOptionPane.showConfirmDialog(this, "The operation has been already executed. Do you want to execute-it again?", "Confirm to re-execute an action", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0;
    }
    else
    {
      doOp = true;
    }

    if (doOp)
    {
      if (resData.getTranferMsgReID().equals(EPPparams.getParameter("EppClient.defaultUser")))
      {
        //We requested this transfer
        txtTransfer.setText("The transfer of the domain name " + resData.getTranferMsgName() + " to Registrar " + EPPparams.getParameter("EppClient.defaultUser") + " has been ");
        if (resData.getTranferMsgTrStatus().equals("clientApproved"))
        {
          ImportDomain transferredDomain = new ImportDomain(mainFrame, true);
          if (transferredDomain.execute(resData.getTranferMsgName()))
          {
            txtTransfer.setText(txtTransfer.getText() + "\nThe domain name has been successfully added to the client local database.");
            message.setActioned(true);
            db.editRecord(message);
            if (!message.getAck())
            {
              if (ackMessage(message.getMsgId()))
              {
                txtTransfer.setText(txtTransfer.getText() + ", this message has been automatically Acked.");
              }
              else
              {
                txtTransfer.setText(txtTransfer.getText() + ", an error occurred while Ack'ing the message.");
              }
            }
          }
          else
          {
            txtTransfer.setText(txtTransfer.getText() + "\nAn error occurred while importing the domain name to the client local database.");
          }
        }

      }
      else
      {
        //Someone else requested this transfer
        if (resData.getTranferMsgTrStatus().equals("pending"))
        {
          DomainTransfer domainTransfer = null;
          switch (JOptionPane.showConfirmDialog(this, "There is a new request to transfer the domain " + resData.getTranferMsgName() + " to registrar " + resData.getTranferMsgReID() + ".\n\nDo you want to aknowledge the transfer?", "New Outbound transfer request", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE))
          {
            case 0:
              domainTransfer = new DomainTransfer(resData.getTranferMsgName());
              domainTransfer.setTransferApprove();
              logger.logmessage(domainTransfer.toString());
              try
              {
                response = EPPuplink.sendCommand(domainTransfer);
              }
              catch (XmlException e)
              {
                e.printStackTrace();
              }
              catch (IOException e)
              {
                e.printStackTrace();
              }
              logger.logmessage(response.toString());
              if (response.isSuccessfully())
              {
                txtTransfer.setText(txtTransfer.getText() + "\n============\nThe transfer has been successfully Acknowledged!");
                message.setActioned(true);
                db.editRecord(message);
                if (!message.getAck())
                {
                  if (ackMessage(message.getMsgId()))
                  {
                    txtTransfer.setText(txtTransfer.getText() + ", this message has been automatically Acked.");
                  }
                  else
                  {
                    txtTransfer.setText(txtTransfer.getText() + ", an error occurred while Ack'ing the message.");
                  }
                }
              }
              else
              {
                txtTransfer.setText(txtTransfer.getText() + "\n============\nAn error occurred while Acknowledging the transfer. This messages has NOT been Acked.");
              }
              break;
            case 1:
              domainTransfer = new DomainTransfer(resData.getTranferMsgName());
              domainTransfer.setTransferReject();
              logger.logmessage(domainTransfer.toString());
              try
              {
                response = EPPuplink.sendCommand(domainTransfer);
              }
              catch (XmlException e)
              {
                e.printStackTrace();
              }
              catch (IOException e)
              {
                e.printStackTrace();
              }
              logger.logmessage(response.toString());
              if (response.isSuccessfully())
              {
                txtTransfer.setText(txtTransfer.getText() + "\n============\nThe transfer has been successfully Rejected!");
                message.setActioned(true);
                db.editRecord(message);
                if (!message.getAck())
                {
                  if (ackMessage(message.getMsgId()))
                  {
                    txtTransfer.setText(txtTransfer.getText() + " This message has been automatically Acked.");
                  }
                  else
                  {
                    txtTransfer.setText(txtTransfer.getText() + " An error occurred while Ack'ing the message.");
                  }
                }
              }
              else
              {
                txtTransfer.setText(txtTransfer.getText() + "\n============\nAn error occurred while Rejecting the transfer. This messages has NOT been Acked.");
              }
              break;
            case 2:
              JOptionPane.showMessageDialog(this, "Doing nothing!");
              break;
          }
        }
        else if (resData.getTranferMsgTrStatus().equals("clientApproved") || resData.getTranferMsgTrStatus().equals("serverApproved"))
        {
          mainFrame.domainsDao.deleteRecord(resData.getTranferMsgName());
          txtTransfer.setText(txtTransfer.getText() + "\n============\nThe domain name has been successfully deleted from the client local database.");
          message.setActioned(true);
          db.editRecord(message);
          if (!message.getAck())
          {
            if (ackMessage(message.getMsgId()))
            {
              txtTransfer.setText(txtTransfer.getText() + " This message has been automatically Acked.");
            }
            else
            {
              txtTransfer.setText(txtTransfer.getText() + " An error occurred while Ack'ing the message.");
            }
          }
        }

      }
    }
  }//GEN-LAST:event_btnTransferMouseReleased

  private void btnOtherMouseReleased(MouseEvent evt)
  {//GEN-FIRST:event_btnOtherMouseReleased
    boolean doOp = false;

    if (message.getActioned())
    {
      doOp = JOptionPane.showConfirmDialog(this, "The operation has been already executed. Do you want to execute-it again?", "Confirm to re-execute an action", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0;
    }
    else
    {
      doOp = true;
    }

    if (doOp)
    {

      if (response.getMsgQText().equalsIgnoreCase("Domain has been deleted"))
      {
        mainFrame.domainsDao.deleteRecord(extData.getSimpleMsgDomains()[0]);
        txtOther.setText(txtOther.getText() + "\n============\nThe domain name has been successfully deleted from the client local database.");
        message.setActioned(true);
        db.editRecord(message);
        if (!message.getAck())
        {
          if (ackMessage(message.getMsgId()))
          {
            txtOther.setText(txtOther.getText() + " This message has been automatically Acked.");
          }
          else
          {
            txtOther.setText(txtOther.getText() + " An error occurred while Ack'ing the message.");
          }
        }
      }
      else if (response.getMsgQText().equalsIgnoreCase("autoRenewPeriod is expired"))
      {

        ImportDomain syncDomain = new ImportDomain(mainFrame, true);
        if (syncDomain.execute(extData.getChgStatusMsgName()))
        {
          txtOther.setText(txtOther.getText() + "\nThe domain name has been successfully updated on the client local database.");
          message.setActioned(true);
          db.editRecord(message);
          if (!message.getAck())
          {
            if (ackMessage(message.getMsgId()))
            {
              txtOther.setText(txtOther.getText() + ", this message has been automatically Acked.");
            }
            else
            {
              txtOther.setText(txtOther.getText() + ", an error occurred while Ack'ing the message.");
            }
          }
        }

      }

    }
  }//GEN-LAST:event_btnOtherMouseReleased

  protected String getMsgId()
  {
    return message.getMsgId();
  }

  public void setEPPEnablement(boolean EPPstatus)
  {
    btnAck.setVisible(EPPstatus);
    btnTransfer.setVisible(EPPstatus);
  }

  private void switchAck()
  {
    if (!message.getAck())
    {
      btnAck.setEnabled(true);
      btnAck.setText("click to ACK");
    }
    else
    {
      btnAck.setEnabled(false);
      btnAck.setText("msg Already ACKED");
    }

    actionTab.setEnabledAt(0, true);
    actionTab.setEnabledAt(1, false);
    actionTab.setEnabledAt(2, false);

    if (resData != null)
    {
      if (resData.isTransferMsg())
      {
        actionTab.setEnabledAt(0, false);
        actionTab.setEnabledAt(1, true);
        actionTab.setSelectedIndex(1);

        if (resData.getTranferMsgReID().equals(EPPparams.getParameter("EppClient.defaultUser")))
        {
          //We requested this transfer
          txtTransfer.setText("The transfer of the domain name " + resData.getTranferMsgName() + " to Registrar " + EPPparams.getParameter("EppClient.defaultUser") + " has been ");
          if (resData.getTranferMsgTrStatus().equals("clientRejected"))
          {
            txtTransfer.setText(txtTransfer.getText() + "REJECTED by the Losing Registrar.");
            btnTransfer.setText("---");
            btnTransfer.setEnabled(false);
          }
          else if (resData.getTranferMsgTrStatus().equals("clientApproved"))
          {
            txtTransfer.setText(txtTransfer.getText() + "APPROVED by the Losing Registrar, the Domain Name has been added to your account on the Registry. Please click the button below to save it on the client local database.");
            btnTransfer.setText("Save to local db");
            btnTransfer.setEnabled(true);
          }
          else
          {
            btnTransfer.setText(resData.getTranferMsgTrStatus());
            txtTransfer.setText("There is no specific action to do.");
            //btnTransfer.setText("---");
            btnTransfer.setEnabled(false);
          }

        }
        else
        {
          //Someone else requested this transfer
          if (resData.getTranferMsgTrStatus().equals("pending"))
          {
            txtTransfer.setText("There is a new request to transfer the domain name " + resData.getTranferMsgName() + " to Registrar " + EPPparams.getParameter("EppClient.defaultUser") + " to Registrar " + resData.getTranferMsgReID() + ". Please click the button below to ACK o REJ the Transfer (will also ACK the message).");
            btnTransfer.setText("Acknowledge/Reject Transfer");
            btnTransfer.setEnabled(true);
          }
          else if (resData.getTranferMsgTrStatus().equals("clientApproved") || resData.getTranferMsgTrStatus().equals("serverApproved"))
          {
            txtTransfer.setText("The domain name " + resData.getTranferMsgName() + " has been successfully transferred to Registrar " + resData.getTranferMsgReID() + ". Please click the button below to delete-it from the client local database.");
            btnTransfer.setText("Delete from local db");
            btnTransfer.setEnabled(true);
          }
          else
          {
            txtTransfer.setText("There is no specific action to do.");
            btnTransfer.setText("---");
            btnTransfer.setEnabled(false);
          }
        }
      }

    }
    else if (response.getMsgQText().equalsIgnoreCase("Domain has been deleted"))
    {
      actionTab.setEnabledAt(0, false);
      actionTab.setEnabledAt(1, false);
      actionTab.setEnabledAt(2, true);
      actionTab.setSelectedIndex(2);
      txtOther.setText("The domain name " + extData.getSimpleMsgDomains()[0] + " has been deleted. Please click the button below to delete-it from the client local database.");
      btnOther.setText("Delete from local db");
      btnOther.setEnabled(true);

    }
    else if (response.getMsgQText().equalsIgnoreCase("autoRenewPeriod is expired"))
    {
      actionTab.setEnabledAt(0, false);
      actionTab.setEnabledAt(1, false);
      actionTab.setEnabledAt(2, true);
      actionTab.setSelectedIndex(2);
      txtOther.setText("The domain name " + extData.getChgStatusMsgName() + " autoRenewPeriod is expired. Please click the button below to update the expiration date stored in the local database.");
      btnOther.setText("Update expiration date on local db");
      btnOther.setEnabled(true);
    }
  }

  protected boolean ackMessage(String msgQid)
  {
    boolean ackStatus = false;
    HttpBaseResponse response = null;
    try
    {
      Poll pollCmd = new Poll();
      pollCmd.setAck(msgQid);
      logger.logmessage("ACK: " + pollCmd.toString());
      response = EPPuplink.sendCommand(pollCmd);
      if (response.isSuccessfully())
      {
        ackStatus = true;
        message.setAck(true);
        db.editRecord(message);
        parentFrame.updateTableContent();
        switchAck();
        EPPuplink.doPoll();
      }
      else
      {
        if (JOptionPane.showConfirmDialog(this, "An error occurred while aknowledging a message.\n\nDo you want to see the Registry XML response?", "Registry adknowledgment failure", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
        {
          JOptionPane.showMessageDialog(this, response.toString());
        }
      }
    }
    catch (EppSchemaException v)
    {
      v.printStackTrace();
    }
    catch (XmlException v)
    {
      v.printStackTrace();
    }
    catch (IOException v)
    {
      v.printStackTrace();
    }

    return ackStatus;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel jLabel1;
  private JTextField msgIdTxt;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JScrollPane jScrollPane1;
  private JTextArea rawMessageTxt;
  private JLabel jLabel4;
  private JTextField datetimeTxt;
  private JButton btnAck;
  private JTabbedPane actionTab;
  private JPanel jPanel4;
  private JScrollPane jScrollPane3;
  private JTextArea txtGeneric;
  private JPanel jPanel1;
  private JButton btnTransfer;
  private JScrollPane jScrollPane2;
  private JTextArea txtTransfer;
  private JPanel jPanel3;
  private JScrollPane jScrollPane5;
  private JTextArea txtOther;
  private JButton btnOther;
  private JScrollPane jScrollPane4;
  private JTextArea messageTxt;
  private JPanel jPanel2;
  // End of variables declaration//GEN-END:variables

}
