/*
 * SPDX-FileCopyrightText: 2009-2025 AssoTLD <reg@assotld.it>
 * SPDX-FileCopyrightText: 2026 Riccardo Bertelli
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of EPPClient.
 *
 * EPPClient is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * EPPClient is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EPPClient.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package com.codetotime.eppclient.contacts;

import java.awt.Container;
import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;

/** Frame that displays the raw EPP info response for a contact. */
public class ContactRawInfo extends JFrame {

  /** Creates new form DomainRawInfo. */
  public ContactRawInfo(String domainName, String domainRawInfo) {
    initComponents();

    contactIdTxt.setText(domainName);
    contactRawInfoTxt.setText(domainRawInfo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    lblContactId = new JLabel();
    contactIdTxt = new JTextField();
    lblTitle = new JLabel();
    rawInfoScroll = new JScrollPane();
    contactRawInfoTxt = new JTextArea();

    // ======== this ========
    setTitle("Contact INFO Output");

    // ---- lblContactId ----
    lblContactId.setText("Contact ID");

    // ---- contactIdTxt ----
    contactIdTxt.setEditable(false);
    contactIdTxt.setText("jTextField1");

    // ---- lblTitle ----
    lblTitle.setFont(new Font("Tahoma", Font.BOLD, 11));
    lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
    lblTitle.setText("CONTACT INFO OUTPUT");

    // ======== rawInfoScroll ========
    {

      // ---- contactRawInfoTxt ----
      contactRawInfoTxt.setColumns(20);
      contactRawInfoTxt.setRows(5);
      rawInfoScroll.setViewportView(contactRawInfoTxt);
    }

    Container contentPane = getContentPane();
    GroupLayout contentPaneLayout = new GroupLayout(contentPane);
    contentPane.setLayout(contentPaneLayout);
    contentPaneLayout.setHorizontalGroup(
        contentPaneLayout
            .createParallelGroup()
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                contentPaneLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblContactId)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        contactIdTxt,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE))
            .addComponent(lblTitle, GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addGroup(
                contentPaneLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(rawInfoScroll, GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addContainerGap()));
    contentPaneLayout.setVerticalGroup(
        contentPaneLayout
            .createParallelGroup()
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                contentPaneLayout
                    .createSequentialGroup()
                    .addComponent(lblTitle)
                    .addGap(8, 8, 8)
                    .addGroup(
                        contentPaneLayout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactId)
                            .addComponent(
                                contactIdTxt,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(rawInfoScroll, GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addContainerGap()));
    pack();
    setLocationRelativeTo(getOwner());
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel lblContactId;
  private JTextField contactIdTxt;
  private JLabel lblTitle;
  private JScrollPane rawInfoScroll;
  private JTextArea contactRawInfoTxt;
  // End of variables declaration//GEN-END:variables

}
